// Cartografia de Leituras: glossário de línguas bíblicas com contexto, semântica e limites de tradução.

export type GlossaryLanguage = "Hebraico" | "Aramaico" | "Grego";

export type AdvancedGlossaryEntry = {
  id: string;
  term: string;
  original: string;
  language: GlossaryLanguage;
  transliteration: string;
  pronunciation: string;
  grammaticalNote: string;
  definition: string;
  semanticRange: string;
  translationNote: string;
  refs: string[];
  related: string[];
  methodology: "Léxico" | "Contexto" | "Debate";
  sources: { label: string; url: string }[];
};

const bibleOdyssey = "https://www.bibleodyssey.org/articles/why-does-the-bible-look-the-way-it-does/";
const sbl = "https://www.sbl-site.org/";

export const advancedGlossary: AdvancedGlossaryEntry[] = [
  { id: "hesed", term: "Hesed", original: "חֶסֶד", language: "Hebraico", transliteration: "ḥesed", pronunciation: "rê-séd", grammaticalNote: "Substantivo masculino; frequentemente aparece em construções de relação e aliança.", definition: "Vocabulário de lealdade relacional, bondade comprometida e ação favorável que sustenta uma relação.", semanticRange: "Dependendo do contexto pode apontar para misericórdia, lealdade, benevolência, fidelidade ou amor constante. Nenhum equivalente isolado resolve todos os usos.", translationNote: "Traduzir sempre por ‘misericórdia’ ou sempre por ‘amor’ pode esconder a dimensão de compromisso. A análise deve observar quem age, com quem, em qual relação e com qual consequência narrativa.", refs: ["Êx 34:6", "Rt 1:8", "Sl 136:1", "Os 6:6"], related: ["aliança", "misericórdia", "fidelidade"], methodology: "Léxico", sources: [{ label: "SBL — investigação bíblica", url: sbl }] },
  { id: "ruach", term: "Ruach", original: "רוּחַ", language: "Hebraico", transliteration: "rûaḥ", pronunciation: "ru-ár", grammaticalNote: "Substantivo feminino; seu campo inclui movimento, respiração e agência invisível.", definition: "Palavra que pode designar vento, sopro, respiração, disposição interior ou espírito, inclusive a ação do Espírito de Deus.", semanticRange: "O contexto decide se a imagem é meteorológica, antropológica, psicológica ou teológica. As camadas podem permanecer deliberadamente próximas em textos poéticos.", translationNote: "A tradução por ‘espírito’ em todos os casos pode apagar o aspecto de vento ou sopro; a tradução por ‘vento’ em textos teológicos pode apagar a agência divina.", refs: ["Gn 1:2", "Ez 37:1–14", "Jl 2:28–29"], related: ["pneuma", "vida", "Espírito Santo"], methodology: "Debate", sources: [{ label: "Bible Odyssey — cânon, manuscritos e tradições", url: bibleOdyssey }] },
  { id: "nephesh", term: "Nephesh", original: "נֶפֶשׁ", language: "Hebraico", transliteration: "nefeš", pronunciation: "né-fesh", grammaticalNote: "Substantivo feminino usado tanto para seres vivos quanto para a vida desejante.", definition: "Vida, pessoa, garganta, ser vivente ou centro de desejo; não corresponde automaticamente ao conceito grego posterior de ‘alma’ desencarnada.", semanticRange: "O termo pode enfatizar a vida concreta, o indivíduo, o apetite, o risco de morte ou a totalidade de uma pessoa.", translationNote: "A tradição de traduzir por ‘alma’ em alguns contextos é possível, mas exige cautela antropológica: o texto hebraico frequentemente fala da pessoa viva em sua inteireza.", refs: ["Gn 2:7", "Lv 17:11", "Sl 42:1–2"], related: ["psychē", "corpo", "vida"], methodology: "Debate", sources: [{ label: "SBL — investigação bíblica", url: sbl }] },
  { id: "torah", term: "Torah", original: "תּוֹרָה", language: "Hebraico", transliteration: "tôrāh", pronunciation: "to-rá", grammaticalNote: "Substantivo feminino; deriva de uma raiz associada a instrução e orientação.", definition: "Instrução, ensino ou orientação; pode nomear o Pentateuco como coleção, mas não se reduz à ideia moderna de código jurídico.", semanticRange: "Em diferentes contextos pode significar uma instrução específica, o ensino sacerdotal, a tradição escrita ou os cinco livros de Moisés.", translationNote: "‘Lei’ é uma tradução tradicional, mas pode sugerir apenas norma punitiva. ‘Instrução’ comunica melhor alguns usos narrativos e sapienciais.", refs: ["Dt 6:1–9", "Sl 1:1–3", "Ne 8:1–8"], related: ["nomos", "aliança", "sabedoria"], methodology: "Contexto", sources: [{ label: "Bible Odyssey — como a Bíblia assumiu sua forma", url: bibleOdyssey }] },
  { id: "qadosh", term: "Qadosh", original: "קָדוֹשׁ", language: "Hebraico", transliteration: "qādôš", pronunciation: "ca-dôsh", grammaticalNote: "Adjetivo; pode qualificar Deus, pessoas, lugares, tempos e objetos.", definition: "Separado, distinto, consagrado ou pertencente a uma esfera de santidade; a ideia de separação não elimina a dimensão ética.", semanticRange: "O termo percorre a distinção cultual, a alteridade divina e a convocação de uma comunidade a refletir a justiça de Deus.", translationNote: "‘Santo’ preserva a tradição, mas a interpretação precisa mostrar como o texto transforma santidade em prática comunitária, não apenas em distância ritual.", refs: ["Êx 19:5–6", "Lv 19:1–18", "Is 6:1–8"], related: ["hagios", "santificação", "culto"], methodology: "Contexto", sources: [{ label: "SBL — investigação bíblica", url: sbl }] },
  { id: "mishpat", term: "Mishpat", original: "מִשְׁפָּט", language: "Hebraico", transliteration: "mišpāṭ", pronunciation: "mish-pát", grammaticalNote: "Substantivo masculino; aparece em contextos jurídicos, sociais e teológicos.", definition: "Juízo, decisão, direito ou ordem justa que regula relações e protege a vida comunitária.", semanticRange: "Pode designar um caso decidido, uma norma, a administração da justiça ou o juízo de Deus sobre uma sociedade.", translationNote: "‘Justiça’ e ‘juízo’ cobrem partes do campo semântico; o leitor deve perguntar se o texto trata de tribunal, ordem social ou ação divina.", refs: ["Êx 21:1", "Am 5:24", "Mq 6:8"], related: ["dikaiosynē", "justiça", "profeta"], methodology: "Contexto", sources: [{ label: "Bible Odyssey — cânon e leitura comunitária", url: bibleOdyssey }] },
  { id: "emet", term: "Emet", original: "אֱמֶת", language: "Hebraico", transliteration: "ʾemet", pronunciation: "ê-met", grammaticalNote: "Substantivo feminino; frequentemente associado a fidelidade, palavra e confiabilidade.", definition: "Verdade, firmeza, confiabilidade e fidelidade; não apenas correspondência abstrata entre frase e realidade.", semanticRange: "Em narrativas e salmos pode caracterizar uma pessoa, uma promessa, um testemunho ou a estabilidade da ação de Deus.", translationNote: "‘Verdade’ é adequada em muitos contextos, mas ‘fidelidade’ pode ser mais precisa quando o foco está no caráter confiável de uma relação.", refs: ["Gn 24:27", "Êx 34:6", "Sl 119:160"], related: ["alētheia", "fidelidade", "aliança"], methodology: "Léxico", sources: [{ label: "SBL — investigação bíblica", url: sbl }] },
  { id: "ab", term: "Abba", original: "אַבָּא", language: "Aramaico", transliteration: "ʾabbāʾ", pronunciation: "ab-bá", grammaticalNote: "Forma de tratamento familiar preservada em contexto grego do Novo Testamento.", definition: "Forma aramaica de dirigir-se ao pai; comunica intimidade e confiança, sem exigir a tradução infantilizada ‘papai’ em todos os contextos.", semanticRange: "O peso afetivo depende da relação, do ambiente de oração e da tradição de tradução. A palavra pode manter reverência e proximidade simultaneamente.", translationNote: "Em Mc 14:36 e Rm 8:15; Gl 4:6, preservar o aramaico seguido de explicação evidencia a memória linguística do movimento cristão primitivo.", refs: ["Mc 14:36", "Rm 8:15", "Gl 4:6"], related: ["patēr", "oração", "adoção"], methodology: "Debate", sources: [{ label: "Bible Odyssey — tradições e cânones", url: bibleOdyssey }] },
  { id: "mammon", term: "Mamom", original: "מָמוֹנָא", language: "Aramaico", transliteration: "māmônāʾ", pronunciation: "ma-mo-ná", grammaticalNote: "Substantivo aramaico incorporado ao discurso grego como nome próprio ou personificação.", definition: "Riqueza, patrimônio ou poder econômico quando tratado como senhor rival da lealdade humana.", semanticRange: "O termo não é simplesmente sinônimo de dinheiro; em Mt 6:24 e Lc 16:9–13, a linguagem personifica a riqueza como poder que reivindica serviço.", translationNote: "Traduzir por ‘dinheiro’ torna a frase concreta, mas pode reduzir a crítica à posse individual e apagar a dimensão de senhorio e lealdade.", refs: ["Mt 6:24", "Lc 16:9–13"], related: ["oikonomia", "riqueza", "idolatria"], methodology: "Contexto", sources: [{ label: "SBL — investigação bíblica", url: sbl }] },
  { id: "logos", term: "Logos", original: "λόγος", language: "Grego", transliteration: "logos", pronunciation: "ló-gos", grammaticalNote: "Substantivo masculino com um campo semântico muito amplo.", definition: "Palavra, discurso, mensagem, razão, relato ou princípio articulador; em João 1, recebe função cristológica singular.", semanticRange: "O sentido resulta do gênero, do contexto e das relações intertextuais. Não deve ser preenchido automaticamente com toda a filosofia grega nem reduzido a ‘palavra’ sem análise.", translationNote: "Em João 1, a tradução tradicional ‘Verbo’ preserva uma história teológica, enquanto ‘Palavra’ é mais transparente; ambas precisam de comentário contextual.", refs: ["Jo 1:1–18", "At 6:7", "Hb 4:12"], related: ["rhēma", "sabedoria", "Cristo"], methodology: "Debate", sources: [{ label: "SBL — investigação bíblica", url: sbl }] },
  { id: "pneuma", term: "Pneuma", original: "πνεῦμα", language: "Grego", transliteration: "pneuma", pronunciation: "pneu-ma", grammaticalNote: "Substantivo neutro; pode aparecer com sentidos físicos, antropológicos, demonológicos e teológicos.", definition: "Vento, sopro, espírito, disposição interior ou Espírito Santo, conforme o contexto literário e sintático.", semanticRange: "O Novo Testamento explora a plasticidade do termo; em João, Paulo e Lucas, a mesma palavra participa de argumentos diferentes sobre vida, discernimento e missão.", translationNote: "O tradutor deve distinguir espírito humano, espírito imundo e Espírito Santo sem apagar os jogos semânticos que o autor constrói.", refs: ["Jo 3:5–8", "At 2:1–21", "1Co 12:4–11"], related: ["ruach", "charisma", "batismo no Espírito"], methodology: "Léxico", sources: [{ label: "SBL — investigação bíblica", url: sbl }] },
  { id: "dikaiosyne", term: "Dikaiosynē", original: "δικαιοσύνη", language: "Grego", transliteration: "dikaiosynē", pronunciation: "di-kai-o-sý-ne", grammaticalNote: "Substantivo feminino; participa do vocabulário jurídico, relacional e escatológico.", definition: "Justiça, retidão, condição de estar em relação correta ou ação que manifesta a fidelidade de Deus.", semanticRange: "Paulo emprega o campo para discutir a fidelidade de Deus, a situação humana, a inclusão de gentios e a vida comunitária; o debate não se resolve por uma definição única.", translationNote: "‘Justiça’ pode sugerir apenas moralidade individual; em Romanos, o contexto exige considerar tribunal, aliança, fé, comunidade e esperança escatológica.", refs: ["Mt 5:6", "Rm 1:16–17", "Fp 3:9"], related: ["mishpat", "pistis", "justificação"], methodology: "Debate", sources: [{ label: "SBL — investigação bíblica", url: sbl }] },
  { id: "pistis", term: "Pistis", original: "πίστις", language: "Grego", transliteration: "pistis", pronunciation: "pís-tis", grammaticalNote: "Substantivo feminino; pode expressar confiança, fidelidade ou a fé confessada.", definition: "Confiança, fé, fidelidade ou lealdade; o sentido depende do agente, do objeto e da relação construída no texto.", semanticRange: "Em alguns contextos descreve a confiança de uma pessoa; em outros, a fidelidade que caracteriza uma vida ou uma comunidade. A discussão ‘fé versus fidelidade’ é real, mas não deve ser resolvida por slogans.", translationNote: "A tradução por ‘fé’ preserva a linguagem confessional; ‘fidelidade’ ilumina certos contextos éticos. O leitor deve acompanhar sintaxe e argumento.", refs: ["Rm 3:21–26", "Gl 5:6", "Hb 11:1–2"], related: ["emunah", "graça", "aliança"], methodology: "Debate", sources: [{ label: "Bible Odyssey — investigação bíblica", url: bibleOdyssey }] },
  { id: "charis", term: "Charis", original: "χάρις", language: "Grego", transliteration: "charis", pronunciation: "kha-rís", grammaticalNote: "Substantivo feminino; percorre relações de favor, gratidão, beleza e dom.", definition: "Graça, favor, benevolência ou gratidão; em Paulo, descreve a iniciativa generosa de Deus e também o efeito comunitário dessa iniciativa.", semanticRange: "Não é uma substância abstrata armazenada na pessoa. O termo pode nomear o favor recebido, a ação de agradecer e o dom que reorganiza relações.", translationNote: "‘Graça’ é tradição indispensável, mas precisa ser lida em contraste com mérito, patronagem, dívida e reciprocidade no mundo antigo.", refs: ["Lc 1:30", "Jo 1:14–17", "Ef 2:8–10"], related: ["dōrea", "pistis", "generosidade"], methodology: "Contexto", sources: [{ label: "SBL — investigação bíblica", url: sbl }] },
  { id: "agape", term: "Agapē", original: "ἀγάπη", language: "Grego", transliteration: "agapē", pronunciation: "a-ga-pe", grammaticalNote: "Substantivo feminino; torna-se linguagem central na ética cristã primitiva.", definition: "Amor orientado ao bem do outro e à fidelidade comunitária, sem que o termo possa ser reduzido a sentimento sem conflito.", semanticRange: "Em João e Paulo, o amor inclui ação, discernimento, renúncia ao privilégio e compromisso com a verdade; não é mera aprovação.", translationNote: "A distinção popular entre eros, philia e agapē é simplificada demais para servir como regra exegética. O contexto literário é decisivo.", refs: ["Jo 13:34–35", "1Co 13", "1Jo 4:7–12"], related: ["hesed", "koinōnia", "ética"], methodology: "Debate", sources: [{ label: "SBL — investigação bíblica", url: sbl }] },
  { id: "ekklesia", term: "Ekklesia", original: "ἐκκλησία", language: "Grego", transliteration: "ekklēsia", pronunciation: "ek-kle-sí-a", grammaticalNote: "Substantivo feminino; nomeia uma assembleia e, em textos cristãos, uma comunidade concreta.", definition: "Assembleia, reunião ou comunidade convocada; no Novo Testamento, não significa automaticamente uma instituição moderna com todas as suas estruturas posteriores.", semanticRange: "Pode designar a reunião local, a rede de comunidades ou a comunidade escatológica. Atos e cartas mostram práticas e conflitos, não apenas uma definição ideal.", translationNote: "‘Igreja’ é uma tradução histórica, mas o leitor deve recuperar a dimensão de assembleia, participação, disciplina e missão.", refs: ["Mt 16:18", "At 2:42–47", "1Co 12:12–27"], related: ["koinōnia", "synagōgē", "comunidade"], methodology: "Contexto", sources: [{ label: "Bible Odyssey — cânon e comunidades", url: bibleOdyssey }] },
  { id: "parousia", term: "Parousia", original: "παρουσία", language: "Grego", transliteration: "parousia", pronunciation: "pa-ru-sí-a", grammaticalNote: "Substantivo feminino; significa presença ou chegada e pode carregar linguagem política.", definition: "Presença, chegada ou visita oficial; no discurso escatológico, a palavra nomeia a esperança da presença/manifestação de Cristo.", semanticRange: "O termo pode falar de uma visita humana comum ou de uma expectativa escatológica. A leitura deve observar o contraste com ausência, demora, vigilância e ressurreição.", translationNote: "Traduzir sempre por ‘segunda vinda’ já interpreta o termo. Em alguns textos a tradução ‘presença’ ou ‘chegada’ expõe melhor a discussão.", refs: ["Mt 24:27", "1Ts 4:15", "2Pe 3:4"], related: ["apokalypsis", "elpis", "ressurreição"], methodology: "Debate", sources: [{ label: "SBL — investigação bíblica", url: sbl }] },
  { id: "apokalypsis", term: "Apokalypsis", original: "ἀποκάλυψις", language: "Grego", transliteration: "apokalypsis", pronunciation: "a-po-ka-lý-psis", grammaticalNote: "Substantivo feminino; formado pela ideia de retirar um véu.", definition: "Revelação ou desvelamento; não equivale simplesmente a destruição do mundo ou a calendário de eventos futuros.", semanticRange: "Pode nomear a manifestação de algo oculto, a revelação de Jesus Cristo e um gênero que interpreta o presente por visões simbólicas.", translationNote: "A palavra ‘apocalipse’ ganhou no português um sentido popular de catástrofe; a interface sempre mostrará o sentido literário e o uso popular separadamente.", refs: ["Rm 8:18–19", "Gl 1:12", "Ap 1:1"], related: ["eschaton", "profecia", "visão"], methodology: "Contexto", sources: [{ label: "Society of Biblical Literature", url: sbl }] },
  { id: "eschaton", term: "Eschaton", original: "ἔσχατος", language: "Grego", transliteration: "eschatos", pronunciation: "és-ka-tos", grammaticalNote: "Adjetivo; funciona como substantivo em expressões sobre o ‘último’.", definition: "Último, extremo ou derradeiro; pode descrever tempo, posição, prioridade social ou horizonte escatológico.", semanticRange: "Em João pode opor primeiro e último; em cartas e Apocalipse participa de uma imaginação de consumação. Não deve ser transformado imediatamente em cronograma.", translationNote: "‘Fim’ é uma possibilidade em algumas expressões, mas ‘último’ ou ‘derradeiro’ preserva melhor a polissemia.", refs: ["Jo 6:39–40", "1Co 15:45", "Ap 22:13"], related: ["parousia", "telos", "nova criação"], methodology: "Léxico", sources: [{ label: "Bible Odyssey — tradições de leitura", url: bibleOdyssey }] },
  { id: "koinonia", term: "Koinōnia", original: "κοινωνία", language: "Grego", transliteration: "koinōnia", pronunciation: "koi-no-ní-a", grammaticalNote: "Substantivo feminino associado a participação e partilha.", definition: "Comunhão, participação, parceria ou partilha de bens e missão; não se limita a sentimento de amizade.", semanticRange: "Em Atos, Paulo e 1 João, o termo envolve mesa, recursos, missão, sofrimento, Espírito e responsabilidade mútua.", translationNote: "‘Comunhão’ comunica a tradição, mas o leitor deve investigar quais práticas concretas tornam a comunhão visível no contexto.", refs: ["At 2:42", "Fp 1:5", "1Jo 1:3"], related: ["ekklesia", "agapē", "mesa"], methodology: "Contexto", sources: [{ label: "SBL — investigação bíblica", url: sbl }] },
  { id: "charisma", term: "Charisma", original: "χάρισμα", language: "Grego", transliteration: "charisma", pronunciation: "kha-rís-ma", grammaticalNote: "Substantivo neutro; deriva do campo de charis, dom gracioso.", definition: "Dom concedido pela graça, especialmente em contextos de serviço e edificação comunitária.", semanticRange: "Paulo usa o termo para dons diversos, vida, celibato e participação no corpo; não nomeia automaticamente performance pública ou status espiritual.", translationNote: "A tradução por ‘dom espiritual’ é útil, mas alguns contextos pedem ‘dom’ sem estreitar o sentido ao extraordinário.", refs: ["Rm 12:6–8", "1Co 12:4–11", "1Pe 4:10–11"], related: ["pneuma", "diakonia", "edificação"], methodology: "Contexto", sources: [{ label: "SBL — investigação bíblica", url: sbl }] },
];

export const glossaryLanguages: (GlossaryLanguage | "Todos")[] = ["Todos", "Hebraico", "Aramaico", "Grego"];
