// Cartografia de Leituras: dossiês avançados para leitores experientes, separando evidência, reconstrução e interpretação.
export type AdvancedDossier = {
  id: string;
  period: string;
  date: string;
  title: string;
  thesis: string;
  questions: string[];
  debates: string[];
  sources: string[];
  entities: string[];
  confidence: string;
};

export type BiblicalPlace = {
  id: string;
  name: string;
  ancientName: string;
  lat: number;
  lng: number;
  periods: string;
  dossier: string;
  summary: string;
  refs: string;
};

export const advancedDossiers: AdvancedDossier[] = [
  {
    id: "origins-levant", period: "Origens e Bronze", date: "c. 3300–1200 a.C.", title: "Cidades, impérios e a formação do Levante", thesis: "Antes de ser um cenário bíblico, Canaã era uma zona de cidades-estado, corredores imperiais e economias agrárias conectada ao Egito, à Síria e à Mesopotâmia.", questions: ["Como urbanização, pastoralismo e tributação reorganizaram o Levante?", "O que Ugarit, Amarna, Ebla e Mari permitem afirmar sobre Canaã?", "Como distinguir memória patriarcal, composição literária e história do Bronze?"], debates: ["Etnogênese de Israel: conquista, revolta camponesa, infiltração ou transformação interna", "Historicidade e cronologia do Êxodo e dos patriarcas", "Religião cananeia, El, Baal e Asherah em relação à normatividade bíblica"], sources: ["Cartas de Amarna e textos ugaríticos", "Estratigrafia de Hazor, Megido, Gezer e Jericó", "Dever, Finkelstein, Mazar e Liverani"], entities: ["Gênesis", "Êxodo", "Josué", "Hazor", "Megido", "Ugarit", "Canaã"], confidence: "Alta para camadas materiais e epigrafia; variável para correlações entre narrativas bíblicas e eventos do Bronze." },
  {
    id: "exodus-iron", period: "Êxodo e Ferro I", date: "c. 1300–1000 a.C.", title: "Êxodo, deserto e etnogênese de Israel", thesis: "O problema histórico não é apenas localizar uma rota, mas reconstruir como memórias de escravidão, deserto, aliança e assentamento produziram uma identidade coletiva.", questions: ["Qual escala demográfica e cronologia são historicamente plausíveis para o Êxodo?", "Como os assentamentos do Ferro I alteram os modelos de conquista e sedentarização?", "Que relação há entre Shasu, Apiru e os grupos que a Bíblia chama de Israel?"], debates: ["Conquista militar versus transformação endógena de Canaã", "Datação alta versus baixa para o Êxodo", "Camadas literárias do Pentateuco e sua relação com memória histórica"], sources: ["Estela de Merneptah", "Papiros Anastasi e cartas de Amarna", "Relatórios de assentamentos do Ferro I e estudos de Halpern, Dever e Finkelstein"], entities: ["Moisés", "Miriã", "Arão", "Merneptah", "Cades-Barneia", "Monte Ebal", "Jericó"], confidence: "Alta para algumas inscrições e padrões de assentamento; variável para rotas e eventos não diretamente atestados." },
  {
    id: "monarchy-temple", period: "Monarquia e templos", date: "c. 1000–586 a.C.", title: "Davi, Salomão, Israel e Judá entre texto e império", thesis: "A monarquia bíblica precisa ser estudada em paralelo com epigrafia, urbanismo, economia e propaganda real, sem reduzir Reis, Crônicas e profetas a uma única crônica neutra.", questions: ["Qual é a extensão histórica da Monarquia Unida?", "Como Israel e Judá se diferenciaram política e religiosamente?", "O que reformas de Ezequias e Josias significam em termos de centralização?"], debates: ["Cronologia convencional versus cronologia baixa", "Maximalismo e minimalismo na reconstrução da Monarquia Unida", "Monoteísmo normativo e práticas religiosas populares"], sources: ["Inscrição de Tel Dan e Estela de Mesa", "Anais assírios e Prisma de Senaqueribe", "Ostraca de Samaria e Arade; Finkelstein, Dever e Liverani"], entities: ["Samuel", "Reis", "Crônicas", "Davi", "Salomão", "Ezequias", "Josias", "Jerusalém", "Samaria"], confidence: "Alta para campanhas imperiais e várias inscrições; média para a escala e centralização do décimo século." },
  {
    id: "exile-restoration", period: "Exílio e restauração", date: "586–332 a.C.", title: "Babilônia, Yehud e as políticas da memória", thesis: "O exílio não foi um vazio entre duas histórias: foi uma reconfiguração administrativa, demográfica e teológica que redefiniu terra, templo, pureza e pertencimento.", questions: ["Como a deportação alterou as elites, a economia e a identidade de Judá?", "O que Al-Yahudu e Elefantina revelam sobre a diáspora?", "Como Esdras e Neemias devem ser lidos diante de cronologias concorrentes?"], debates: ["Território vazio versus continuidade demográfica", "Cronologia das missões de Esdras e Neemias", "Influência persa em angelologia, demonologia e escatologia"], sources: ["Cilindro de Ciro e documentos de Al-Yahudu", "Papiros de Elefantina e moedas de Yehud", "Lipschits, Albertz e Blenkinsopp"], entities: ["Jeremias", "Ezequiel", "Esdras", "Neemias", "Ester", "Ciro", "Nabucodonosor", "Babilônia", "Susa"], confidence: "Alta para documentação imperial e epigráfica; variável para cronologia literária de Esdras–Neemias." },
  {
    id: "hellenistic-hasmonean", period: "Helenismo e Hasmoneus", date: "332–63 a.C.", title: "Torá, helenização e soberania disputada", thesis: "A Judeia helenística não pode ser explicada por uma oposição simples entre fé e cultura: elites, sacerdotes, camponeses e grupos pietistas negociaram poder, língua e lealdade.", questions: ["Até onde avançou a helenização social e institucional?", "Como a crise de Antíoco IV catalisou guerra, martírio e apocaliptismo?", "Que legitimidade religiosa tinha a dinastia hasmoneia?"], debates: ["Torá imperial e formação institucional persa", "Hellenização por assimilação versus resistência", "1–2 Macabeus, Josefo e arqueologia dos conflitos"], sources: ["1–2 Macabeus e Flávio Josefo", "Numismática hasmoneia e escavações do Monte Gerizim", "Grabbe, Hengel e Schürer"], entities: ["Daniel", "1–2 Macabeus", "Antíoco IV", "Judas Macabeu", "João Hircano", "Jerusalém", "Gerizim"], confidence: "Alta para moedas e alguns estratos; média para reconstruções sociopolíticas baseadas em fontes literárias tardias." },
  {
    id: "second-temple", period: "Segundo Templo e judaísmos", date: "516 a.C.–70 d.C.", title: "Pluralidade judaica, textos e expectativas messiânicas", thesis: "O judaísmo do Segundo Templo foi um campo plural de práticas, instituições, textos e debates; é nesse ambiente que se formam várias linguagens usadas pelo Novo Testamento.", questions: ["Havia um judaísmo normativo único ou múltiplos judaísmos?", "O que Qumran permite dizer sobre sacerdócio, calendário e escatologia?", "Como apócrifos e pseudepígrafos se relacionam ao cânon e à recepção?"], debates: ["Identidade de Qumran: essênios, sacerdotes dissidentes ou grupo singular", "Extensão da helenização na Palestina", "Fronteiras entre fariseus, saduceus, essênios e cristãos"], sources: ["Manuscritos do Mar Morto: 1QS, 1QM e 4QMMT", "Josefo, 1 Enoque, Jubileus e Eclesiástico", "Sanders, Hengel e VanderKam"], entities: ["Qumran", "Massada", "Jerusalém", "Alexandria", "Hilel", "Shamai", "Flávio Josefo"], confidence: "Alta para manuscritos e achados; variável para filiação sectária e reconstruções de grupos marginais." },
  {
    id: "roman-jesus", period: "Roma, Jesus e os Evangelhos", date: "63 a.C.–70 d.C.", title: "Império, templo e o movimento de Jesus", thesis: "O Jesus histórico precisa ser situado no cruzamento entre dominação romana, economia galileia, instituições do templo, movimentos judaicos e expectativas escatológicas.", questions: ["Como tributação, urbanização e violência romana moldaram a Galileia?", "Como distinguir memória histórica, teologia narrativa e redação evangelística?", "Qual relação existe entre os Sinóticos e a prioridade de Marcos?"], debates: ["Jesus político, profético, sapiencial e apocalíptico", "Critérios de autenticidade e limites do método histórico", "Prioridade de Marcos, hipótese das Duas Fontes e alternativas"], sources: ["Evangelhos, Josefo, Fílon, Tácito e Suetônio", "Cafarnaum, Séforis, Cesareia Marítima e Jerusalém", "Sanders, Meier, Bauckham e Wright"], entities: ["Jesus", "João Batista", "Herodes Antipas", "Pilatos", "Caifás", "Cafarnaum", "Séforis", "Templo"], confidence: "Alta para ambiente imperial, numismática e instituições; média para reconstruções do Jesus histórico; variável para leituras confessionais." },
  {
    id: "paul-church", period: "Igreja primitiva e Paulo", date: "30–100 d.C.", title: "Cartas, cidades e redes do cristianismo nascente", thesis: "As comunidades paulinas devem ser analisadas como redes urbanas concretas, atravessadas por estatuto social, patronagem, império, conflitos judaico-gentílicos e experiências carismáticas.", questions: ["Como as cartas autênticas se relacionam com Atos e as deuteropaulinas?", "Qual foi o peso da patronagem e da desigualdade nas ekklesiai?", "Como Torá, identidade e missão são negociadas em Gálatas e Romanos?"], debates: ["Nova Perspectiva sobre Paulo e justificação", "Autoria de Colossenses, Efésios e Pastorais", "Paulo contra o império versus acomodação política", "Liderança feminina e sociologia das comunidades"], sources: ["Romanos, 1–2 Coríntios, Gálatas, Filipenses, 1 Tessalonicenses e Filemom", "Inscrição de Gálio, papiros e Padres Apostólicos", "Sanders, Theissen, Meeks e Wright"], entities: ["Paulo", "Pedro", "Tiago", "Priscila", "Áquila", "Febe", "Júnia", "Antioquia", "Corinto", "Éfeso", "Roma"], confidence: "Alta para cartas centrais e vários eixos geográficos; média para cronologia relativa e sociologia; variável para motivações não atestadas." }
];

export const biblicalPlaces: BiblicalPlace[] = [
  { id: "jerusalem", name: "Jerusalém", ancientName: "Yerushalayim", lat: 31.7683, lng: 35.2137, periods: "Bronze–romano", dossier: "monarchy-temple", summary: "Centro político, cultual e simbólico cuja centralidade é disputada e reforçada por textos, reformas e impérios.", refs: "2Sm 5; 1Rs 8; 2Rs 25; Mc 11; At 2" },
  { id: "eden", name: "Éden", ancientName: "Eden · marcador didático", lat: 33.5, lng: 44.4, periods: "Origens–Bronze", dossier: "origins-levant", summary: "Espaço narrativo de Gênesis 2–3; a coordenada representa uma aproximação didática, não uma localização arqueológica comprovada.", refs: "Gn 2–3; Ez 28; Ap 2; Ap 22" },
  { id: "ur", name: "Ur", ancientName: "Ur dos caldeus · Tell el-Muqayyar", lat: 30.96, lng: 46.1, periods: "Bronze–Patriarcas", dossier: "origins-levant", summary: "Cidade do sul da Mesopotâmia associada à origem da família de Abraão; a relação entre cidade arqueológica e memória patriarcal é debatida.", refs: "Gn 11:27–32; Gn 15:7; Ne 9:7; At 7:2–4" },
  { id: "haran", name: "Harã", ancientName: "Harran", lat: 36.87, lng: 39.03, periods: "Bronze–Patriarcas", dossier: "origins-levant", summary: "Entreposto do norte da Mesopotâmia que liga a partida de Terá e Abraão ao retorno de Jacó.", refs: "Gn 11:31–32; Gn 12:1–5; Gn 27:43–31:55; At 7:4" },
  { id: "canaan", name: "Canaã", ancientName: "Terra de Canaã · Levante", lat: 31.8, lng: 35.2, periods: "Bronze–Ferro", dossier: "origins-levant", summary: "Região de cidades, rotas e populações diversas que se torna território de promessa, disputa e formação de Israel.", refs: "Gn 12:5–7; Gn 23; Êx 3:8; Js 1; Hb 11:9" },
  { id: "hebron", name: "Hebrom", ancientName: "Ḥevron · Manre", lat: 31.53, lng: 35.1, periods: "Bronze–Monarquia", dossier: "monarchy-temple", summary: "Centro patriarcal e lugar associado à sepultura de Sara, Abraão, Isaque, Rebeca, Jacó e Lia.", refs: "Gn 13:18; Gn 18; Gn 23; Gn 35:27–29; 2Sm 5:1–5" },
  { id: "egypt", name: "Egito", ancientName: "Kemet · Egito faraônico", lat: 29.98, lng: 31.13, periods: "Bronze–Êxodo", dossier: "exodus-iron", summary: "Potência e lugar de migração, preservação, trabalho forçado e libertação nas narrativas de Gênesis e Êxodo.", refs: "Gn 12; Gn 37–50; Êx 1–15; Os 11:1; Mt 2:13–15" },
  { id: "samaria", name: "Samaria", ancientName: "Šomron", lat: 32.2768, lng: 35.1976, periods: "Ferro II–romano", dossier: "monarchy-temple", summary: "Capital do reino do Norte e ponto decisivo para estudar fronteiras, memória e relações judaico-samaritanas.", refs: "1Rs 16; 2Rs 17; Jo 4" },
  { id: "hazor", name: "Hazor", ancientName: "Ḥaṣor", lat: 33.0171, lng: 35.5695, periods: "Bronze–Ferro", dossier: "origins-levant", summary: "Grande centro do Levante setentrional, essencial para discutir cidades-estado, destruição e modelos de conquista.", refs: "Js 11:10–13" },
  { id: "megiddo", name: "Megido", ancientName: "Məgiddo", lat: 32.5851, lng: 35.1829, periods: "Bronze–Ferro", dossier: "origins-levant", summary: "Nó de rotas e conflitos; suas camadas arqueológicas são centrais para debates de cronologia e urbanismo.", refs: "Jz 5; 2Rs 23:29" },
  { id: "jericho", name: "Jericó", ancientName: "Yərīḥō", lat: 31.8704, lng: 35.4444, periods: "Neolítico–Ferro", dossier: "exodus-iron", summary: "Sítio de longa ocupação usado para discutir memória de conquista, estratigrafia e limites de correlação narrativa.", refs: "Js 2–6" },
  { id: "babylon", name: "Babilônia", ancientName: "Bāb-ilim", lat: 32.542, lng: 44.421, periods: "Babilônico–persa", dossier: "exile-restoration", summary: "Capital imperial e lugar de deportação, produção documental e reconfiguração de identidades judaítas.", refs: "2Rs 24–25; Dn 1; Sl 137" },
  { id: "susa", name: "Susa", ancientName: "Šušān", lat: 32.1892, lng: 48.2579, periods: "Persa", dossier: "exile-restoration", summary: "Centro administrativo aquemênida associado à corte persa e ao imaginário de Ester e Daniel.", refs: "Et 1; Dn 8" },
  { id: "qumran", name: "Qumran", ancientName: "Khirbet Qumran", lat: 31.7417, lng: 35.4594, periods: "Segundo Templo", dossier: "second-temple", summary: "Sítio associado aos Manuscritos do Mar Morto; decisivo para estudar textos, calendários e identidades sectárias.", refs: "1QS; 4QMMT; Mt 3" },
  { id: "capernaum", name: "Cafarnaum", ancientName: "Kəfar Naḥūm", lat: 32.8803, lng: 35.5733, periods: "Romano", dossier: "roman-jesus", summary: "Aldeia galileia que permite estudar economia pesqueira, sinagoga, redes locais e memória do ministério de Jesus.", refs: "Mc 1:21–34; Mt 4:13" },
  { id: "antioch", name: "Antioquia", ancientName: "Antiocheia", lat: 36.2021, lng: 36.1606, periods: "Helenístico–romano", dossier: "paul-church", summary: "Metrópole síria e nó missionário para discutir identidades judaicas e gentílicas em ambiente imperial.", refs: "At 11:19–26; Gl 2" },
  { id: "corinth", name: "Corinto", ancientName: "Kórinthos", lat: 37.9059, lng: 22.8835, periods: "Romano", dossier: "paul-church", summary: "Colônia romana e comunidade epistolar onde status, patronagem, culto e conflito moldam a leitura de Paulo.", refs: "At 18; 1Co 1–16" },
  { id: "ephesus", name: "Éfeso", ancientName: "Éphesos", lat: 37.9412, lng: 27.3419, periods: "Helenístico–romano", dossier: "paul-church", summary: "Centro comercial e cultual da Ásia Menor, conectado a Paulo, Atos e à carta do Apocalipse.", refs: "At 19; 1Co 15:32; Ap 2:1–7" },
  { id: "rome", name: "Roma", ancientName: "Rōmē", lat: 41.9028, lng: 12.4964, periods: "Romano", dossier: "paul-church", summary: "Capital imperial e destino epistolar de Paulo, onde a linguagem de evangelho e senhorio ganha peso político.", refs: "Rm 1:7; 13:1–7; At 28" }
];
