// Cartografia de Leituras: módulo 11 sobre Apocalipse, escatologia e discernimento hermenêutico.
export type ApocalypseUnit = { id: string; range: string; title: string; subtitle: string; summary: string; scriptures: string; interpretiveNote: string };
export type RevelationChurch = { name: string; city: string; image: string; text: string; location: string; caution: string };
export type InterpretationSchool = { name: string; short: string; core: string; strength: string; tension: string };
export type MillennialView = { name: string; core: string; keyText: string };

export const apocalypseUnits: ApocalypseUnit[] = [
  { id: "porta", range: "Ap 1", title: "A porta da visão", subtitle: "Revelação, profecia e testemunho", summary: "O livro começa como revelação de Jesus Cristo, carta às comunidades e profecia. João se apresenta em Patmos e vê o Cristo glorificado entre os candeeiros.", scriptures: "Ap 1:1–20; Dn 7:9–14; Ez 1", interpretiveNote: "Antes de perguntar quando algo acontecerá, pergunte como o texto formava coragem, fidelidade e discernimento em seus primeiros ouvintes." },
  { id: "igrejas", range: "Ap 2–3", title: "As sete igrejas", subtitle: "Comunidades reais e símbolo de totalidade", summary: "Éfeso, Esmirna, Pérgamo, Tiatira, Sardes, Filadélfia e Laodiceia recebem diagnósticos, advertências e promessas do Cristo que conhece sua vida comunitária.", scriptures: "Ap 2–3; Ap 1:20", interpretiveNote: "As cidades eram reais, mas o número sete também funciona simbolicamente. Não há base suficiente para transformar cada carta em uma sequência fixa de eras da história da Igreja." },
  { id: "trono", range: "Ap 4–5", title: "Trono e Cordeiro", subtitle: "Quem governa a história?", summary: "A visão celestial desloca o centro do poder: o trono de Deus e o Cordeiro imolado interpretam a história a partir da adoração, da criação e da redenção.", scriptures: "Ap 4–5; Is 6; Ez 1; Dn 7", interpretiveNote: "O Cordeiro vence sem reproduzir a violência dos impérios. A imagem é cristológica e litúrgica antes de ser um cronograma militar." },
  { id: "selos", range: "Ap 6–11", title: "Selos e trombetas", subtitle: "Juízo, testemunho e alerta", summary: "Cavaleiros, mártires, selamento, trombetas e testemunhas compõem ciclos de juízo parcial e chamado à perseverança, com ecos de Êxodo, Daniel, Joel e Ezequiel.", scriptures: "Ap 6–11; Êx 7–12; Jl 2; Ez 9; Zc 4", interpretiveNote: "O paralelismo dos ciclos e a linguagem simbólica tornam arriscado montar um calendário linear. A cena também funciona como resistência e consolo para comunidades sob pressão." },
  { id: "bestas", range: "Ap 12–14", title: "Dragão e bestas", subtitle: "Poder, propaganda e lealdade", summary: "A mulher, o dragão e as bestas dramatizam o conflito entre o Cordeiro e poderes que exigem adoração, controlam a economia e imitam sinais de autoridade.", scriptures: "Ap 12–14; Dn 7; Gn 3; Êx 19", interpretiveNote: "A marca da besta não deve ser identificada automaticamente com cada tecnologia ou governo contemporâneo. O texto comunica pertencimento, lealdade e participação em um sistema de culto ao poder." },
  { id: "babilonia", range: "Ap 15–18", title: "Babilônia cai", subtitle: "Império, luxo e economia da exploração", summary: "Taças, a mulher montada na besta e a queda de Babilônia expõem uma cidade-sistema que enriquece por comércio, violência e sedução política.", scriptures: "Ap 15–18; Jr 50–51; Is 13–14; Ez 27", interpretiveNote: "Para muitos estudos históricos, Babilônia é uma cifra para Roma. A imagem também permite discernir estruturas de idolatria, exploração e injustiça em diferentes épocas sem apagar o contexto original." },
  { id: "milênio", range: "Ap 19–20", title: "Rei, juízo e milênio", subtitle: "A derrota do mal e a questão dos mil anos", summary: "O cavaleiro fiel, a derrota das bestas, o aprisionamento de Satanás, o reinado dos santos e o juízo diante do grande trono branco geram leituras escatológicas distintas.", scriptures: "Ap 19–20; Mt 25; 1Co 15; 1Ts 4", interpretiveNote: "Pré-milenismo, amilenismo e pós-milenismo interpretam a relação entre a volta de Cristo e o milênio de modos diferentes. A declaração da Church of God assume uma formulação pré-milenista." },
  { id: "nova-criacao", range: "Ap 21–22", title: "Nova criação", subtitle: "Deus habita com a humanidade", summary: "Novo céu, nova terra, Nova Jerusalém, rio da vida e árvore da vida concluem a Bíblia com presença, cura das nações e fim da morte, do luto e da dor.", scriptures: "Ap 21–22; Gn 2–3; Is 65–66; Ez 47", interpretiveNote: "As medidas e imagens da cidade funcionam como linguagem de plenitude, segurança e comunhão. O final não é fuga da criação, mas sua renovação sob a presença de Deus." },
];

export const revelationChurches: RevelationChurch[] = [
  { name: "Éfeso", city: "Éfeso", image: "Amor que precisa ser reaceso", text: "Perseverança, discernimento e resistência a falsos mestres convivem com a denúncia de abandono do primeiro amor.", location: "Metrópole comercial e religiosa da Ásia, associada ao templo de Ártemis.", caution: "Não é seguro reduzir a carta a uma biografia completa da igreja; o texto constrói um diagnóstico profético." },
  { name: "Esmirna", city: "Esmirna", image: "Fidelidade sob pressão", text: "Uma comunidade pobre aos olhos do império é chamada rica diante de Deus e encorajada a permanecer fiel em meio à tribulação.", location: "Cidade portuária com forte lealdade pública a Roma.", caution: "A linguagem de perseguição deve ser estudada com cuidado; o texto não oferece uma estatística ou cronologia da repressão." },
  { name: "Pérgamo", city: "Pérgamo", image: "Testemunho em ambiente imperial", text: "A igreja vive onde está o trono de Satanás, mantém o nome de Cristo, mas é advertida por tolerar ensinos associados a Balaão e aos nicolaítas.", location: "Centro político e religioso com importantes monumentos de culto imperial.", caution: "A identificação exata dos grupos e de Antipas permanece discutida." },
  { name: "Tiatira", city: "Tiatira", image: "Discernir profecia e compromisso", text: "O texto elogia serviço e perseverança, mas critica a tolerância a Jezabel e práticas associadas à idolatria e imoralidade.", location: "Cidade interior conhecida por associações profissionais e produção artesanal.", caution: "O nome Jezabel pode ser uma alusão teológica, não necessariamente a uma pessoa com esse nome." },
  { name: "Sardes", city: "Sardes", image: "Fama sem vida", text: "A comunidade tem reputação de estar viva, mas recebe um chamado urgente à vigilância, fortalecimento e arrependimento.", location: "Cidade com memória de grandeza passada e experiência de declínio e terremotos.", caution: "A correspondência entre a história da cidade e cada imagem da carta não pode ser afirmada sem reservas." },
  { name: "Filadélfia", city: "Filadélfia", image: "Pouca força, fidelidade real", text: "A igreja tem pouca força, guarda a palavra e recebe a imagem da porta aberta e da coluna no templo de Deus.", location: "Cidade de fronteira e região sujeita a terremotos, com reconstruções frequentes.", caution: "Porta aberta não deve ser convertida automaticamente em promessa de sucesso institucional contemporâneo." },
  { name: "Laodiceia", city: "Laodiceia", image: "Autossuficiência desmascarada", text: "A mornidão é confrontada por uma comunidade que diz ser rica, mas é descrita como pobre, cega e nua; o convite final é comunhão e arrependimento.", location: "Centro financeiro e médico conhecido por riqueza, lã e colírio, embora as associações exatas sejam debatidas.", caution: "A imagem de água morna é poderosa, mas não deve ser usada para humilhar pessoas ou produzir medo sem restauração." },
];

export const interpretationSchools: InterpretationSchool[] = [
  { name: "Preterista", short: "O horizonte principal está no primeiro século", core: "Lê grande parte das visões à luz de Roma, das crises judaicas e das comunidades do século I.", strength: "Recupera destinatários, império, cidades e conflitos originais.", tension: "Pode reduzir demais o horizonte futuro e a expectativa cósmica do livro quando usado de forma exclusiva." },
  { name: "Historicista", short: "O livro percorre a história da Igreja", core: "Interpreta símbolos como etapas sucessivas da história cristã até a consumação.", strength: "Percebe a recepção histórica e a força do livro para comunidades posteriores.", tension: "Tem dificuldade de produzir critérios estáveis para associar cada símbolo a eventos específicos." },
  { name: "Futurista", short: "Grande parte se refere ao fim ainda futuro", core: "Lê especialmente Apocalipse 4–22 como acontecimentos escatológicos futuros, muitas vezes em sequência.", strength: "Preserva a dimensão futura, a segunda vinda e a consumação do mal.", tension: "Pode descolar o texto das igrejas originais e incentivar especulações sobre eventos atuais." },
  { name: "Idealista", short: "O livro dramatiza o conflito de todas as eras", core: "Lê imagens como símbolos recorrentes da luta entre o Cordeiro, impérios, idolatria, testemunho e esperança.", strength: "Mantém a força pastoral e ética do livro para diferentes gerações.", tension: "Pode perder detalhes históricos e a expectativa de intervenção futura quando aplicado isoladamente." },
  { name: "Eclética", short: "Combina contexto, padrão e consumação", core: "Reconhece um referente primeiro, padrões recorrentes e uma consumação futura sem obrigar todo símbolo a um único nível.", strength: "Permite leitura histórica, pastoral, teológica e escatológica em conjunto.", tension: "Exige mais disciplina para não virar uma mistura seletiva sem critérios claros." },
];

export const millennialViews: MillennialView[] = [
  { name: "Pré-milenismo", core: "Cristo retorna antes de um reinado milenar entendido como futuro; há variações sobre tribulação e arrebatamento.", keyText: "Ap 19–20; 1Ts 4:13–18" },
  { name: "Amilenismo", core: "O milênio é lido simbolicamente como o reinado presente de Cristo, com consumação na volta final e juízo.", keyText: "Ap 20; Mt 12:28–29; Ef 2:6" },
  { name: "Pós-milenismo", core: "A expansão do reino e da justiça precede a consumação; o retorno de Cristo acontece depois desse período interpretado de modo variável.", keyText: "Ap 20; Mt 13:31–33" },
];

export type ApocalypseChapter = { chapter: number; title: string; summary: string; refs: string };
export const apocalypseChapters: ApocalypseChapter[] = [
  { chapter: 1, title: "Prólogo e Cristo entre os candeeiros", summary: "Revelação, bênção, João em Patmos e a visão do Filho do Homem glorificado.", refs: "Ap 1:1–20" },
  { chapter: 2, title: "Éfeso, Esmirna, Pérgamo e Tiatira", summary: "Quatro cartas que combinam elogio, advertência, sofrimento, doutrina e promessa.", refs: "Ap 2:1–29" },
  { chapter: 3, title: "Sardes, Filadélfia e Laodiceia", summary: "Vigilância, pouca força, porta aberta, mornidão e o convite para abrir a porta.", refs: "Ap 3:1–22" },
  { chapter: 4, title: "O trono e a adoração", summary: "A cena celestial desloca o centro de soberania dos impérios para o Criador.", refs: "Ap 4:1–11" },
  { chapter: 5, title: "O livro e o Cordeiro", summary: "O Leão-Cordeiro é digno de abrir o livro e inaugura a redenção cantada pelo céu.", refs: "Ap 5:1–14" },
  { chapter: 6, title: "Os seis primeiros selos", summary: "Cavaleiros, mártires e abalos cósmicos formam um ciclo de juízo e clamor por justiça.", refs: "Ap 6:1–17" },
  { chapter: 7, title: "O selo e a grande multidão", summary: "O texto apresenta preservação, pertencimento e uma multidão de todas as nações diante do Cordeiro.", refs: "Ap 7:1–17" },
  { chapter: 8, title: "Sétimo selo e primeiras trombetas", summary: "Silêncio, oração e juízos parciais sobre terra, mar e águas ecoam as pragas do Êxodo.", refs: "Ap 8:1–13" },
  { chapter: 9, title: "A quinta e a sexta trombeta", summary: "Imagens de abismo, guerra e sofrimento insistem na necessidade de discernimento e arrependimento.", refs: "Ap 9:1–21" },
  { chapter: 10, title: "O anjo e o pequeno rolo", summary: "João recebe um rolo doce e amargo, imagem da vocação profética que envolve consolo e dor.", refs: "Ap 10:1–11" },
  { chapter: 11, title: "Templo, duas testemunhas e sétima trombeta", summary: "Medição, testemunho, martírio, ressurreição e anúncio do reino formam o centro profético do ciclo.", refs: "Ap 11:1–19" },
  { chapter: 12, title: "A mulher e o dragão", summary: "Uma narrativa cósmica interpreta perseguição e conflito como parte de uma batalha entre acusação e testemunho.", refs: "Ap 12:1–18" },
  { chapter: 13, title: "As duas bestas e a marca", summary: "Poder político e propaganda religiosa se combinam para exigir lealdade e controlar a participação econômica.", refs: "Ap 13:1–18" },
  { chapter: 14, title: "Cordeiro, colheita e advertência", summary: "O Cordeiro, os anúncios angelicais e as imagens de colheita contrastam pertencimentos e destinos.", refs: "Ap 14:1–20" },
  { chapter: 15, title: "O cântico e as sete taças", summary: "A cena prepara o último ciclo de juízos com memória do Êxodo e do testemunho dos santos.", refs: "Ap 15:1–8" },
  { chapter: 16, title: "As sete taças", summary: "O juízo se intensifica, mas o texto mantém a tensão entre sinais, endurecimento e expectativa.", refs: "Ap 16:1–21" },
  { chapter: 17, title: "A mulher e a besta", summary: "Babilônia é vista como poder sedutor, luxuoso e violento que se articula com governos.", refs: "Ap 17:1–18" },
  { chapter: 18, title: "A queda de Babilônia", summary: "Reis, mercadores e navegadores lamentam a queda de uma economia baseada em luxo, comércio e vidas humanas.", refs: "Ap 18:1–24" },
  { chapter: 19, title: "Bodas e cavaleiro fiel", summary: "Cânticos, bodas do Cordeiro e a derrota das bestas apresentam a vitória de Cristo sobre o poder violento.", refs: "Ap 19:1–21" },
  { chapter: 20, title: "Milênio e grande trono branco", summary: "O milênio, a soltura final de Satanás e o juízo dos mortos sustentam as principais divergências escatológicas.", refs: "Ap 20:1–15" },
  { chapter: 21, title: "Novo céu, nova terra e Nova Jerusalém", summary: "A cidade-noiva desce, Deus habita com a humanidade e a criação é descrita sem morte, luto ou dor.", refs: "Ap 21:1–27" },
  { chapter: 22, title: "Rio da vida e epílogo", summary: "Árvore da vida, cura das nações, convite do Espírito e promessa da vinda encerram a Bíblia.", refs: "Ap 22:1–21" },
];

export const apocalypseSources = [
  { label: "Bible Odyssey — Revelation to John", url: "https://www.bibleodyssey.org/dictionary/revelation-to-john-the/" },
  { label: "Bible Odyssey — What Is an Apocalypse?", url: "https://www.bibleodyssey.org/articles/what-is-an-apocalypse/" },
  { label: "Bible Odyssey — The Seven Cities of Revelation", url: "https://www.bibleodyssey.org/articles/the-seven-cities-of-revelation/" },
  { label: "Church of God — Declaration of Faith", url: "https://churchofgod.org/beliefs/declaration-of-faith/" },
  { label: "Yale Bible Study — Revelation", url: "https://yalebiblestudy.org/courses/revelation/" },
  { label: "Assemblies of God — Premillennial Eschatology", url: "https://ag.org/Beliefs/Position-Papers/Premillennial-Eschatology" },
];
