export type CanonLens = "católica" | "ortodoxa" | "protestante" | "segundo-templo";

export type ApocryphaEntry = {
  id: string;
  title: string;
  collection: "Deuterocanônico" | "Acréscimo grego" | "Anagignoskomena" | "Segundo Templo";
  period: string;
  genre: string;
  summary: string;
  historicalQuestion: string;
  reception: string;
  references: string;
  lenses: CanonLens[];
};

export const canonLenses: { id: CanonLens; label: string; note: string }[] = [
  { id: "católica", label: "Católica", note: "Deuterocanônicos recebidos no cânon católico." },
  { id: "ortodoxa", label: "Ortodoxa", note: "Coleções variam entre igrejas; a tradição grega é decisiva." },
  { id: "protestante", label: "Protestante", note: "Recebidos como leitura histórica útil, mas não como cânon normativo." },
  { id: "segundo-templo", label: "Segundo Templo", note: "Literatura judaica antiga em diálogo intenso com as Escrituras de Israel." },
];

export const apocryphaEntries: ApocryphaEntry[] = [
  { id: "tobit", title: "Tobias", collection: "Deuterocanônico", period: "c. 225–175 a.C.", genre: "Narrativa sapiencial de diáspora", summary: "Uma família israelita vive fidelidade, pobreza, viagem, casamento, cura e hospitalidade em cenário assírio imaginado pela obra.", historicalQuestion: "Como a narrativa usa um passado assírio para ensinar identidade judaica em contextos posteriores de diáspora?", reception: "Canônico nas tradições católica e ortodoxa; incluído entre os apócrifos em edições protestantes históricas.", references: "Tob 1–14 · esmola · oração · família", lenses: ["católica", "ortodoxa", "protestante", "segundo-templo"] },
  { id: "judith", title: "Judite", collection: "Deuterocanônico", period: "final do séc. II–início do I a.C.", genre: "Novela teológica", summary: "Uma heroína viúva confronta a invasão de Holofernes; o livro combina memória bíblica, oração, política e inversão narrativa.", historicalQuestion: "As imprecisões geográficas e cronológicas sugerem que a obra funciona como narrativa teológica, não como crônica linear.", reception: "Canônico em coleções católicas e ortodoxas; lido como apócrifo em tradições protestantes.", references: "Jdt 1–16 · Betúlia · jejum · libertação", lenses: ["católica", "ortodoxa", "protestante", "segundo-templo"] },
  { id: "wisdom", title: "Sabedoria de Salomão", collection: "Deuterocanônico", period: "c. 50 a.C.–50 d.C.", genre: "Sabedoria helenística", summary: "Atribuída literariamente a Salomão, a obra reflete sobre justiça, imortalidade, idolatria e a história do êxodo em grego sofisticado.", historicalQuestion: "Como a linguagem filosófica helenística reorganiza temas de criação, justiça e esperança israelitas?", reception: "Canônica para católicos e ortodoxos; relevante para estudar vocabulário que dialoga com autores do Novo Testamento.", references: "Sb 1–19 · sabedoria · justiça · êxodo", lenses: ["católica", "ortodoxa", "protestante", "segundo-templo"] },
  { id: "sirach", title: "Eclesiástico / Ben Sira", collection: "Deuterocanônico", period: "c. 200–175 a.C.", genre: "Sabedoria e instrução", summary: "Coleção de máximas, poemas e louvor aos antepassados, originalmente escrita em hebraico e difundida amplamente em grego.", historicalQuestion: "O que os fragmentos hebraicos e gregos revelam sobre transmissão, tradução e autoridade antes de listas canônicas fechadas?", reception: "Canônico em tradições católicas e ortodoxas; circulou amplamente também em ambientes judaicos antigos.", references: "Eclo 1–51 · Torá · templo · antepassados", lenses: ["católica", "ortodoxa", "protestante", "segundo-templo"] },
  { id: "baruch", title: "Baruc e Carta de Jeremias", collection: "Deuterocanônico", period: "sécs. II–I a.C.", genre: "Confissão, sabedoria e carta", summary: "Textos associados ao escriba de Jeremias articulam exílio, arrependimento, sabedoria e crítica à idolatria sob uma autoria literária antiga.", historicalQuestion: "Como a pseudepigrafia funciona como recepção criativa de Jeremias e da memória do exílio?", reception: "Incluído no cânon católico; parte de coleções ortodoxas, com arranjos e extensões que variam.", references: "Br 1–6 · exílio · sabedoria · idolatria", lenses: ["católica", "ortodoxa", "protestante", "segundo-templo"] },
  { id: "maccabees-1", title: "1 Macabeus", collection: "Deuterocanônico", period: "c. 100 a.C.", genre: "História dinástica", summary: "Narra a crise sob Antíoco IV, a revolta de Matatias e Judas e a ascensão hasmoneia em estilo próximo à historiografia política.", historicalQuestion: "Como comparar a apresentação hasmoneia da obra com arqueologia, moedas e o relato de Josefo?", reception: "Canônico em católicos e ortodoxos; indispensável para o cenário de Daniel, festas e movimentos do Segundo Templo.", references: "1Mc 1–16 · Antíoco IV · templo · Hasmoneus", lenses: ["católica", "ortodoxa", "protestante", "segundo-templo"] },
  { id: "maccabees-2", title: "2 Macabeus", collection: "Deuterocanônico", period: "c. 124 a.C.", genre: "Epítome historiográfico e martírio", summary: "Reconta parte da crise macabeia por outra lente, com foco no templo, martírio, ressurreição e intervenção divina.", historicalQuestion: "Por que 1 e 2 Macabeus não devem ser harmonizados como se fossem a mesma crônica?", reception: "Canônico para católicos e ortodoxos; texto relevante para estudos de martírio, oração pelos mortos e esperança de ressurreição.", references: "2Mc 3–15 · martírio · ressurreição · templo", lenses: ["católica", "ortodoxa", "protestante", "segundo-templo"] },
  { id: "greek-additions", title: "Acréscimos gregos a Ester e Daniel", collection: "Acréscimo grego", period: "sécs. II–I a.C.", genre: "Orações e narrativas ampliadas", summary: "Versões gregas preservam orações de Ester e Mardoqueu, Susana, Bel e o Dragão e a Oração de Azarias, que ampliam personagens e teologia narrativa.", historicalQuestion: "Como versões antigas podem conservar, adaptar ou expandir formas textuais diferentes das preservadas em hebraico?", reception: "Partes integrais de Bíblias católicas e ortodoxas; geralmente separadas como apócrifos em edições protestantes.", references: "Est grego · Dn 3; 13–14 · Septuaginta", lenses: ["católica", "ortodoxa", "protestante", "segundo-templo"] },
  { id: "anagignoskomena", title: "Salmo 151, Oração de Manassés e 3 Macabeus", collection: "Anagignoskomena", period: "sécs. III–I a.C.", genre: "Salmo, oração e narrativa histórica", summary: "Textos presentes em diversas coleções gregas e ortodoxas, mas não de modo idêntico em todas as igrejas ou manuscritos.", historicalQuestion: "O que a diversidade de coleções mostra sobre a diferença entre circulação, uso litúrgico e delimitação canônica?", reception: "Reconhecidos em várias tradições ortodoxas como textos de leitura; a extensão exata depende da igreja e da edição.", references: "Sl 151 · OrMan · 3Mc · tradição grega", lenses: ["ortodoxa", "protestante", "segundo-templo"] },
  { id: "enoch-jubilees", title: "1 Enoque e Jubileus", collection: "Segundo Templo", period: "sécs. III–I a.C.", genre: "Apocalíptica e reescrita bíblica", summary: "Obras judaicas influentes que reimaginam Gênesis, anjos, calendário, justiça e juízo; não pertencem ao deuterocânon católico romano.", historicalQuestion: "Como manuscritos de Qumran, citações antigas e recepção etíope ajudam a distinguir influência, uso e canonicidade?", reception: "Fora do cânon católico e protestante; 1 Enoque é canônico na tradição ortodoxa etíope e ambos são centrais para estudar o Segundo Templo.", references: "1En 1–108 · Jub 1–50 · Qumran · Jd 14–15", lenses: ["ortodoxa", "protestante", "segundo-templo"] },
];

export const apocryphaSources = [
  { label: "SBL Press · The Growth of the Septuagint and Its Canon", url: "https://scholarlypublishingcollective.org/sblpress/jbl/article/143/2/303/389157/Suddenly-and-Then-Gradually-The-Growth-of-the", kind: "debate acadêmico" },
  { label: "BibleProject · Deuterocanon / Apocrypha", url: "https://bibleproject.com/articles/why-deuterocanon-apocrypha-some-bibles-and-not-others/", kind: "introdução comparativa" },
  { label: "Vaticano · Dei Verbum", url: "https://www.vatican.va/archive/hist_councils/ii_vatican_council/documents/vat-ii_const_19651118_dei-verbum_en.html", kind: "posição católica" },
];
