import type { JourneyView } from "@/components/JourneyNavigator";

export type HistoryPeriod = {
  id: string;
  order: string;
  date: string;
  label: string;
  empire: string;
  narrative: string;
  textLayer: string;
  evidence: string;
  debate: string;
  source: string;
  sourceUrl: string;
  destination: JourneyView;
  destinationLabel: string;
};

export const historyPeriods: HistoryPeriod[] = [
  { id: "worlds", order: "01", date: "c. 3300–1200 a.C.", label: "Cidades, rios e rotas do antigo Oriente", empire: "Egito, Mesopotâmia e cidades do Levante", narrative: "Gênesis situa as origens e os ancestrais em um mundo de rios, cidades, fome, migração e alianças familiares. A história das narrativas não é idêntica à história demonstrável de cada personagem.", textLayer: "Gn 1–50 · origens, dilúvio, Babel e ancestrais", evidence: "Textos de Mari, Ebla, Ugarit e Amarna; arqueologia de cidades do Levante.", debate: "Memória patriarcal, composição literária e correlação com o Bronze são questões distintas e disputadas.", source: "Pleiades · gazetteer histórico", sourceUrl: "https://pleiades.stoa.org/places", destination: "atlas", destinationLabel: "Ver atlas do Levante" },
  { id: "exodus", order: "02", date: "c. 1300–1000 a.C.", label: "Libertação, deserto e etnogênese", empire: "Egito faraônico e Canaã do Bronze/Ferro", narrative: "Êxodo e Josué narram libertação, aliança e terra; na tradição de Israel, essa memória organiza identidade, culto e ética muito além de uma cronologia simples.", textLayer: "Êx 1–Dt 34 · Js 1–24", evidence: "Estela de Merneptah, topônimos egípcios, sítios e padrões de assentamento do Ferro I.", debate: "Não há consenso sobre data, escala, rota ou modelo de emergência de Israel; conquista, transformação interna e migrações são modelos discutidos.", source: "SBL · arqueologia e história", sourceUrl: "https://www.sbl-site.org/educational/Resources.aspx", destination: "atlas", destinationLabel: "Cruzar rotas e lugares" },
  { id: "judges", order: "03", date: "c. 1200–1000 a.C.", label: "Aldeias, juízes e memórias tribais", empire: "Pós-colapso do Bronze", narrative: "Juízes e Rute descrevem lideranças locais, conflito, famílias e a pergunta sobre como um povo sem monarquia imagina ordem e fidelidade.", textLayer: "Jz · Rt · tradições de 1Sm 1–8", evidence: "Levantamentos de assentamentos, cerâmica e transformação do padrão rural no planalto central.", debate: "Os ciclos narrativos de Juízes não formam necessariamente uma sequência cronológica contínua.", source: "Pleiades · lugares e paisagens", sourceUrl: "https://pleiades.stoa.org/places", destination: "library", destinationLabel: "Abrir livros históricos" },
  { id: "monarchy", order: "04", date: "c. 1000–930 a.C.", label: "Jerusalém, dinastia e templo", empire: "Reinos levantinos", narrative: "Samuel e Reis apresentam Davi e Salomão como eixo de dinastia, Jerusalém e culto. Crônicas relê a mesma memória em outra situação histórica.", textLayer: "1–2Sm · 1Rs 1–11 · 1–2Cr 1–9", evidence: "Estela de Tel Dan, urbanismo, inscrições e debates de cronologia arqueológica.", debate: "A escala da Monarquia Unida, a datação de estratos e a relação entre propaganda real e memória bíblica seguem em discussão.", source: "The Bible Unearthed · debate arqueológico", sourceUrl: "https://books.google.com/books?id=lu6ywyJr0CMC", destination: "library", destinationLabel: "Explorar Samuel e Reis" },
  { id: "divided", order: "05", date: "c. 930–722 a.C.", label: "Dois reinos sob a pressão assíria", empire: "Neoassíria", narrative: "Israel e Judá vivem dinâmicas políticas próprias. Profetas denunciam idolatria, exploração e alianças, enquanto a Assíria redesenha o Levante por tributo e deportação.", textLayer: "1Rs 12–2Rs 17 · Am · Os · Is 1–39 · Mq", evidence: "Anais assírios, ostraca de Samaria, inscrições reais e sítios do Ferro II.", debate: "Profecia é discurso situado, não simples previsão; a relação entre oráculos e seus contextos editoriais precisa ser examinada livro a livro.", source: "ANE Today · Isaías e impérios", sourceUrl: "https://anetoday.org/stromberg-isaiah-empires/", destination: "atlas", destinationLabel: "Ver expansão dos impérios" },
  { id: "judah-babylon", order: "06", date: "722–539 a.C.", label: "Judá, queda e exílio", empire: "Neoassíria e Neo-Babilônia", narrative: "A queda de Samaria, a crise de Jerusalém e o exílio moldam a linguagem de julgamento, lamento, esperança e responsabilidade coletiva.", textLayer: "2Rs 18–25 · Jr · Ez · Is 40–55 · Lm", evidence: "Prisma de Senaqueribe, crônicas babilônicas, tabletes de Al-Yahudu e estratigrafia de destruições.", debate: "É preciso distinguir deportação de todas as populações, continuidade local e a memória teológica do exílio.", source: "British Museum · Babilônia", sourceUrl: "https://www.britishmuseum.org/collection/galleries/mesopotamia", destination: "atlas", destinationLabel: "Abrir Babilônia e Yehud" },
  { id: "persia", order: "07", date: "539–332 a.C.", label: "Pérsia, retorno e Yehud", empire: "Aquemênida", narrative: "Esdras, Neemias, Ageu, Zacarias e partes de Isaías enfrentam templo, terra, Torá, casamento, calendário e reconstrução sob administração persa.", textLayer: "Ed · Ne · Ag · Zc · Et · Is 56–66", evidence: "Cilindro de Ciro, papiros de Elefantina, arquivos de Al-Yahudu e moedas de Yehud.", debate: "Cronologias de Esdras–Neemias e o grau de influência persa sobre instituições judaítas são debatidos.", source: "Pleiades · mundo persa", sourceUrl: "https://pleiades.stoa.org/places", destination: "canon", destinationLabel: "Ver cânon e transmissão" },
  { id: "hellenism", order: "08", date: "332–63 a.C.", label: "Helenismo, revolta e textos do Segundo Templo", empire: "Macedônia, Selêucidas e Hasmoneus", narrative: "A conquista de Alexandre abre novos arranjos linguísticos e políticos. A crise de Antíoco IV, a revolta macabeia e o governo hasmoneu são decisivos para compreender Daniel e literatura fora do cânon protestante.", textLayer: "Dn 7–12 · 1–2Mc · Eclo · Sb · Jdt", evidence: "Moedas hasmoneias, fontes de 1–2 Macabeus, Josefo e escavações.", debate: "Helenização não foi apenas imposição ou resistência: grupos diferentes negociaram língua, poder e pertencimento de maneiras distintas.", source: "SBL Press · Septuaginta e cânon", sourceUrl: "https://scholarlypublishingcollective.org/sblpress/jbl/article/143/2/303/389157/Suddenly-and-Then-Gradually-The-Growth-of-the", destination: "apocrypha", destinationLabel: "Abrir apócrifos e deuterocanônicos" },
  { id: "roman-jesus", order: "09", date: "63 a.C.–70 d.C.", label: "Roma, templo e o movimento de Jesus", empire: "República e Império Romano", narrative: "Jesus e os Evangelhos pertencem a um judaísmo plural sob Roma. Galileia, Jerusalém, templo, tributação e messianismo formam o ambiente de leitura.", textLayer: "Evangelhos · At 1–12 · cartas iniciais", evidence: "Josefo, Fílon, inscrições, moedas, sítios de Cafarnaum, Séforis e Cesareia.", debate: "Retratos de Jesus nos Evangelhos são narrativos e teológicos; reconstruções históricas trabalham com probabilidades e não com acesso direto a cada episódio.", source: "Bible Odyssey · Jesus e contexto", sourceUrl: "https://www.bibleodyssey.org/", destination: "library", destinationLabel: "Abrir Evangelhos" },
  { id: "church", order: "10", date: "30–100 d.C.", label: "Cidades, cartas e comunidades", empire: "Império Romano mediterrâneo", narrative: "Atos e as cartas mostram redes em Antioquia, Corinto, Éfeso, Filipos e Roma, atravessadas por status social, hospitalidade, conflito e missão.", textLayer: "At · cartas paulinas e católicas · Ap 1–3", evidence: "Inscrição de Gálio, arqueologia urbana, epigrafia e as próprias cartas.", debate: "Atos, cartas autênticas e escritos posteriores não fornecem uma cronologia simples; suas relações precisam ser comparadas criticamente.", source: "Pleiades · cidades mediterrâneas", sourceUrl: "https://pleiades.stoa.org/places", destination: "atlas", destinationLabel: "Seguir rotas paulinas" },
  { id: "apocalypse", order: "11", date: "c. 70–100 d.C.", label: "Crise, resistência e novas criações", empire: "Roma imperial", narrative: "Apocalipse usa imagens de bestas, Babilônia, cidades e nova criação para formar imaginação de fidelidade diante de poderes imperiais.", textLayer: "Ap 1–22 · tradições joaninas", evidence: "Geografia das sete cidades, numismática, inscrições e estudos de culto imperial compõem o contexto sem decifrar cada símbolo automaticamente.", debate: "Preterismo, historicismo, futurismo, idealismo e leituras ecléticas organizam respostas diferentes; nenhuma leitura elimina o gênero apocalíptico.", source: "Pleiades · Ásia Menor", sourceUrl: "https://pleiades.stoa.org/places", destination: "apocalypse", destinationLabel: "Abrir rota escatológica" },
];
