export type CloseReadingFrame = { range: string; title: string; question: string; bodyLabel?: string };

const frames = (items: CloseReadingFrame[]) => items;

export const closeReadingFrames: Record<string, CloseReadingFrame[]> = {
  tobit: frames([{ range: "Tob 1–2", title: "Diáspora, misericórdia e risco", question: "Como fidelidade pública se torna perigosa em Nínive?" }, { range: "Tob 3", title: "Duas orações na mesma noite", question: "Como Tobit e Sara compartilham uma dor que ainda não conhecem?" }, { range: "Tob 4–6", title: "A viagem como formação", question: "O que Tobias aprende ao sair da casa do pai?" }, { range: "Tob 7–9", title: "Sara, casamento e libertação", question: "Como uma nova casa nasce no meio de trauma e oração?" }, { range: "Tob 10–14", title: "Retorno, cura e memória", question: "O que a restauração ensina sem apagar a dor atravessada?" }]),
  judith: frames([{ range: "Jdt 1–7", title: "Cerco e imaginação imperial", question: "Como a narrativa cria uma crise que parece sem saída?" }, { range: "Jdt 8", title: "Judite recusa colocar Deus no relógio", question: "Por que ela confronta o prazo proposto pelos líderes?" }, { range: "Jdt 9–10", title: "Oração, preparo e passagem", question: "Como espiritualidade e estratégia caminham juntas?" }, { range: "Jdt 11–13", title: "O centro do acampamento inimigo", question: "Como o poder de Holofernes se torna vulnerável?" }, { range: "Jdt 14–16", title: "Defesa, canto e memória", question: "Como a cidade aprende a contar sua libertação?" }]),
  wisdom: frames([{ range: "Sb 1–2", title: "A lógica dos ímpios", question: "Como prazer e morte podem ser usados para justificar injustiça?" }, { range: "Sb 3–6", title: "O justo e a crise da morte", question: "Por que o sofrimento do justo exige esperança mais ampla?" }, { range: "Sb 7–9", title: "Sabedoria pedida", question: "O que um governante aprende quando recebe sabedoria como dom?" }, { range: "Sb 10–12", title: "Sabedoria e a história de Israel", question: "Como o passado é relido como educação para a justiça?" }, { range: "Sb 13–19", title: "Idolatria, criação e êxodo", question: "Como a crítica ao poder chega ao centro da memória do êxodo?" }]),
  sirach: frames([{ range: "Eclo 1–6", title: "Temor, prova e amizade", question: "Que tipo de caráter a sabedoria procura formar?" }, { range: "Eclo 7–23", title: "Casa, fala e dinheiro", question: "Como decisões cotidianas se tornam matéria de fé?" }, { range: "Eclo 24", title: "A sabedoria encontra morada", question: "Por que a Sabedoria é associada à Torá e a Israel?" }, { range: "Eclo 25–42", title: "Discernimento em público", question: "Como o livro trata trabalho, honra, corpo e relações sociais?" }, { range: "Eclo 43–51", title: "Criação e antepassados", question: "Como louvor e memória formam uma comunidade?" }]),
  baruch: frames([{ range: "Br 1:1–2:35", title: "Confissão de uma comunidade ferida", question: "O que significa lembrar a ruína sem negar a responsabilidade?" }, { range: "Br 3:1–8", title: "Oração longe da cidade", question: "Como a comunidade busca Deus fora de Jerusalém?" }, { range: "Br 3:9–4:4", title: "Onde a Sabedoria é encontrada", question: "Por que impérios e riqueza não podem comprar direção?" }, { range: "Br 4:5–5:9", title: "Sião em luto e esperança", question: "Como a cidade ferida é reimaginada em retorno?" }, { range: "Carta de Jeremias", title: "Ídolos que precisam ser guardados", question: "O que a sátira ensina sobre falsas seguranças?" }]),
  "maccabees-1": frames([{ range: "1Mc 1", title: "Império, costumes e crise", question: "O que estava em jogo na política de Antíoco IV?" }, { range: "1Mc 2", title: "Matatias e a decisão de resistir", question: "Como uma família se torna foco de revolta?" }, { range: "1Mc 3–4", title: "Judas e a dedicação do templo", question: "Por que recuperar o templo reorganiza a memória do povo?" }, { range: "1Mc 5–9", title: "Guerra, alianças e perdas", question: "Como resistência religiosa se mistura a estratégia política?" }, { range: "1Mc 10–16", title: "Da revolta à dinastia", question: "O que muda quando a resistência passa a governar?" }]),
  "maccabees-2": frames([{ range: "2Mc 1–3", title: "Cartas, templo e conflitos internos", question: "Como Jerusalém já vive tensões antes da perseguição?" }, { range: "2Mc 4–6", title: "Crise e profanação", question: "Como disputa por poder interno encontra pressão imperial?" }, { range: "2Mc 6–7", title: "Eleazar, mãe e irmãos", question: "O que o martírio afirma sobre consciência e fidelidade?" }, { range: "2Mc 8–11", title: "Batalha, oração e dedicação", question: "Como o livro relaciona memória cultual e resistência?" }, { range: "2Mc 12–15", title: "Morte, ressurreição e intercessão", question: "Quais debates confessionais nascem dessas cenas?" }]),
  "greek-additions": frames([{ range: "Tradições gregas", title: "Textos que circularam em mais de uma forma", question: "Por que versões diferentes merecem estudo cuidadoso?" }, { range: "Ester A–F", title: "Sonhos e orações em Ester", question: "O que muda quando a providência é dita em voz alta?" }, { range: "Daniel 3:24–90", title: "Azarias e o cântico na fornalha", question: "Como louvor pode nascer no centro da ameaça?" }, { range: "Susana", title: "Falso testemunho sob investigação", question: "Como o texto confronta abuso e testemunho apressado?" }, { range: "Bel e o Dragão", title: "Ídolos, vestígios e coragem", question: "Como Daniel desmonta uma religião de aparência?" }]),
  anagignoskomena: frames([{ range: "Coleções e usos", title: "Textos que foram lidos", question: "Como liturgia e cânon se cruzam sem serem a mesma coisa?" }, { range: "Salmo 151", title: "Davi, o menor escolhido", question: "Como um cântico expande a memória de Davi e Golias?" }, { range: "Oração de Manassés", title: "Penitência depois da violência", question: "O que significa pedir perdão sem apagar o passado?" }, { range: "3 Macabeus 1–4", title: "Diáspora sob coerção", question: "Como a comunidade judaica do Egito enfrenta um poder hostil?" }, { range: "3 Macabeus 5–7", title: "Libertação, celebração e recepção", question: "Como a memória da crise se torna louvor comunitário?" }]),
  "enoch-jubilees": frames([{ range: "1En 1–16", title: "Vigilantes e origem da violência", question: "Como o livro amplia a pergunta de Gênesis 6?" }, { range: "1En 17–36", title: "Viagens e ordem cósmica", question: "Que justiça as imagens do céu procuram tornar visível?" }, { range: "1En 37–71", title: "Parábolas, reis e julgamento", question: "Como esperança apocalíptica confronta poderes humanos?" }, { range: "1En 72–108", title: "Tempo, calendário e exortação", question: "Por que o tempo ordenado importa para a fidelidade?" }, { range: "Jubileus", title: "Gênesis e Êxodo relidos", question: "Como calendário e aliança reorganizam a memória bíblica?" }]),
  worlds: frames([{ range: "Gn 1–2", title: "Criação e bondade do mundo", question: "O que muda quando o mundo é contado como criação boa, e não como acidente?" }, { range: "Gn 3–11", title: "Ruptura, violência e Babel", question: "Como o mal se espalha de uma escolha para famílias, cidades e povos?" }, { range: "Gn 12–50", title: "Famílias em deslocamento", question: "Como promessas, fome, migração e reconciliação formam Israel?" }]),
  exodus: frames([{ range: "Êx 1–15", title: "Escravidão, confronto e saída", question: "O que o êxodo revela sobre Deus diante da opressão?" }, { range: "Êx 16–18", title: "Deserto e aprendizagem", question: "Por que sair do Egito não resolve imediatamente os medos do povo?" }, { range: "Êx 19–40", title: "Sinai, aliança e presença", question: "Como liberdade se transforma em uma forma nova de vida comum?" }]),
  judges: frames([{ range: "Jz 1–5", title: "Terra disputada e Débora", question: "Como liderança e conflito aparecem antes de existir um reino unido?" }, { range: "Jz 6–16", title: "Gideão, Jefté e Sansão", question: "Por que libertadores também carregam falhas tão graves?" }, { range: "Jz 17–21; Rt 1–4", title: "Desordem e fidelidade cotidiana", question: "Como Rute responde com cuidado ao mundo violento de Juízes?" }]),
  monarchy: frames([{ range: "1Sm 8–15", title: "O pedido por um rei", question: "Por que desejar um rei pode ser compreensível e perigoso ao mesmo tempo?" }, { range: "1Sm 16–2Sm 24", title: "Davi: promessa e violência", question: "Como a Bíblia preserva tanto a grandeza quanto os pecados de Davi?" }, { range: "1Rs 1–11", title: "Salomão, templo e sobrecarga", question: "O que acontece quando sabedoria e riqueza convivem com exploração?" }]),
  divided: frames([{ range: "1Rs 12–16", title: "Dois reinos e duas capitais", question: "Como a divisão política muda a vida religiosa e social?" }, { range: "1Rs 17–2Rs 10", title: "Elias, Eliseu e a crítica ao poder", question: "Como profetas confrontam reis e suas alianças?" }, { range: "2Rs 11–17", title: "Samaria cai diante da Assíria", question: "O que uma conquista imperial faz com pessoas e memórias?" }]),
  "judah-babylon": frames([{ range: "2Rs 18–23", title: "Reformas, ameaças e falsas seguranças", question: "Por que Jerusalém não é protegida apenas por ter um templo?" }, { range: "2Rs 24–25; Jr", title: "Queda, lamento e exílio", question: "Como a Bíblia fala quando a cidade e o templo são destruídos?" }, { range: "Ez; Is 40–55", title: "Vida fora da terra e esperança", question: "Como Deus continua presente com quem vive em derrota e deslocamento?" }]),
  persia: frames([{ range: "Ed 1–6", title: "Retorno e reconstrução do templo", question: "O que significa voltar a uma cidade que ainda não está restaurada?" }, { range: "Ed 7–10; Ne 1–7", title: "Torá, muralhas e conflitos", question: "Como uma comunidade reconstrói regras, casas e fronteiras?" }, { range: "Ag; Zc; Ml", title: "Profetas depois do exílio", question: "Por que culto, justiça e esperança continuam em disputa?" }]),
  hellenism: frames([{ range: "Alexandre e seus sucessores", title: "Um mundo de língua grega", question: "Como uma mudança de impérios altera cidades, educação e identidade?" }, { range: "Dn 7–12; 1–2Mc", title: "Crise sob Antíoco e revolta", question: "Como perseguição e templo geram memória, resistência e esperança?" }, { range: "Textos do Segundo Templo", title: "Um judaísmo plural", question: "Por que tantos livros diferentes surgem no período antes de Jesus?" }]),
  "roman-jesus": frames([{ range: "Herodes, Roma e o templo", title: "A terra de Jesus sob império", question: "Como impostos, soldados, festas e templo moldam o cenário dos Evangelhos?" }, { range: "Galileia e o anúncio do reino", title: "Jesus entre aldeias e multidões", question: "O que suas curas, parábolas e refeições dizem sobre o reino de Deus?" }, { range: "Jerusalém, cruz e ressurreição", title: "Conflito e esperança", question: "Por que a execução romana se tornou o centro da fé cristã?" }]),
  church: frames([{ range: "At 1–7", title: "Jerusalém, Espírito e mesa comum", question: "Como uma comunidade nasce de testemunho, oração e partilha?" }, { range: "At 8–15", title: "Fronteiras atravessadas", question: "Como samaritanos, gentios e judeus entram numa mesma história?" }, { range: "At 16–28; cartas", title: "Cidades, cartas e conflitos", question: "Por que cada comunidade recebe ensino situado em seus problemas?" }]),
  apocalypse: frames([{ range: "Ap 1–3", title: "Sete igrejas reais", question: "Por que o livro começa com comunidades concretas antes das grandes visões?" }, { range: "Ap 4–20", title: "Trono, Cordeiro, bestas e juízo", question: "Como imagens simbólicas criticam poder, idolatria e violência?" }, { range: "Ap 21–22", title: "Nova criação e cura das nações", question: "Por que a esperança final é cidade, jardim e presença de Deus?" }])
};
