export type CloseReadingFrame = { range: string; title: string; question: string; bodyLabel?: string };

const frames = (items: CloseReadingFrame[]) => items;

export const closeReadingFrames: Record<string, CloseReadingFrame[]> = {
  tobit: frames([{ range: "Tob 1–3", title: "Uma casa fiel em meio à dor", question: "Como alguém generoso continua quando a vida parece injusta?" }, { range: "Tob 4–9", title: "A viagem de Tobias e o encontro com Sara", question: "Como a viagem transforma duas famílias feridas?" }, { range: "Tob 10–14", title: "Retorno, cura e memória", question: "O que a restauração de uma família ensina sobre esperança?" }]),
  judith: frames([{ range: "Jdt 1–7", title: "A cidade cercada e o medo", question: "O que acontece quando uma comunidade mede Deus pelo tempo da sua crise?" }, { range: "Jdt 8–13", title: "A estratégia de Judite", question: "Como oração, risco e inteligência aparecem juntos na narrativa?" }, { range: "Jdt 14–16", title: "Libertação e canto", question: "Por que a vitória não termina no ato de Judite, mas na resposta do povo?" }]),
  wisdom: frames([{ range: "Sb 1–6", title: "Justos, ímpios e a pergunta pela morte", question: "Por que o livro recusa chamar o mal de destino normal?" }, { range: "Sb 7–9", title: "A sabedoria pedida por Salomão", question: "O que é sabedoria além de inteligência e poder?" }, { range: "Sb 10–19", title: "Sabedoria na história do êxodo", question: "Como o passado de Israel critica idolatria e opressão?" }]),
  sirach: frames([{ range: "Eclo 1–23", title: "Aprender a viver no cotidiano", question: "Como fala, amizade, trabalho e família se tornam assuntos de fé?" }, { range: "Eclo 24–42", title: "Sabedoria, Torá e vida pública", question: "Por que a instrução de Deus forma hábitos, e não só ideias?" }, { range: "Eclo 43–51", title: "Criação, culto e os antepassados", question: "Como memória e louvor formam a identidade de um povo?" }]),
  baruch: frames([{ range: "Br 1:1–3:8", title: "Confissão depois da ruína", question: "Como um povo fala com Deus quando perdeu cidade, templo e segurança?" }, { range: "Br 3:9–5:9", title: "Sabedoria e retorno", question: "Onde a comunidade procura direção depois do exílio?" }, { range: "Carta de Jeremias", title: "Ídolos que não respondem", question: "O que a crítica aos ídolos revela sobre falsas seguranças?" }]),
  "maccabees-1": frames([{ range: "1Mc 1–4", title: "Crise, profanação e revolta", question: "O que estava em jogo quando o templo e as práticas judaicas foram atacados?" }, { range: "1Mc 5–9", title: "Guerras, alianças e liderança", question: "Como resistência religiosa se mistura a estratégia e poder político?" }, { range: "1Mc 10–16", title: "Da revolta ao governo", question: "O que muda quando uma família de resistência se torna dinastia?" }]),
  "maccabees-2": frames([{ range: "2Mc 1–7", title: "Templo, perseguição e martírio", question: "Como o livro fala de fidelidade quando o corpo está sob ameaça?" }, { range: "2Mc 8–12", title: "Vitórias, oração e memória", question: "Por que batalha e culto aparecem no mesmo relato?" }, { range: "2Mc 13–15", title: "Morte, esperança e dedicação", question: "Como a esperança de ressurreição muda a leitura do sofrimento?" }]),
  "greek-additions": frames([{ range: "Ester grego", title: "Orações dentro de uma história de risco", question: "O que muda quando a oração de Ester e Mardoqueu fica explícita?" }, { range: "Daniel 3", title: "Azarias na fornalha", question: "Como louvor e lamento convivem no meio da ameaça?" }, { range: "Susana; Bel e o Dragão", title: "Justiça e crítica aos ídolos", question: "Como investigar uma acusação e desmontar uma falsa divindade?" }]),
  anagignoskomena: frames([{ range: "Salmo 151", title: "Davi, o menor escolhido", question: "Como um cântico expande a memória de Davi e Golias?" }, { range: "Oração de Manassés", title: "Confissão e retorno", question: "O que significa pedir perdão depois de uma história de violência?" }, { range: "3 Macabeus", title: "Diáspora e perseguição", question: "Como judeus no Egito imaginam proteção em uma crise imperial?" }]),
  "enoch-jubilees": frames([{ range: "1 Enoque 1–36", title: "Vigilantes, violência e juízo", question: "Como o livro amplia as perguntas abertas por Gênesis 6?" }, { range: "1 Enoque 37–108", title: "Visões, tempo e justiça", question: "Por que a esperança apocalíptica fala de julgamento e restauração?" }, { range: "Jubileus", title: "Gênesis e Êxodo relidos", question: "Como calendário e aliança reorganizam a memória bíblica?" }]),
  worlds: frames([{ range: "Gn 1–2", title: "Criação e bondade do mundo", question: "O que muda quando o mundo é contado como criação boa, e não como acidente?" }, { range: "Gn 3–11", title: "Ruptura, violência e Babel", question: "Como o mal se espalha de uma escolha para famílias, cidades e povos?" }, { range: "Gn 12–50", title: "Famílias em deslocamento", question: "Como promessas, fome, migração e reconciliação formam Israel?" }]),
  exodus: frames([{ range: "Êx 1–15", title: "Escravidão, confronto e saída", question: "O que o êxodo revela sobre Deus diante da opressão?" }, { range: "Êx 16–18", title: "Deserto e aprendizagem", question: "Por que sair do Egito não resolve imediatamente os medos do povo?" }, { range: "Êx 19–40", title: "Sinai, aliança e presença", question: "Como liberdade se transforma em uma forma nova de vida comum?" }]),
  judges: frames([{ range: "Jz 1–5", title: "Terra disputada e Débora", question: "Como liderança e conflito aparecem antes de existir um reino unido?" }, { range: "Jz 6–16", title: "Gideão, Jefté e Sansão", question: "Por que libertadores também carregam falhas tão graves?" }, { range: "Jz 17–21; Rt 1–4", title: "Desordem e fidelidade cotidiana", question: "Como Rute responde com cuidado ao mundo violento de Juízes?" }]),
  monarchy: frames([{ range: "1Sm 8–15", title: "O pedido por um rei", question: "Por que desejar um rei pode ser compreensível e perigoso ao mesmo tempo?" }, { range: "1Sm 16–2Sm 24", title: "Davi: promessa e violência", question: "Como a Bíblia preserva tanto a grandeza quanto os pecados de Davi?" }, { range: "1Rs 1–11", title: "Salomão, templo e sobrecarga", question: "O que acontece quando sabedoria e riqueza convivem com exploração?" }]),
  divided: frames([{ range: "1Rs 12–16", title: "Dois reinos e duas capitais", question: "Como a divisão política muda a vida religiosa e social?" }, { range: "1Rs 17–2Rs 10", title: "Elias, Eliseu e a crítica ao poder", question: "Como profetas confrontam reis e suas alianças?" }, { range: "2Rs 11–17", title: "Samaria cai diante da Assíria", question: "O que uma conquista imperial faz com pessoas e memórias?" }]),
  "judah-babylon": frames([{ range: "2Rs 18–23", title: "Reformas, ameaças e falsas seguranças", question: "Por que Jerusalém não é protegida apenas por ter um templo?" }, { range: "2Rs 24–25; Jr", title: "Queda, lamento e exílio", question: "Como a Bíblia fala quando a cidade e o templo são destruídos?" }, { range: "Ez; Is 40–55", title: "Vida fora da terra e esperança", question: "Como Deus continua presente com quem vive em derrota e deslocamento?" }]),
  persia: frames([{ range: "Ed 1–6", title: "Retorno e reconstrução do templo", question: "O que significa voltar a uma cidade que ainda não está restaurada?" }, { range: "Ed 7–10; Ne 1–7", title: "Torá, muralhas e conflitos", question: "Como uma comunidade reconstrói regras, casas e fronteiras?" }, { range: "Ag; Zc; Ml", title: "Profetas depois do exílio", question: "Por que culto, justiça e esperança continuam em disputa?" }]),
  hellenism: frames([{ range: "Alexandre e seus sucessores", title: "Um mundo de língua grega", question: "Como uma mudança de impérios altera cidades, educação e identidade?" }, { range: "Dn 7–12; 1–2Mc", title: "Crise sob Antíoco e revolta", question: "Como perseguição e templo geram memória, resistência e esperança?" }, { range: "Textos do Segundo Templo", title: "Um judaísmo plural", question: "Por que tantos livros diferentes surgem no período antes de Jesus?" }]),
  "roman-jesus": frames([{ range: "Herodes, Roma e o templo", title: "A terra de Jesus sob império", question: "Como impostos, soldados, festas e templo moldam o cenário dos Evangelhos?" }, { range: "Galileia e o anúncio do reino", title: "Jesus entre aldeias e multidões", question: "O que suas curas, parábolas e refeições dizem sobre o reino de Deus?" }, { range: "Jerusalém, cruz e ressurreição", title: "Conflito e esperança", question: "Por que a execução romana se tornou o centro da fé cristã?" }]),
  church: frames([{ range: "At 1–7", title: "Jerusalém, Espírito e mesa comum", question: "Como uma comunidade nasce de testemunho, oração e partilha?" }, { range: "At 8–15", title: "Fronteiras atravessadas", question: "Como samaritanos, gentios e judeus entram numa mesma história?" }, { range: "At 16–28; cartas", title: "Cidades, cartas e conflitos", question: "Por que cada comunidade recebe ensino situado em seus problemas?" }]),
  apocalypse: frames([{ range: "Ap 1–3", title: "Sete igrejas reais", question: "Por que o livro começa com comunidades concretas antes das grandes visões?" }, { range: "Ap 4–20", title: "Trono, Cordeiro, bestas e juízo", question: "Como imagens simbólicas criticam poder, idolatria e violência?" }, { range: "Ap 21–22", title: "Nova criação e cura das nações", question: "Por que a esperança final é cidade, jardim e presença de Deus?" }])
};
