// Cartografia de Leituras: dados editoriais profundos para verbetes enciclopédicos, com autoridade da afirmação explicitada em cada camada.
export type CompleteSource = { label: string; url: string };
export type CompleteBook = {
  name: string;
  opening: string;
  identity: { canon: string; genre: string; period: string; traditionalAuthor: string; academicView: string; setting: string; centralQuestion: string };
  structure: { range: string; title: string; summary: string }[];
  themes: { label: string; explanation: string }[];
  people: { name: string; role: string }[];
  places: { name: string; note: string }[];
  layers: { label: string; tone: "scripture" | "pentecostal" | "confession" | "academic"; text: string; refs: string }[];
  connections: { book: string; label: string; reason: string }[];
  sources: CompleteSource[];
};

const idbFaith = "https://churchofgod.org/beliefs/declaration-of-faith/";
const idbBrasil = "https://igrejadedeus.org.br/";

export const completeBookEntries: Record<string, CompleteBook> = {
  "Gênesis": {
    name: "Gênesis",
    opening: "O livro dos começos não oferece apenas uma origem do mundo: ele acompanha a formação de uma família, uma promessa e uma memória que atravessa deslocamentos, rupturas e reconciliações.",
    identity: { canon: "1º livro do Pentateuco e do Antigo Testamento", genre: "Narrativa de origens, saga ancestral e teologia da promessa", period: "Mundo narrado patriarcal; composição final debatida entre períodos monárquico e pós-exílico", traditionalAuthor: "Moisés, segundo a tradição judaico-cristã", academicView: "Obra composta e editada a partir de tradições orais e escritas diversas; a autoria mosaica unitária é debatida na pesquisa", setting: "História primeva, Mesopotâmia, Canaã e Egito", centralQuestion: "Como uma humanidade fragmentada e uma família vulnerável se tornam portadoras de uma promessa para todas as famílias da terra?" },
    structure: [
      { range: "Gn 1–11", title: "História primeva", summary: "Criação, imagem de Deus, ruptura, violência, dilúvio e Babel apresentam uma humanidade simultaneamente digna, ferida e dispersa." },
      { range: "Gn 12–25", title: "Abraão e Sara", summary: "O chamado, os deslocamentos, a promessa, a aliança e os conflitos familiares formam uma vocação de alcance universal." },
      { range: "Gn 26–36", title: "Isaque, Rebeca, Jacó e Esaú", summary: "A promessa passa por rivalidades, enganos, encontros e reconciliações, sem apagar a complexidade moral dos personagens." },
      { range: "Gn 37–50", title: "José e a família no Egito", summary: "A inveja, a migração, a fome e a administração do poder culminam em preservação familiar e releitura da providência." },
    ],
    themes: [
      { label: "Criação e dignidade", explanation: "A humanidade é apresentada como portadora da imagem de Deus e responsável pelo cuidado da terra." },
      { label: "Aliança e missão", explanation: "A escolha de Abraão não termina na família: a promessa mira todas as famílias da terra." },
      { label: "Providência e agência", explanation: "O livro mantém juntas ação divina, decisões humanas, injustiça, arrependimento e consequências." },
      { label: "Deslocamento", explanation: "Quase toda promessa é vivida em movimento: sair, peregrinar, perder, retornar e habitar provisoriamente." },
    ],
    people: [{ name: "Adão e Eva", role: "Humanidade primordial e imagem de Deus" }, { name: "Noé", role: "Sobrevivente e guardião de uma aliança cósmica" }, { name: "Abraão e Sara", role: "Família da promessa e hospitalidade" }, { name: "Jacó", role: "Patriarca marcado por luta, nome novo e reconciliação" }, { name: "José", role: "Irmão vendido que administra crise e reencontra a família" }],
    places: [{ name: "Éden", note: "Espaço simbólico de vida, presença e ruptura" }, { name: "Harã", note: "Lugar de passagem no chamado de Abraão" }, { name: "Canaã", note: "Território da promessa e da peregrinação" }, { name: "Egito", note: "Lugar de sobrevivência, poder e preservação familiar" }],
    layers: [
      { label: "Texto bíblico", tone: "scripture", text: "Gênesis articula criação, queda, dilúvio, Babel e patriarcas por meio de repetições, bênçãos, deslocamentos e conflitos familiares. O final não resolve tudo: deixa a família no Egito, aguardando o movimento de Êxodo.", refs: "Gn 1–3; 12:1–3; 50:20" },
      { label: "Leitura pentecostal", tone: "pentecostal", text: "Uma leitura pentecostal pode enfatizar a presença do Espírito na criação, a vocação missionária da promessa e a santidade como resposta a Deus. Essa leitura deve evitar transformar cada detalhe narrativo em alegoria obrigatória.", refs: "Gn 1:2; 12:1–3; 41:38" },
      { label: "Posição confessional", tone: "confession", text: "A declaração de fé da Church of God reconhece a Bíblia como Palavra inspirada e autoridade de fé e prática. Isso expressa uma moldura confessional para receber Gênesis; não constitui um comentário oficial exclusivo sobre cada capítulo.", refs: idbFaith },
      { label: "Pesquisa acadêmica", tone: "academic", text: "A pesquisa distingue mundo narrado, tradições patriarcais e composição final. A historicidade dos patriarcas e a relação com narrativas do antigo Oriente Próximo permanecem temas de debate, sem autorizar certezas maiores que as evidências.", refs: "Bible Odyssey; estudos de composição do Pentateuco" },
    ],
    connections: [{ book: "Êxodo", label: "Continuidade narrativa", reason: "A família de Jacó termina no Egito; Êxodo começa com sua transformação em povo oprimido." }, { book: "Romanos", label: "Promessa e fé", reason: "Paulo retoma Abraão para discutir fé, justiça e inclusão de judeus e gentios." }, { book: "João", label: "Criação e nova vida", reason: "O prólogo joanino reabre a linguagem do princípio para apresentar o Verbo e a vida." }],
    sources: [{ label: "Bible Odyssey — Society of Biblical Literature", url: "https://www.bibleodyssey.org/" }, { label: "Declaração de Fé — Church of God", url: idbFaith }, { label: "Igreja de Deus no Brasil", url: idbBrasil }],
  },
  "Êxodo": {
    name: "Êxodo",
    opening: "Êxodo narra a saída da opressão e a difícil aprendizagem de ser um povo livre: libertação, aliança, lei, culto e presença de Deus aparecem como um único processo de formação comunitária.",
    identity: { canon: "2º livro do Pentateuco", genre: "Narrativa de libertação, legislação de aliança e instruções de culto", period: "Mundo narrado situado no segundo milênio a.C.; data do evento e composição final são debatidas", traditionalAuthor: "Moisés, segundo a tradição", academicView: "Texto composto por tradições e camadas redacionais, consolidado ao longo de períodos monárquico, exílico e pós-exílico", setting: "Egito, deserto, Mar Vermelho e Sinai", centralQuestion: "Como pessoas libertas da escravidão se tornam uma comunidade capaz de viver diante de Deus e do próximo?" },
    structure: [{ range: "Êx 1–15", title: "Opressão e saída", summary: "Moisés, as parteiras, as pragas, a Páscoa e a travessia formam uma memória de libertação e confronto com o poder imperial." }, { range: "Êx 16–18", title: "Deserto e provisão", summary: "Maná, água, conflitos e aconselhamento de Jetro revelam que sair do Egito não encerra a dependência nem a necessidade de organização." }, { range: "Êx 19–24", title: "Sinai e aliança", summary: "A presença no monte, os mandamentos e o compromisso comunitário dão forma ética à liberdade recebida." }, { range: "Êx 25–40", title: "Tabernáculo e presença", summary: "Instruções de culto, Bezerro de Ouro e renovação da aliança perguntam como a presença divina habita no meio de um povo instável." }],
    themes: [{ label: "Libertação", explanation: "Deus ouve o clamor dos oprimidos e confronta estruturas de dominação; a libertação recebe forma comunitária." }, { label: "Aliança e lei", explanation: "Os mandamentos são resposta de um povo resgatado, não uma técnica de compra da salvação." }, { label: "Presença", explanation: "Nuvem, fogo, tenda e glória narram proximidade sem reduzir Deus a um objeto controlável." }, { label: "Memória", explanation: "Páscoa e narrativas de geração em geração impedem que a comunidade esqueça de onde veio." }],
    people: [{ name: "Moisés", role: "Mediador, profeta e líder relutante" }, { name: "Arão e Miriã", role: "Liderança sacerdotal e profética" }, { name: "Faraó", role: "Poder imperial em oposição à libertação" }, { name: "Jetro", role: "Mentor de organização e discernimento" }, { name: "Bezalel e Aoliabe", role: "Artesãos capacitados para o santuário" }],
    places: [{ name: "Egito", note: "Casa de escravidão e cenário de confronto de poderes" }, { name: "Mar Vermelho", note: "Fronteira narrativa entre perseguição e caminho aberto" }, { name: "Sinai", note: "Montanha da teofania, aliança e formação" }, { name: "Deserto", note: "Espaço de provação, provisão e dependência" }],
    layers: [{ label: "Texto bíblico", tone: "scripture", text: "Êxodo conecta o nome de Deus, a Páscoa, a aliança e o tabernáculo. O objetivo da saída é servir e habitar em uma comunidade marcada por justiça e presença.", refs: "Êx 3:14–15; 12; 19–24; 40" }, { label: "Leitura pentecostal", tone: "pentecostal", text: "A tradição pentecostal pode ler a libertação como chamado à missão e à santidade, destacando a capacitação de trabalhadores do santuário e a direção de Deus no caminho. A aplicação pastoral deve evitar usar Êxodo para prometer libertação automática de toda crise.", refs: "Êx 9:1; 31:1–6; 13:21–22" }, { label: "Posição confessional", tone: "confession", text: "A declaração confessional da Church of God recebe as Escrituras como norma de fé e prática e articula salvação, santificação e culto a partir do testemunho bíblico. Ela não resolve todos os debates históricos sobre o êxodo.", refs: idbFaith }, { label: "Pesquisa acadêmica", tone: "academic", text: "A datação precoce e tardia, a escala demográfica, a arqueologia do Sinai e a formação do culto a Yahweh são debates distintos. A enciclopédia os manterá separados do valor teológico da memória do êxodo.", refs: "Bible Odyssey — Exodus; estudos de história do antigo Israel" }],
    connections: [{ book: "Gênesis", label: "Família que vira povo", reason: "Êxodo continua a história dos descendentes de Jacó que estavam no Egito." }, { book: "Mateus", label: "Jesus e o novo êxodo", reason: "Mateus usa imagens de Moisés, deserto, monte e libertação para narrar Jesus." }, { book: "Atos", label: "Libertação e missão", reason: "A igreja interpreta sua expansão como testemunho guiado pelo Espírito depois de uma saída e uma formação." }],
    sources: [{ label: "Bible Odyssey — Society of Biblical Literature", url: "https://www.bibleodyssey.org/dictionary/exodus-2/" }, { label: "Declaração de Fé — Church of God", url: idbFaith }, { label: "Igreja de Deus no Brasil", url: idbBrasil }],
  },
  "Mateus": {
    name: "Mateus",
    opening: "Mateus apresenta Jesus como Messias davídico, novo Moisés e mestre do Reino dos Céus. Sua narrativa trabalha a continuidade entre as Escrituras de Israel, a comunidade dos discípulos e a missão entre todas as nações.",
    identity: { canon: "1º Evangelho do Novo Testamento", genre: "Biografia antiga (bios) com narrativa profética, ensino e apelo comunitário", period: "Ministério de Jesus no início do século I; composição final geralmente situada por volta de 80–90 d.C.", traditionalAuthor: "Mateus, o cobrador de impostos, segundo a tradição patrística", academicView: "Autor cristão anônimo, provavelmente ligado a uma comunidade judaico-cristã, usando Marcos, tradições de ditos e material próprio", setting: "Galileia, Judeia, Jerusalém e comunidades sob domínio romano", centralQuestion: "Como o Reino de Deus se torna visível na vida, no ensino, na morte e na missão de Jesus?" },
    structure: [{ range: "Mt 1–4", title: "Identidade do Messias", summary: "Genealogia, nascimento, fuga, retorno, João Batista e tentação colocam Jesus dentro da história de Israel." }, { range: "Mt 5–7", title: "Sermão do Monte", summary: "Bem-aventuranças, justiça, oração e amor aos inimigos descrevem a ética do Reino." }, { range: "Mt 8–18", title: "Sinais, missão e comunidade", summary: "Milagres, envio dos Doze, parábolas, confissão de Pedro e cuidado com os pequenos estruturam o discipulado." }, { range: "Mt 19–28", title: "Conflito, cruz e comissão", summary: "O caminho para Jerusalém, o confronto no templo, a paixão, a ressurreição e a missão universal culminam a narrativa." }],
    themes: [{ label: "Reino dos Céus", explanation: "Não é apenas lugar futuro: é o reinado de Deus que reorganiza prioridades, relações e esperança." }, { label: "Cumprimento", explanation: "Citações e alusões às Escrituras de Israel apresentam Jesus em continuidade e tensão com a história anterior." }, { label: "Discipulado", explanation: "Seguir Jesus envolve prática, misericórdia, discernimento, reconciliação e perseverança." }, { label: "Missão às nações", explanation: "A história de Israel se abre para uma comunidade enviada a todos os povos." }],
    people: [{ name: "Jesus", role: "Messias, mestre, Filho e Senhor ressuscitado" }, { name: "Maria", role: "Mãe de Jesus na narrativa da encarnação" }, { name: "Pedro", role: "Porta-voz dos discípulos e figura de liderança" }, { name: "Fariseus e escribas", role: "Oponentes em debates sobre justiça e interpretação" }, { name: "Pilatos", role: "Governador romano no julgamento de Jesus" }],
    places: [{ name: "Belém", note: "Nascimento narrado em chave davídica e profética" }, { name: "Galileia", note: "Centro do ensino, sinais e chamado dos discípulos" }, { name: "Cafarnaum", note: "Base narrativa de parte do ministério" }, { name: "Jerusalém", note: "Cidade da paixão, morte e ressurreição" }],
    layers: [{ label: "Texto bíblico", tone: "scripture", text: "Os cinco grandes blocos de ensino alternados com narrativa dão ao Evangelho uma arquitetura de formação. A Grande Comissão encerra o livro com presença, autoridade, batismo e discipulado.", refs: "Mt 5–7; 16:13–20; 28:18–20" }, { label: "Leitura pentecostal", tone: "pentecostal", text: "A leitura pentecostal destaca o Espírito na concepção e no batismo de Jesus, os sinais do Reino, a santidade do Sermão do Monte e a missão transcultural. Poder espiritual é inseparável de caráter, serviço e obediência.", refs: "Mt 1:18; 3:16; 10; 28:18–20" }, { label: "Posição confessional", tone: "confession", text: "A declaração de fé da Church of God sustenta a inspiração das Escrituras, a plena divindade de Cristo, o batismo cristão e a expectativa da volta de Jesus. O texto confessional é uma moldura doutrinária, não uma autoria institucional do Evangelho.", refs: idbFaith }, { label: "Pesquisa acadêmica", tone: "academic", text: "A dependência de Marcos, a hipótese de uma fonte de ditos e o contexto pós-70 são discussões centrais. Também é preciso ler a polêmica de Mateus com cuidado, sem convertê-la em autorização para hostilidade contra judeus hoje.", refs: "https://www.bibleodyssey.org/dictionary/matthew-the-gospel-according-to/" }],
    connections: [{ book: "Gênesis", label: "Genealogia e promessa", reason: "Mateus abre com Abraão e Davi para situar Jesus na história de Israel." }, { book: "Êxodo", label: "Novo Moisés", reason: "Monte, deserto, ensino e libertação criam ecos do êxodo sem apagar a singularidade de Jesus." }, { book: "Atos", label: "Comissão em movimento", reason: "Atos narra a expansão da comunidade enviada por Jesus para Jerusalém e as nações." }],
    sources: [{ label: "Bible Odyssey — Matthew", url: "https://www.bibleodyssey.org/dictionary/matthew-the-gospel-according-to/" }, { label: "Declaração de Fé — Church of God", url: idbFaith }, { label: "Igreja de Deus no Brasil", url: idbBrasil }],
  },
  "João": {
    name: "João",
    opening: "João narra Jesus como o Verbo encarnado, a luz e a vida. Em vez de repetir a forma dos Sinóticos, constrói uma teologia narrativa de sinais, discursos, testemunhas, conflitos e presença do Paráclito.",
    identity: { canon: "4º Evangelho do Novo Testamento", genre: "Biografia antiga teologicamente elaborada, com sinais, discursos e ironia narrativa", period: "Ministério de Jesus no primeiro século; redação final geralmente situada entre 90–100 d.C.", traditionalAuthor: "João, filho de Zebedeu e discípulo amado, segundo a tradição", academicView: "Texto associado a uma tradição ou comunidade joanina, com possíveis etapas de composição e edição", setting: "Galileia, Samaria, Jerusalém e comunidades em tensão no mundo romano", centralQuestion: "Quem é Jesus e como a fé nele se transforma em vida, testemunho, amor e missão?" },
    structure: [{ range: "Jo 1:1–18", title: "Prólogo do Verbo", summary: "O Logos preexistente entra na história como carne, graça e revelação do Pai." }, { range: "Jo 1:19–12:50", title: "Livro dos Sinais", summary: "Sinais, encontros e discursos revelam identidade, vida e conflito diante de testemunhas." }, { range: "Jo 13–20", title: "Livro da Glória", summary: "O lava-pés, os discursos de despedida, a cruz e a ressurreição mostram a glória como amor entregue." }, { range: "Jo 21", title: "Epílogo e testemunho", summary: "A restauração de Pedro e o testemunho do discípulo amado encerram a narrativa com vocação e memória." }],
    themes: [{ label: "Verbo e encarnação", explanation: "A linguagem de criação e presença é reaberta para afirmar que Deus se dá a conhecer em Jesus." }, { label: "Vida eterna", explanation: "Vida eterna é relação presente com o Pai e o Filho, sem perder a esperança futura." }, { label: "Paráclito", explanation: "O Espírito ensina, lembra, testemunha e conduz a comunidade depois da partida de Jesus." }, { label: "Testemunho", explanation: "Personagens, sinais, Escrituras e comunidade testemunham para que o leitor creia e tenha vida." }],
    people: [{ name: "Jesus", role: "Verbo encarnado, enviado do Pai e doador da vida" }, { name: "João Batista", role: "Testemunha que aponta para o Cordeiro" }, { name: "Nicodemos", role: "Mestre que busca compreender o novo nascimento" }, { name: "Mulher samaritana", role: "Testemunha e agente de anúncio em sua cidade" }, { name: "Tomé", role: "Discípulo que confessa Jesus como Senhor e Deus" }],
    places: [{ name: "Caná", note: "Primeiro sinal e manifestação da glória" }, { name: "Sicar", note: "Lugar do encontro com a mulher samaritana" }, { name: "Jerusalém", note: "Cidade de festas, debates, paixão e ressurreição" }, { name: "Betânia", note: "Casa de Marta, Maria e Lázaro" }],
    layers: [{ label: "Texto bíblico", tone: "scripture", text: "Os sinais não são espetáculos isolados: apontam para a identidade de Jesus e exigem resposta. O mandamento central dos discursos de despedida é permanecer no amor e testemunhar.", refs: "Jo 1:1–18; 7:37–39; 13–17; 20:30–31" }, { label: "Leitura pentecostal", tone: "pentecostal", text: "João é central para a pneumatologia pentecostal: novo nascimento, rios de água viva, sopro do Ressuscitado e o Paráclito unem regeneração, presença e missão. Experiência espiritual é julgada pelo testemunho de Cristo e pelo amor.", refs: "Jo 3:3–8; 7:37–39; 14–16; 20:21–22" }, { label: "Posição confessional", tone: "confession", text: "A declaração da Church of God confessa a divindade de Cristo e a obra do Espírito; João fornece textos frequentemente usados nessa formulação. A associação não significa que a denominação tenha editado o texto joanino.", refs: idbFaith }, { label: "Pesquisa acadêmica", tone: "academic", text: "A autoria, a comunidade joanina, os discursos longos e a relação com a sinagoga são debates complexos. Precisão topográfica e elaboração teológica podem coexistir sem que cada fala seja tratada como transcrição literal.", refs: "https://www.bibleodyssey.org/; https://www.sbl-site.org/" }],
    connections: [{ book: "Mateus", label: "Quatro retratos de Jesus", reason: "João compartilha a paixão e a ressurreição com os Sinóticos, mas reorganiza sinais e discursos." }, { book: "Atos", label: "Espírito e testemunho", reason: "O Paráclito joanino e o Espírito de Atos sustentam uma comunidade enviada." }, { book: "Romanos", label: "Vida e Espírito", reason: "João e Romanos articulam fé, vida, nova existência e ação do Espírito em registros distintos." }],
    sources: [{ label: "Bible Odyssey — Society of Biblical Literature", url: "https://www.bibleodyssey.org/" }, { label: "Society of Biblical Literature", url: "https://www.sbl-site.org/" }, { label: "Declaração de Fé — Church of God", url: idbFaith }],
  },
  "Atos": {
    name: "Atos",
    opening: "Atos narra a expansão do testemunho de Jerusalém até Roma. Não é apenas uma coleção de aventuras apostólicas: é uma teologia narrativa da missão conduzida pelo Espírito através de pessoas, casas, conflitos, decisões e cidades.",
    identity: { canon: "5º livro do Novo Testamento e ponte entre Evangelhos e cartas", genre: "Historiografia antiga, narrativa missionária e teologia da comunidade", period: "Narrativa de aproximadamente três décadas; data de composição precoce ou tardia é debatida", traditionalAuthor: "Lucas, companheiro de Paulo, segundo a tradição", academicView: "Segundo volume de uma obra lucana; autoria, fontes e relação com as cartas de Paulo são debatidas", setting: "Jerusalém, Judeia, Samaria, Ásia Menor, Grécia e Roma", centralQuestion: "Como o Espírito transforma um grupo local em testemunha intercultural sem apagar conflitos e discernimento?" },
    structure: [{ range: "At 1–7", title: "Jerusalém e Pentecostes", summary: "A promessa do Espírito, a comunidade, a oração, os sinais, os conflitos e o martírio de Estêvão inauguram o testemunho." }, { range: "At 8–12", title: "Judeia, Samaria e gentios", summary: "Filipe, Saulo, Cornélio e Antioquia desmontam fronteiras geográficas e étnicas." }, { range: "At 13–20", title: "Viagens e concílio", summary: "Paulo e companheiros anunciam em cidades mediterrâneas; o concílio de Jerusalém discerne a inclusão dos gentios." }, { range: "At 21–28", title: "Prisão e Roma", summary: "A prisão, os julgamentos, o naufrágio e a chegada a Roma mostram que a palavra continua avançando em meio à vulnerabilidade." }],
    themes: [{ label: "Espírito e missão", explanation: "O Espírito envia, impede, direciona, capacita e cria testemunho; não é adorno de uma narrativa já pronta." }, { label: "Discernimento comunitário", explanation: "Decisões difíceis exigem oração, escuta, Escrituras, testemunho e responsabilidade coletiva." }, { label: "Universalidade", explanation: "Judeus, samaritanos e gentios aparecem dentro de uma história de inclusão ainda cheia de tensão." }, { label: "Coragem vulnerável", explanation: "Testemunho envolve prisão, oposição, viagens perigosas e presença de Deus em situações sem controle." }],
    people: [{ name: "Pedro", role: "Líder da comunidade e ponte para os gentios" }, { name: "Estêvão", role: "Testemunha e mártir cujo discurso amplia a memória de Israel" }, { name: "Filipe", role: "Evangelista que cruza fronteiras geográficas e sociais" }, { name: "Barnabé", role: "Mediador, encorajador e companheiro de missão" }, { name: "Paulo", role: "Missionário e prisioneiro cuja testemunha chega a Roma" }],
    places: [{ name: "Jerusalém", note: "Origem narrativa da missão" }, { name: "Antioquia", note: "Base de uma comunidade multicultural e missionária" }, { name: "Éfeso", note: "Centro de ensino, conflito e expansão na Ásia" }, { name: "Roma", note: "Confim simbólico e político alcançado pelo testemunho" }],
    layers: [{ label: "Texto bíblico", tone: "scripture", text: "Atos 1:8 funciona como programa geográfico e teológico: Jerusalém, Judeia, Samaria e confins da terra. O final aberto sugere continuidade da missão, não encerramento de toda a história.", refs: "At 1:8; 2; 10; 15; 28:30–31" }, { label: "Leitura pentecostal", tone: "pentecostal", text: "A tradição pentecostal lê Atos como testemunho normativo da ação do Espírito, incluindo batismo no Espírito, línguas, curas e dons. A leitura responsável mantém junto poder, santidade, discernimento, serviço e missão, sem usar Atos como receita mecânica para cada culto.", refs: "At 1:5–8; 2:1–4; 10:44–48; 19:1–7" }, { label: "Posição confessional", tone: "confession", text: "A declaração de fé da Church of God afirma o batismo no Espírito como promessa para os crentes e a continuidade da cura divina. Ao apresentar isso, a enciclopédia marca a afirmação como posição confessional pentecostal, não como consenso de todas as igrejas.", refs: idbFaith }, { label: "Pesquisa acadêmica", tone: "academic", text: "A cronologia de Paulo, os discursos resumidos, a relação entre Atos e Gálatas e o grau de objetividade historiográfica são debates importantes. A confirmação de detalhes geográficos não elimina a natureza teológica da narrativa.", refs: "https://www.bibleodyssey.org/dictionary/acts-of-the-apostles-the/" }],
    connections: [{ book: "Lucas", label: "Segundo volume", reason: "Atos continua o projeto narrativo do Evangelho de Lucas a partir da ascensão e da promessa do Espírito." }, { book: "Mateus", label: "Comissão e testemunho", reason: "A missão às nações recebe formas geográficas e comunitárias depois da ressurreição." }, { book: "Romanos", label: "Paulo em contexto", reason: "Atos fornece parte do cenário das viagens, cidades e conflitos que cercam a missão paulina." }],
    sources: [{ label: "Bible Odyssey — Acts of the Apostles", url: "https://www.bibleodyssey.org/dictionary/acts-of-the-apostles-the/" }, { label: "Bible Odyssey — Pentecost in Acts", url: "https://www.bibleodyssey.org/articles/pentecost-in-the-book-of-acts/" }, { label: "Declaração de Fé — Church of God", url: idbFaith }],
  },
  "Romanos": {
    name: "Romanos",
    opening: "Romanos é uma carta de apresentação, teologia e reconciliação comunitária. Paulo articula o evangelho, a justiça de Deus, a vida no Espírito e a convivência entre judeus e gentios enquanto prepara uma missão para o Ocidente.",
    identity: { canon: "1ª epístola paulina na ordem do Novo Testamento", genre: "Carta pastoral e teológica com diatribe, exegese e instrução comunitária", period: "Meados do século I, geralmente 55–58 d.C., provavelmente a partir de Corinto", traditionalAuthor: "Paulo, com Tércio como escriba", academicView: "Uma das cartas paulinas indiscutidas; debates menores tratam da forma final e do capítulo 16", setting: "Comunidades domésticas de Roma sob o Império, com judeus e gentios em tensão", centralQuestion: "Como o evangelho cria uma comunidade reconciliada, justa e viva no Espírito em meio a diferenças reais?" },
    structure: [{ range: "Rm 1:1–17", title: "Saudação e tese", summary: "Paulo se apresenta e anuncia o evangelho como poder de Deus, revelando justiça para quem crê." }, { range: "Rm 1:18–5:21", title: "Pecado, graça e fé", summary: "A carta argumenta sobre a necessidade universal e apresenta a justificação, Abraão, paz e reconciliação." }, { range: "Rm 6–8", title: "Nova vida e Espírito", summary: "Batismo, luta, adoção, intercessão e esperança formam o coração pneumatológico da carta." }, { range: "Rm 9–11", title: "Israel e a misericórdia", summary: "Paulo enfrenta a questão da fidelidade de Deus e do lugar de Israel no plano de salvação." }, { range: "Rm 12–16", title: "Corpo, ética e missão", summary: "Dons, amor, autoridades, acolhimento dos fracos, planos de viagem e saudações tornam a teologia comunitária." }],
    themes: [{ label: "Justiça de Deus", explanation: "Pode designar o caráter justo e a ação fiel de Deus que cria uma relação restaurada; o termo é debatido." }, { label: "Fé e graça", explanation: "A carta desloca a confiança do mérito e confronta qualquer base de orgulho étnico ou religioso." }, { label: "Vida no Espírito", explanation: "O Espírito habita, testemunha, vivifica, ajuda na oração e forma uma comunidade de filhos e herdeiros." }, { label: "Unidade", explanation: "A ética de Romanos busca uma mesa comum entre fortes e fracos sem apagar diferenças de consciência." }],
    people: [{ name: "Paulo", role: "Apóstolo e autor que escreve a uma igreja que ainda não visitou" }, { name: "Tércio", role: "Amanuense que registra a carta" }, { name: "Febe", role: "Servidora/diaconisa de Cencreia e possível portadora da carta" }, { name: "Priscila e Áquila", role: "Cooperadores e anfitriões de comunidades" }, { name: "Abraão", role: "Figura bíblica mobilizada para discutir fé e promessa" }],
    places: [{ name: "Roma", note: "Comunidade destinatária, formada por grupos domésticos" }, { name: "Corinto", note: "Local provável da redação e da preparação da viagem" }, { name: "Jerusalém", note: "Destino da coleta para os santos" }, { name: "Espanha", note: "Horizonte missionário projetado por Paulo" }],
    layers: [{ label: "Texto bíblico", tone: "scripture", text: "Romanos não é uma lista abstrata de doutrinas: a tese sobre justiça desemboca em corpo, dons, amor, acolhimento, serviço e missão. Romanos 8 une sofrimento, Espírito, adoção e esperança.", refs: "Rm 1:16–17; 5:1; 8; 12:1–8; 15:7" }, { label: "Leitura pentecostal", tone: "pentecostal", text: "A leitura pentecostal mantém justificação, regeneração e santificação conectadas. O Espírito não apenas consola interiormente: conduz uma vida santa, sustenta a oração e impulsiona a missão da igreja.", refs: "Rm 6–8; 12:1–2; 15:13" }, { label: "Posição confessional", tone: "confession", text: "A declaração de fé da Church of God articula a autoridade bíblica, a salvação pela fé, a santificação e a vida no Espírito. Romanos oferece linguagem para essas convicções, mas a aplicação denominacional deve ser identificada como leitura confessional.", refs: idbFaith }, { label: "Pesquisa acadêmica", tone: "academic", text: "A Nova Perspectiva sobre Paulo, a interpretação de obras da lei, a demografia de Roma e a integridade do capítulo 16 são debates que exigem precisão. Judaísmo do Segundo Templo não deve ser retratado como mero legalismo.", refs: "https://www.bibleodyssey.org/dictionary/romans-the-letter-of-paul-to-the/" }],
    connections: [{ book: "Gênesis", label: "Abraão e promessa", reason: "Paulo relê Abraão para argumentar sobre fé, promessa e alcance da justiça de Deus." }, { book: "Atos", label: "Paulo em movimento", reason: "A carta se situa no horizonte de viagens, coleta, Jerusalém e futura missão ocidental." }, { book: "João", label: "Vida no Espírito", reason: "Ambos articulam vida, fé, nova existência e ação do Espírito em linguagens diferentes." }],
    sources: [{ label: "Bible Odyssey — Romans", url: "https://www.bibleodyssey.org/dictionary/romans-the-letter-of-paul-to-the/" }, { label: "Declaração de Fé — Church of God", url: idbFaith }, { label: "Igreja de Deus no Brasil", url: idbBrasil }],
  },
};
