// Cartografia de Leituras — camada enciclopédica: cada trilha possui contexto, vocabulário, perguntas e fontes.
export type Lesson = { id: string; title: string; kind: string; duration: string; body: string; keyPoints: string[]; source: string };
export type StudyModule = { id: string; number: string; title: string; subtitle: string; description: string; level: string; duration: string; tone: string; lessons: Lesson[] };

export const studyModules: StudyModule[] = [
  { id: "fundamentos", number: "01", title: "Como a Bíblia chegou até nós", subtitle: "Cânon, autoridade e formação", description: "Antes de perguntar o que um versículo significa, descubra que tipo de biblioteca está em suas mãos: textos de épocas, línguas, comunidades e gêneros diferentes.", level: "Fundamentos", duration: "2h 40min", tone: "blue", lessons: [
    { id: "o-que-e-biblia", title: "Uma biblioteca, não um livro único", kind: "Aula-base", duration: "18 min", body: "A palavra Bíblia esconde uma coleção. O Antigo Testamento reúne narrativas, leis, poesia, sabedoria e profecia; o Novo Testamento reúne evangelhos, história narrativa, cartas e apocalipse. Cada obra tem situação comunicativa, vocabulário e expectativas próprias. Ler bem começa por reconhecer essa pluralidade sem perder de vista que comunidades posteriores passaram a lê-la como um conjunto.", keyPoints: ["Antologia com múltiplas vozes e épocas", "Gênero literário muda a forma de ler", "A ordem dos livros também produz uma leitura"], source: "Society of Biblical Literature · Bible Odyssey" },
    { id: "formacao-canon", title: "Como se forma um cânon", kind: "História", duration: "24 min", body: "Cânon é uma lista de escritos que uma comunidade reconhece como normativos. Historicamente, a formação foi gradual: textos circularam, foram copiados, lidos em assembleias, comentados e agrupados. Não houve uma única reunião que tenha decidido toda a Bíblia. No cristianismo antigo, apostolicidade, antiguidade, coerência com a regra de fé e uso amplo foram critérios importantes, mas aplicados de modo desigual por regiões.", keyPoints: ["Reconhecimento histórico não é o mesmo que decreto instantâneo", "As listas variaram durante séculos", "Niceia não escolheu os livros do Novo Testamento"], source: "SBL Press · How the Books Became the Bible" },
    { id: "tres-mundos", title: "Três mundos para toda leitura", kind: "Método", duration: "21 min", body: "Uma leitura profunda observa o mundo por trás do texto — história, política, economia e língua —, o mundo do texto — narrador, personagens, estrutura e imagens — e o mundo diante do texto — recepção, perguntas do leitor e efeitos na comunidade. Nenhuma camada elimina as outras. A plataforma usa as três para evitar tanto o anacronismo quanto a fragmentação excessiva.", keyPoints: ["Contexto histórico", "Forma literária", "Recepção e aplicação responsável"], source: "Pontifícia Comissão Bíblica · A interpretação da Bíblia na Igreja" },
  ] },
  { id: "antigo-testamento", number: "02", title: "O mundo do Antigo Testamento", subtitle: "Israel, Judá e os impérios", description: "Percorra o Levante antigo entre aldeias, reinos, templos, exílios e retornos. Aprenda o que a arqueologia ilumina e onde a narrativa bíblica continua sendo uma interpretação teológica da história.", level: "História", duration: "4h 10min", tone: "wine", lessons: [
    { id: "levante", title: "O Levante entre Egito e Mesopotâmia", kind: "Contexto", duration: "26 min", body: "Canaã era um corredor entre grandes potências. Egito, Assíria, Babilônia e Pérsia disputaram tributos, rotas e lealdades. As comunidades que produziram a Bíblia não viviam isoladas: negociavam, migravam, guerreavam e absorviam formas literárias do antigo Oriente Próximo. O contexto imperial ajuda a entender por que terra, templo, tributo e exílio aparecem tantas vezes.", keyPoints: ["O Levante é uma ponte geopolítica", "Impérios organizavam a vida por tributo", "A Bíblia dialoga com culturas vizinhas"], source: "The Oxford History of the Biblical World" },
    { id: "exodo-conquista", title: "Êxodo, conquista e memória", kind: "Debate", duration: "32 min", body: "O êxodo é a memória fundacional de libertação de Israel. A arqueologia não confirmou uma migração em massa nas proporções narradas, e os modelos sobre a emergência de Israel em Canaã são variados. Isso não torna o relato irrelevante: significa que devemos distinguir o que a narrativa quer afirmar sobre identidade, poder e aliança da reconstrução histórica que pode ser demonstrada com outras fontes.", keyPoints: ["Memória fundacional e verificação histórica são perguntas diferentes", "Josué é uma narrativa teológica da terra", "Modelos arqueológicos permanecem debatidos"], source: "Society of Biblical Literature · recursos de arqueologia bíblica" },
    { id: "exilio-retorno", title: "Exílio, retorno e reconstrução", kind: "Eixo central", duration: "29 min", body: "A queda de Jerusalém e o exílio babilônico reorganizaram a identidade de Judá. Textos foram editados, tradições foram preservadas e novas perguntas surgiram: como ser povo sem rei, terra ou templo? No período persa, a reconstrução do templo e a reorganização de Yehud deram novo peso a sacerdotes, escribas, memória e lei. O exílio funciona como experiência histórica e como metáfora literária.", keyPoints: ["O exílio é ruptura e laboratório de identidade", "A lei é também tecnologia de memória", "Retorno não significa voltar ao mundo anterior"], source: "The Anchor Yale Bible Dictionary" },
  ] },
  { id: "novo-testamento", number: "03", title: "Jesus e o primeiro século", subtitle: "Judaísmo, Roma e comunidades", description: "Leia os Evangelhos e as cartas dentro do judaísmo do Segundo Templo e do mundo romano, evitando caricaturas de conflito e simplificações sobre o nascimento do cristianismo.", level: "Contexto", duration: "3h 35min", tone: "olive", lessons: [
    { id: "judaísmo-segundo-templo", title: "Um judaísmo plural", kind: "Contexto", duration: "27 min", body: "O judaísmo do século I não era monolítico. Havia diferenças sobre templo, pureza, autoridade, ressurreição, interpretação da Torá e relação com Roma. Fariseus, saduceus, essênios, grupos apocalípticos e seguidores de Jesus participavam desse campo plural. O conflito dos Evangelhos deve ser lido como debate interno e situado, não como licença para hostilidade contra judeus.", keyPoints: ["Pluralidade interna", "Templo e Torá como centros de debate", "Cuidado com leituras antijudaicas"], source: "Society of Biblical Literature · Bible Odyssey" },
    { id: "jesus-historico", title: "O Jesus histórico e os Evangelhos", kind: "Leitura crítica", duration: "31 min", body: "Os evangelhos são narrativas antigas sobre Jesus, não biografias modernas. Foram compostos décadas depois de sua morte, a partir de tradições orais e escritas, e organizam acontecimentos para comunicar uma interpretação teológica. A pesquisa histórica trabalha com critérios como múltipla atestação, coerência e contexto, mas não transforma probabilidades em certeza absoluta.", keyPoints: ["Memória e teologia trabalham juntas", "Cada evangelho tem composição e ênfase próprias", "História e confissão são camadas distintas"], source: "Cambridge University Press · Religion and Bible" },
    { id: "paulo-e-cidades", title: "Paulo, cidades e redes de casas", kind: "Comunidades", duration: "25 min", body: "As cartas paulinas mostram comunidades urbanas com conflitos reais: comida, status, sexualidade, trabalho, dons, dinheiro e pertencimento étnico. Paulo escreve para situações específicas, não para um leitor abstrato. As sete cartas geralmente consideradas autênticas são uma janela excepcional para a formação de comunidades mediterrâneas e para a negociação entre judeus e gentios.", keyPoints: ["Cartas respondem a situações concretas", "Casa e cidade são unidades de expansão", "A missão também produz conflito e revisão"], source: "Oxford Biblical Studies Online" },
  ] },
  { id: "livros", number: "04", title: "Os 66 livros por dentro", subtitle: "Argumento, estrutura e voz", description: "Aprenda a entrar em cada livro sem tratá-lo como coleção de frases soltas. Descubra argumento, forma, personagens, tensões internas e relações com outros textos.", level: "Leitura", duration: "12h 00min", tone: "brass", lessons: [
    { id: "pentateuco", title: "Torá: identidade, lei e presença", kind: "Antigo Testamento", duration: "45 min", body: "Gênesis a Deuteronômio formam uma grande moldura de origens, família, libertação, deserto e compromisso. A lei não aparece apenas como lista jurídica: organiza tempo, corpo, trabalho, culto, reparação e pertencimento. A tradição mosaica é fundamental para a recepção, enquanto a pesquisa acadêmica estuda camadas e tradições que se reuniram ao longo do tempo.", keyPoints: ["Gênesis: promessa e família", "Êxodo–Números: libertação, culto e deserto", "Deuteronômio: memória e escolha"], source: "Bible Odyssey · Browse the Bible" },
    { id: "profetas-sabedoria", title: "Profetas e sábios: duas perguntas difíceis", kind: "Antigo Testamento", duration: "39 min", body: "Profetas não são apenas previsores do futuro: são intérpretes de alianças, economia, guerra e culto. A literatura sapiencial pergunta como viver quando as fórmulas não bastam. Provérbios, Jó e Eclesiastes formam uma conversa interna sobre ordem, sofrimento, limite e sentido.", keyPoints: ["Profecia critica o presente", "Sabedoria observa a experiência", "A Bíblia preserva discordâncias produtivas"], source: "The Oxford Handbook of Biblical Studies" },
    { id: "evangelhos-cartas-apocalipse", title: "Evangelhos, cartas e apocalipse", kind: "Novo Testamento", duration: "42 min", body: "Os Evangelhos apresentam retratos narrativos de Jesus; Atos constrói uma história de expansão; as cartas argumentam com comunidades; o Apocalipse usa símbolos para resistir a poderes imperiais. O gênero muda a pergunta: uma visão não é um cronograma, uma carta não é um tratado universal e uma narrativa não é uma transcrição neutra.", keyPoints: ["Mateus, Marcos, Lucas e João não são cópias entre si", "Cartas têm destinatários e problemas", "Apocalipse é resistência simbólica"], source: "Bible Odyssey · Literary Context" },
  ] },
  { id: "temas", number: "05", title: "Os grandes temas em movimento", subtitle: "Aliança, reino, justiça e esperança", description: "Siga palavras que atravessam séculos e mudam de forma. Compare tensões internas em vez de forçar uma única definição para todo o cânon.", level: "Teologia bíblica", duration: "5h 20min", tone: "wine", lessons: [
    { id: "alianca-reino", title: "Aliança e reino", kind: "Tema", duration: "29 min", body: "Aliança articula promessas, responsabilidades e pertencimento, mas não aparece de modo idêntico em cada livro. Reino pode indicar soberania divina, projeto político, esperança escatológica ou linguagem usada por comunidades para imaginar uma ordem diferente. A melhor leitura pergunta quem fala, em que crise e com qual imagem de futuro.", keyPoints: ["Aliança possui formas diversas", "Reino é linguagem política e teológica", "Contexto decide o peso do termo"], source: "Society of Biblical Literature" },
    { id: "justica-sofrimento", title: "Justiça, sofrimento e teodiceia", kind: "Tema", duration: "34 min", body: "A literatura bíblica não resolve o sofrimento em uma única fórmula. Provérbios oferece padrões de sabedoria; Jó desmonta explicações fáceis; Salmos dá voz ao lamento; os profetas denunciam estruturas que produzem pobreza. O cânon conserva a tensão, permitindo que a pergunta permaneça aberta e responsável.", keyPoints: ["Lamento também é linguagem teológica", "Sofrimento não deve ser explicado apressadamente", "Justiça inclui estrutura, não apenas intenção"], source: "Bible Odyssey · Wisdom Literature" },
    { id: "presenca-esperanca", title: "Presença, exílio e esperança", kind: "Tema", duration: "27 min", body: "Tenda, templo, espírito, sabedoria e comunidade são imagens diferentes para proximidade. Depois do exílio, a esperança não é simplesmente voltar ao passado: é imaginar uma presença que atravesse fronteiras, corpos e instituições. No Novo Testamento, essa linguagem é reconfigurada em torno de Jesus, do Espírito e de comunidades.", keyPoints: ["Presença pode ser móvel ou institucional", "Esperança nasce dentro da crise", "Restauração é uma ideia disputada"], source: "The Oxford Encyclopedia of the Bible and Gender Studies" },
  ] },
  { id: "manuscritos", number: "06", title: "Manuscritos, línguas e traduções", subtitle: "Do rolo ao texto crítico", description: "Veja como textos foram escritos, copiados, traduzidos e comparados. Aprenda o que variantes textuais significam — e o que elas não significam.", level: "Pesquisa", duration: "3h 50min", tone: "blue", lessons: [
    { id: "linguas", title: "Hebraico, aramaico e grego", kind: "Línguas", duration: "22 min", body: "A Bíblia Hebraica foi escrita majoritariamente em hebraico, com trechos em aramaico; o Novo Testamento foi escrito em grego koiné. Línguas não são recipientes neutros: metáforas, tempos verbais, trocadilhos e termos culturais carregam decisões que toda tradução precisa negociar.", keyPoints: ["Hebraico bíblico e aramaico", "Grego koiné e mundo mediterrâneo", "Tradução é interpretação com responsabilidade"], source: "Society of Biblical Literature · Digital Resources" },
    { id: "qumran-massoretico", title: "Qumran, Septuaginta e Texto Massorético", kind: "Testemunhas", duration: "30 min", body: "Os Manuscritos do Mar Morto mostram que diferentes formas textuais circulavam antes da estabilização medieval do Texto Massorético. A Septuaginta, tradução grega antiga, às vezes preserva leituras diferentes. Comparar testemunhas não destrói o texto: torna visível sua história de transmissão e permite decisões editoriais mais transparentes.", keyPoints: ["Pluralidade textual antiga", "Qumran anterior aos códices medievais", "Versões antigas são testemunhas"], source: "Yale University Library · New Testament Studies: Textual Criticism" },
    { id: "variantes-traducao", title: "Variantes e escolhas de tradução", kind: "Oficina", duration: "36 min", body: "Variantes surgem por lapsos, harmonizações, correções gramaticais e mudanças intencionais. A crítica textual pesa evidências externas — idade, distribuição e genealogia — e internas — estilo, dificuldade e contexto. Uma boa tradução informa suas escolhas e reconhece que equivalência formal e funcional são polos de um espectro, não slogans absolutos.", keyPoints: ["Variante não é sinônimo de fraude", "Edições críticas registram alternativas", "Traduções devem explicitar escolhas relevantes"], source: "Yale University Library · Textual Criticism" },
  ] },
  { id: "interpretacao", number: "07", title: "Como interpretar com responsabilidade", subtitle: "Exegese, hermenêutica e tradições", description: "Aprenda a lidar com textos difíceis, leituras conflitantes e diferentes tradições sem confundir convicção religiosa com consenso histórico.", level: "Método", duration: "4h 25min", tone: "olive", lessons: [
    { id: "exegese-hermeneutica", title: "Exegese não é apenas opinião", kind: "Método", duration: "24 min", body: "Exegese pergunta pelo sentido de um texto em seu contexto; hermenêutica pergunta pelos princípios que tornam a interpretação possível e relevante. Uma leitura responsável identifica evidências, admite incertezas, considera gênero e evita usar uma frase isolada para resolver um problema que o texto trata em escala maior.", keyPoints: ["Contexto imediato e contexto amplo", "Argumento antes de aplicação", "Evidência antes de certeza"], source: "Pontifícia Comissão Bíblica · A interpretação da Bíblia na Igreja" },
    { id: "metodos", title: "Métodos que se complementam", kind: "Ferramentas", duration: "32 min", body: "Crítica textual, histórica, da fonte, da redação, narrativa, retórica, sociológica, feminista e pós-colonial fazem perguntas diferentes. Nenhuma é uma chave universal. A pesquisa contemporânea combina métodos para observar origem, forma final, relações de poder, vozes marginalizadas e efeitos de leitura.", keyPoints: ["Diacrônico: mudanças ao longo do tempo", "Sincrônico: forma final do texto", "Contextual: posição e experiência do leitor"], source: "Society of Biblical Literature · Resources" },
    { id: "tradicoes", title: "Protestante, católica, ortodoxa e judaica", kind: "Comparação", duration: "28 min", body: "Tradições não diferem apenas pelo número de livros. Elas também distinguem autoridade, liturgia, interpretação, relação entre Escritura e tradição e formas de leitura comunitária. O objetivo não é nivelar diferenças, mas descrevê-las com precisão e sem transformar uma tradição em caricatura da outra.", keyPoints: ["Cânon molda o horizonte de leitura", "Autoridade possui mais de uma camada", "Comparar exige vocabulário específico"], source: "Vatican · Pontifical Biblical Commission; SBL" },
  ] },
  { id: "enciclopedia", number: "08", title: "Glossário para continuar pesquisando", subtitle: "Palavras que abrem portas", description: "Domine o vocabulário necessário para ler comentários, artigos e notas de estudo sem depender de jargão não explicado.", level: "Consulta", duration: "1h 30min", tone: "brass", lessons: [
    { id: "glossario", title: "Doze conceitos essenciais", kind: "Consulta", duration: "15 min", body: "Cânon, apócrifo, deuterocanônico, manuscrito, variante, crítica textual, exegese, hermenêutica, apocalíptica, diáspora, Segundo Templo e pseudepigrafia formam um vocabulário mínimo. Saber nomear um problema não resolve a questão, mas impede que ela seja reduzida a uma frase pronta.", keyPoints: ["Conceitos possuem histórias", "Termos podem variar entre tradições", "Definição sempre precisa de exemplo"], source: "Bible Odyssey · Reference Tools" },
    { id: "como-continuar", title: "Como estudar depois da plataforma", kind: "Próximos passos", duration: "12 min", body: "Depois do panorama, escolha um livro e leia-o inteiro. Em seguida, compare duas traduções, consulte uma introdução acadêmica, escreva o argumento do livro em suas palavras e registre perguntas que ainda não têm resposta. O estudo cresce quando você consegue distinguir o texto, sua interpretação e sua aplicação.", keyPoints: ["Leia unidades completas", "Compare traduções e comentários", "Mantenha um caderno de perguntas"], source: "Bíblia em Visão Geral · método editorial" },
  ] },
];

export const people = [
  { name: "Abraão e Sara", type: "Patriarcas", description: "Memória de deslocamento, promessa, família e hospitalidade em Gênesis.", refs: "Gn 12–25", tags: ["aliança", "migração", "família"] },
  { name: "Moisés", type: "Liderança e lei", description: "Figura central da tradição do êxodo, da aliança e da mediação da Torá.", refs: "Êx–Dt", tags: ["êxodo", "lei", "liderança"] },
  { name: "Davi", type: "Realeza", description: "Rei, personagem literário e referência dinástica que recebe leituras diversas.", refs: "1Sm–1Rs", tags: ["reino", "templo", "promessa"] },
  { name: "Ester", type: "Diáspora", description: "Rainha e protagonista de uma narrativa de sobrevivência comunitária no império persa.", refs: "Et", tags: ["coragem", "identidade", "império"] },
  { name: "Isaías e Jeremias", type: "Profetas", description: "Vozes proféticas em contextos de crise, juízo, reforma, exílio e esperança.", refs: "Is; Jr", tags: ["justiça", "exílio", "esperança"] },
  { name: "Maria e Jesus", type: "Evangelhos", description: "Personagens centrais de tradições narrativas distintas sobre nascimento, missão e conflito.", refs: "Mt–Jo", tags: ["reino", "cuidado", "messias"] },
  { name: "Pedro e Paulo", type: "Comunidades", description: "Lideranças lembradas em narrativas e cartas que mostram expansão e disputa.", refs: "At; cartas", tags: ["missão", "comunidade", "gentios"] },
];

export const glossary = [
  ["Apocalíptica", "Gênero que usa visões, símbolos e revelações para interpretar crises e imaginar a intervenção divina."],
  ["Cânon", "Conjunto de escritos reconhecidos como normativos por uma comunidade religiosa."],
  ["Crítica textual", "Comparação de manuscritos e versões para avaliar leituras antigas e preparar edições do texto."],
  ["Deuterocanônico", "Livro ou seção reconhecida como canônica em algumas tradições cristãs e não incluída em outras."],
  ["Diáspora", "Dispersão e vida de comunidades fora de seu território de origem; também a experiência cultural resultante."],
  ["Exegese", "Análise de um texto buscando explicar seu sentido, contexto, forma e argumento."],
  ["Hermenêutica", "Reflexão sobre os princípios, condições e efeitos da interpretação."],
  ["Pseudepigrafia", "Atribuição literária de um texto a uma figura de autoridade, conceito que exige cuidado e contexto."],
  ["Septuaginta", "Tradução grega antiga das Escrituras judaicas, com história textual e coleção próprias."],
  ["Segundo Templo", "Período da história judaica entre a reconstrução do templo após o exílio e sua destruição em 70 d.C."],
  ["Texto Massorético", "Tradição textual hebraica preservada e vocalizada por escribas medievais, base de muitas edições do texto hebraico."],
  ["Variante textual", "Diferença entre testemunhas manuscritas; pode ser ortográfica, gramatical, de ordem ou de conteúdo."],
] as const;

export const canonComparison = [
  { tradition: "Protestante", old: "39", new: "27", total: "66", note: "Organiza o Antigo Testamento em Lei, Históricos, Poesia, Profetas maiores e menores." },
  { tradition: "Católica", old: "46", new: "27", total: "73", note: "Inclui os deuterocanônicos e acréscimos em algumas coleções e tradições litúrgicas." },
  { tradition: "Ortodoxa", old: "varia", new: "27", total: "varia", note: "As listas podem variar entre igrejas ortodoxas; a Septuaginta tem papel histórico importante." },
  { tradition: "Tanakh judaica", old: "24", new: "—", total: "24", note: "Divide os livros em Torá, Neviim e Ketuvim; vários correspondem aos 39 livros protestantes." },
];
