import { churchStudyModules, churchStudySources } from "./church-study-data";

export type StudyLayerKey = "texto" | "contexto" | "significado" | "debate" | "pentecostal";
export type DeepStudyModule = { id: string; title: string; references: string; question: string; layers: Record<StudyLayerKey, string> };
export type DeepStudySource = string | { label: string; url: string };
export type DeepStudy = { title: string; subtitle: string; orientation: string; modules: DeepStudyModule[]; sources: DeepStudySource[] };

const module = (id: string, title: string, references: string, question: string, texto: string, contexto: string, significado: string, debate: string, pentecostal: string): DeepStudyModule => ({ id, title, references, question, layers: { texto, contexto, significado, debate, pentecostal } });

export const deepStudies: Record<string, DeepStudy> = {
  "escatologia-sem-atalhos": {
    title: "Escatologia: ler fim, juízo e nova criação", subtitle: "Daniel, Jesus, Paulo e Apocalipse em ordem de leitura, sem transformar símbolos em calendário.", orientation: "Não comece pelo ‘quando’. Comece perguntando que tipo de texto está diante de você, que crise ele enfrenta e que esperança ele anuncia.",
    modules: [
      module("genero", "1. Antes de decifrar: que tipo de texto é Apocalipse?", "Daniel 7–12 · Marcos 13 · Apocalipse 1", "O símbolo informa uma data secreta ou comunica esperança em linguagem visionária?", "Apocalipse se apresenta como revelação, profecia e carta. João escreve a igrejas reais da Ásia e usa imagens de Daniel, Ezequiel, Isaías e Êxodo; por isso uma figura raramente deve ser interpretada isoladamente.", "A literatura apocalíptica floresceu em situações de domínio imperial e conflito. Ela descreve o mundo como ele é visto a partir do trono de Deus, não apenas como ele parece a partir do poder de Roma.", "O estudo começa percebendo que ‘fim’ não significa somente destruição. O eixo é a fidelidade de Deus, a derrota do mal, a vindicação dos fiéis e a renovação da criação.", "Preterismo, historicismo, futurismo, idealismo e leituras ecléticas discordam sobre o alcance temporal das visões. O leitor deve comparar os textos que cada escola privilegia e o que cada uma deixa pouco explicado.", "A leitura pentecostal afirma a atualidade espiritual do texto e a esperança da volta de Cristo, mas recusa usar notícias, datas ou medo como chave absoluta de interpretação."),
      module("daniel-jesus", "2. Daniel, Jesus e a crise da fidelidade", "Daniel 7–12 · Mateus 24–25 · Lucas 21", "Como visões de reinos e discursos de Jesus formam discípulos em tempos de crise?", "Daniel vê reinos representados por animais e recebe a figura do ‘filho do homem’; Jesus retoma imagens semelhantes ao falar de sofrimento, queda de Jerusalém, vigilância e vinda do Filho do Homem.", "Daniel nasceu em contextos de impérios sucessivos; os Evangelhos colocam Jesus sob Roma e diante do Templo. As imagens falam de poderes reais, perseguição, culto, lealdade e julgamento.", "O objetivo não é satisfazer curiosidade sobre impérios futuros. É mostrar que nenhum poder absoluto escapa ao juízo de Deus e que a perseverança é uma forma de testemunho.", "Há debate sobre quais palavras de Jesus se referem principalmente a 70 d.C., quais alcançam a consumação final e como os dois horizontes se relacionam. O leitor não deve apagar essa tensão.", "A leitura pentecostal enfatiza vigilância, santidade, missão e esperança. A preparação cristã é fidelidade prática, não especulação cronológica."),
      module("visoes", "3. Selos, trombetas, taças e Babilônia", "Apocalipse 4–18", "As séries descrevem eventos sucessivos, ciclos simbólicos ou ambos?", "João organiza visões de trono, livro, selos, trombetas, taças, besta, Babilônia e testemunhas. As cenas se repetem e se intensificam, ligando culto celestial, violência política e sofrimento humano.", "Babilônia evoca a cidade imperial que seduz por comércio, luxo e violência; a besta representa poder que exige lealdade absoluta. O vocabulário nasce de Escrituras de Israel e de uma vida sob Roma.", "O texto expõe sistemas que transformam adoração em idolatria política e pessoas em mercadoria. A pergunta não é somente ‘quem é a besta?’, mas ‘a que poderes o povo de Deus se recusa a pertencer?’.", "O 666, o milênio e as sequências de juízo recebem interpretações distintas. Nenhuma leitura responsável pode ignorar o contexto romano, as alusões bíblicas e a dimensão futura da esperança cristã.", "Uma leitura pentecostal madura discerne conflito espiritual sem atribuir automaticamente toda instituição, pessoa ou acontecimento a um inimigo final identificável."),
      module("consumacao", "4. Ressurreição, juízo e nova criação", "1 Coríntios 15 · 1 Tessalonicenses 4–5 · Apocalipse 20–22", "Qual é a esperança final anunciada pelo Novo Testamento?", "Paulo fala de ressurreição corporal e da vinda do Senhor; Apocalipse termina com juízo, fim da morte e cidade renovada. A meta não é fuga do mundo, mas Deus habitando com seu povo.", "As cartas tratam comunidades que sofriam, enterravam seus mortos e perguntavam pelo futuro. A esperança cristã responde a luto, injustiça e morte antes de responder a curiosidade.", "A consumação afirma que Deus julga o mal e restaura a criação. Isso dá peso ético ao presente: trabalho, justiça, corpo e cuidado do próximo importam porque o futuro de Deus não despreza sua criação.", "Milênio, tribulação e arrebatamento são pontos de desacordo entre cristãos. É possível declarar a esperança comum — Cristo reina, ressuscita, julga e renova — sem fingir que os detalhes debatidos são consensuais.", "A tradição pentecostal confessa a volta visível de Cristo, a ressurreição e o juízo, chamando a igreja a missão e santidade, não a cronogramas fechados."),
    ], sources: ["Bíblia: Daniel; Evangelhos; cartas paulinas; Apocalipse.", "Richard Bauckham, The Theology of the Book of Revelation.", "Gregory K. Beale, The Book of Revelation."]
  },
  "financas-trabalho-generosidade": {
    title: "Finanças bíblicas: trabalho, dívida, generosidade e justiça", subtitle: "Uma leitura que começa no mundo agrário da Bíblia e chega às decisões pessoais sem prometer fórmulas mágicas.", orientation: "A Bíblia não oferece uma tabela automática de investimentos. Ela forma desejos, denuncia exploração e pergunta como recursos, trabalho e poder servem ao próximo.",
    modules: [
      module("mundo-economico", "1. Primeiro, entenda o mundo econômico da Bíblia", "Deuteronômio 15 · Provérbios 10–31 · Amós 2–8", "O que muda quando percebemos que ‘riqueza’ bíblica não é o mesmo que economia moderna?", "Terra, colheita, rebanho, casa e família eram os principais meios de sobrevivência. Dívida podia levar à perda de terra, dependência e trabalho forçado; por isso leis e profetas falam de descanso, colheita e proteção do vulnerável.", "Israel viveu sob agricultura de subsistência e depois sob tributos imperiais. Textos sobre empréstimo, pobre e estrangeiro tratam relações concretas de sobrevivência e poder.", "Prosperidade nos textos de sabedoria pode nomear fruto de diligência, mas não funciona como contrato que garante riqueza a todo fiel. Profetas denunciam justamente quem prospera explorando.", "Há debate sobre como aplicar jubileu, dízimo e leis agrárias hoje. O erro é tratá-las como legislação financeira direta ou descartá-las como se não tivessem ética social.", "Uma leitura pentecostal rejeita tanto a culpa espiritual do pobre quanto a promessa de enriquecimento garantido. Generosidade, trabalho honesto e cuidado mútuo são marcas de fé."),
      module("jesus", "2. Jesus: tesouro, mesa, dívida e Reino", "Mateus 6 · Lucas 4 · Lucas 12 · Lucas 16 · Lucas 19", "Jesus condena possuir bens ou o domínio que os bens exercem?", "Jesus fala de tesouro, ansiedade, ricos, pobres, credores, trabalhadores e banquetes. Ele chama Zaqueu à restituição, alerta sobre a ilusão do acúmulo e acolhe pessoas que sofrem exclusão econômica.", "A Galileia e a Judeia do primeiro século conviviam com tributação, concentração de terras e dependência. As parábolas usam cenas econômicas cotidianas, mas não podem ser reduzidas a manuais de negócios.", "O centro é a lealdade: ninguém pode servir a Deus e ao dinheiro. Isso não transforma toda posse em pecado, mas impede que segurança, identidade e poder sejam buscados no acúmulo.", "O ‘mordomo infiel’ e os textos sobre ricos geram debates reais. A interpretação deve respeitar o enredo de cada parábola em vez de extrair um slogan isolado.", "A leitura pentecostal pergunta se recursos produzem serviço, justiça e missão. Fé não é técnica para manipular resultados financeiros."),
      module("igreja", "3. Paulo, partilha e responsabilidade", "Atos 2–4 · 2 Coríntios 8–9 · 1 Timóteo 6 · Tiago 2–5", "Como a igreja combina generosidade, responsabilidade e justiça?", "Atos descreve partilha voluntária; Paulo organiza uma coleta entre igrejas; Tiago denuncia favoritismo e salários retidos. O Novo Testamento une fé, comunhão e responsabilidade material.", "As primeiras comunidades eram diversas e vulneráveis. A coleta para Jerusalém conectava gentios e judeus e expressava unidade, não apenas assistência.", "Generosidade é uma prática de comunhão: recursos deixam de ser somente privados quando a necessidade do irmão e a missão da igreja entram no campo de visão.", "Discute-se quanto Atos prescreve um modelo econômico e quanto descreve uma resposta situada. O consenso responsável é que a exploração e a indiferença não são neutras diante do evangelho.", "Na tradição pentecostal, ofertas e dízimos devem sustentar culto, missão, cuidado e transparência; não podem ser instrumento de coerção ou promessa de retorno automático."),
      module("pratica", "4. Aplicar sem transformar a Bíblia em fórmula", "Provérbios 21 · Mateus 6 · 1 Timóteo 6 · Tiago 5", "Que práticas cabem numa vida financeira fiel?", "Os textos convidam a planejar, trabalhar, evitar ganância, pagar o que é justo, cuidar da família, repartir e resistir à ansiedade. Eles não substituem informação profissional sobre orçamento, contratos ou dívida.", "Cada decisão financeira ocorre em condições diferentes: renda, desemprego, doença, desigualdade e responsabilidades familiares. A leitura bíblica não deve ser usada para julgar simplistamente quem passa necessidade.", "O sentido prático é formar caráter e comunidade: verdade, contentamento, generosidade, reparação e justiça. A pergunta deixa de ser ‘como ficar rico?’ e passa a ser ‘como administrar sem ser governado pelo dinheiro?’.", "Há cristãos que enfatizam disciplina individual e outros que enfatizam estruturas injustas. O estudo profundo mantém as duas perguntas: responsabilidade pessoal e responsabilidade social.", "A aplicação pentecostal deve combinar oração, trabalho, prudência, apoio comunitário e integridade, sem confundir milagre com garantia de enriquecimento."),
    ], sources: ["Bíblia: Lei, Profetas, Evangelhos, Atos, cartas e Tiago.", "Craig L. Blomberg, Neither Poverty nor Riches.", "Christopher J. H. Wright, Old Testament Ethics for the People of God."]
  },
  "oracao-lamento-discernimento": {
    title: "Espiritualidade: oração, lamento e discernimento", subtitle: "Um estudo sobre falar com Deus, ouvir com responsabilidade e permanecer fiel quando não há respostas rápidas.", orientation: "Espiritualidade bíblica não é sensação permanente. Ela inclui adoração, pedido, silêncio, lamento, obediência, discernimento comunitário e esperança.",
    modules: [
      module("salmos", "1. Os Salmos ensinam a falar sem máscara", "Salmos 13 · 23 · 42–43 · 88 · 139", "O lamento é falta de fé ou uma forma de fé?", "Os Salmos trazem louvor, medo, ira, confissão, silêncio e confiança. O Salmo 88 termina sem resolução fácil, mostrando que a Escritura preserva oração que ainda não recebeu alívio.", "A oração de Israel era pessoal e comunitária, cantada e memorizada. Ela formava um povo que levava sua dor diante de Deus em vez de escondê-la.", "Lamentar significa protestar diante de Deus porque se confia que ele ouve e que o mal não é normal. Não é manipular Deus, mas recusar-se a chamar a dor de bem.", "Debate-se como aplicar salmos imprecatórios e linguagem de inimigos. O leitor cristão precisa ler à luz de Cristo sem apagar as vozes de sofrimento que os salmos guardam.", "A espiritualidade pentecostal pode valorizar oração intensa e alegria, mas precisa preservar espaço para lamento, espera e cuidado de quem não recebeu a resposta desejada."),
      module("jesus", "2. Jesus ora, ensina e discerne", "Mateus 6 · Lucas 5–6 · Lucas 22 · João 17", "O que a oração de Jesus mostra sobre intimidade e obediência?", "Jesus ora antes de decisões, busca lugares solitários, ensina o Pai Nosso e ora no Getsêmani. Em vez de usar oração para evitar sofrimento, ele submete sua vontade ao Pai em meio à angústia.", "O Pai Nosso nasce num ambiente de piedade judaica, mas reorganiza desejos: nome de Deus, Reino, pão, perdão e livramento. A oração envolve corpo, relações e missão.", "Discernir não é receber toda impressão como ordem divina. É aprender a reconhecer o caráter de Deus, submeter desejos, examinar frutos e caminhar com a comunidade.", "Há tradições que enfatizam oração espontânea e outras que valorizam formas fixas. O Novo Testamento permite pedido sincero e palavras recebidas da tradição.", "A leitura pentecostal afirma oração fervorosa e direção do Espírito, mas exige exame bíblico, humildade, conselho e frutos compatíveis com Cristo."),
      module("espirito", "3. Espírito, dons e discernimento", "1 Coríntios 12–14 · Gálatas 5 · 1 João 4", "Como distinguir experiência espiritual, dom e manipulação?", "Paulo afirma diversidade de dons e um mesmo Espírito, ordena que profecias sejam avaliadas e coloca o amor como caminho indispensável. Gálatas fala de fruto, não só de manifestações.", "Corinto era uma comunidade dividida que precisava aprender a usar dons para edificação e não para status. O texto responde a culto desordenado e competição espiritual.", "O sinal decisivo não é intensidade emocional, mas se a prática confessa Cristo, serve o corpo, suporta exame e produz amor, domínio próprio e edificação.", "Continuísmo e cessacionismo divergem sobre a permanência de certos dons. Mesmo entre continuístas há debate sobre linguagem profética, autoridade e práticas de avaliação.", "A tradição pentecostal valoriza dons, oração e testemunho, ao mesmo tempo em que precisa cultivar ordem, prestação de contas e proteção contra abuso espiritual."),
    ], sources: ["Bíblia: Salmos; Evangelhos; cartas paulinas; 1 João.", "Walter Brueggemann, The Message of the Psalms.", "Gordon D. Fee, God’s Empowering Presence."]
  },
  "espirito-dons-fruto-missao": {
    title: "Espírito Santo: dons, fruto e missão", subtitle: "Promessa, poder, caráter, comunidade e missão em uma leitura pentecostal responsável.", orientation: "O Espírito não é apenas experiência individual. Nos textos bíblicos ele cria povo, testemunho, santidade, serviço e esperança.",
    modules: [
      module("promessa", "1. Promessa e presença do Espírito", "Joel 2 · Lucas 3–4 · João 14–16 · Atos 1–2", "O que Pentecostes cumpre e inaugura?", "Atos narra vento, fogo, línguas e anúncio público; Pedro relaciona a cena à promessa de Joel. João fala do Espírito como presença de Deus que ensina, testemunha e glorifica Cristo.", "Pentecostes acontece em Jerusalém, numa festa que reúne judeus de muitas regiões. A multiplicidade de línguas aponta para a comunicação pública do evangelho, não para elite espiritual.", "O Espírito capacita a igreja para testemunhar e forma uma comunidade onde barreiras étnicas e sociais são confrontadas. Poder é dado para serviço e missão.", "Cristãos discordam sobre a relação entre conversão, batismo no Espírito, evidências e experiências posteriores. A narrativa de Atos precisa ser lida junto às cartas, não isoladamente.", "A leitura pentecostal da IDB afirma a atualidade do Espírito e dos dons, buscando unir experiência, Escritura, santidade e missão."),
      module("dons", "2. Dons: não medalhas, mas serviço", "Romanos 12 · 1 Coríntios 12–14 · Efésios 4", "Para que os dons são dados?", "Paulo lista muitos dons e insiste que nenhum membro é dispensável. Línguas, profecia, cura, ensino, misericórdia e liderança aparecem como serviços para o corpo.", "As igrejas do primeiro século tinham conflitos de status. Por isso 1 Coríntios 12–14 discute simultaneamente manifestação, amor, inteligibilidade e ordem.", "Dom não prova maturidade isoladamente. O dom é uma responsabilidade recebida para edificar outros; o fruto mostra se o caráter acompanha o serviço.", "Há debate sobre listas fechadas, formas atuais de profecia e cura, e critérios de discernimento. A prática responsável não absolutiza relatos individuais.", "Pentecostalmente, espera-se a atuação de dons, mas sua avaliação deve ser bíblica, comunitária e orientada por amor, ordem e missão."),
      module("fruto-missao", "3. Fruto, santidade e envio", "Gálatas 5 · Atos 13 · Romanos 8", "Como experiência do Espírito se torna vida semelhante a Cristo?", "Gálatas contrapõe obras da carne e fruto do Espírito; Atos mostra comunidades em oração enviando missionários; Romanos fala do Espírito como vida, adoção e esperança.", "O fruto aparece dentro de comunidades reais, marcadas por conflito e desigualdade. Ele não é uma lista decorativa, mas alternativa prática à competição, violência e domínio.", "A missão não é só atravessar fronteiras geográficas. É testemunhar Cristo, servir pessoas, formar comunidades e praticar reconciliação onde a igreja já vive.", "Há risco de separar espiritualidade ‘poderosa’ de ética cotidiana. O Novo Testamento não permite essa divisão: o Espírito que concede dons também produz caráter.", "A ênfase pentecostal em poder recebe equilíbrio quando o poder é medido pela fidelidade a Cristo, compaixão, santidade e serviço."),
    ], sources: ["Bíblia: Joel; Lucas-Atos; Romanos; Gálatas; 1 Coríntios; Efésios.", "Gordon D. Fee, God’s Empowering Presence.", "Amos Yong, The Spirit Poured Out on All Flesh."]
  },
  "anjos-mensageiros-mundo-espiritual": {
    title: "Anjos: mensageiros, criaturas e discernimento", subtitle: "Uma leitura bíblica que leva o mundo espiritual a sério sem alimentar medo, culto a anjos ou especulação.", orientation: "Comece pelo ponto mais importante: anjos são criaturas e servos de Deus; eles não são alternativa para Cristo, objeto de culto ou atalho para conhecimento secreto.",
    modules: [
      module("palavras", "1. Mensageiros no Antigo Testamento", "Gênesis 16; 22; 28 · Êxodo 3; 23 · Isaías 6 · Daniel 7–12", "O que ‘anjo’ quer dizer e como as figuras variam?", "O termo hebraico mal'ak significa mensageiro. Os textos incluem mensageiros comuns, mensageiros celestes, querubins, serafins e a complexa figura do anjo do Senhor.", "A linguagem se desenvolve em mundos culturais do antigo Oriente e, no período pós-exílico, torna-se mais elaborada em Daniel e outras literaturas judaicas.", "O papel dos anjos é servir à ação de Deus: guardar, anunciar, interpretar visões e apontar para a santidade divina. Eles não são uma tecnologia espiritual disponível ao leitor.", "A identidade do anjo do Senhor é debatida: alguns textos aproximam mensageiro e presença divina; leituras cristãs posteriores por vezes o relacionam ao Logos. O texto pede cuidado, não resposta automática.", "A leitura pentecostal pode reconhecer conflito e assistência espiritual, mas deve submeter toda prática ao Deus revelado em Cristo e à Escritura."),
      module("cristo", "2. Anjos no ministério de Cristo e da igreja", "Mateus 1–4; 28 · Lucas 1–2; 22 · Atos 5; 8; 12 · Hebreus 1–2", "Por que Hebreus insiste que o Filho é maior que os anjos?", "Anjos anunciam nas narrativas de nascimento, servem Jesus, testemunham ressurreição e aparecem em Atos como mensageiros de libertação e direção. Hebreus, porém, contrapõe explicitamente Filho e anjos.", "O Novo Testamento nasce em ambiente judaico que valorizava seres celestes. A confissão cristã reorganiza esse mundo: Cristo é o mediador decisivo e os anjos são seus servos.", "O ponto não é colecionar aparições; é ver que a revelação culmina no Filho. Toda doutrina de anjos que obscurece Jesus perde o foco dos textos.", "Relatos de proteção, visões e intervenção são lidos de modos diferentes por tradições cristãs. O texto não autoriza transformar cada coincidência em decreto infalível.", "A espiritualidade pentecostal valoriza oração e discernimento, mas rejeita culto de anjos, invocação de seres criados e medo como método de vida cristã."),
      module("discernimento", "3. Mundo espiritual sem pânico nem fantasia", "Efésios 6 · Colossenses 1–2 · 1 João 4 · Apocalipse 12", "Como falar de conflito espiritual sem negar responsabilidade humana?", "Os textos falam de poderes, resistência, mentira, oração e armadura de Deus. Colossenses afirma que todas as coisas, visíveis e invisíveis, foram criadas por Cristo e estão submetidas a ele.", "Imagens de batalha pertencem a contextos de perseguição, idolatria e conflito de lealdade. Elas não substituem análise de injustiça, trauma, doença ou responsabilidade moral.", "Discernir espíritos inclui examinar mensagem, fruto, prática e confissão de Cristo. A pessoa não é dispensada de cuidado médico, aconselhamento responsável ou reparação quando necessário.", "Existe amplo debate sobre demonologia, hierarquias e linguagem de ‘territórios’. A Bíblia não oferece um mapa completo do mundo espiritual para ser usado como sistema técnico.", "A leitura pentecostal afirma oração, libertação e autoridade de Cristo com acompanhamento pastoral, ética, cuidado e rejeição de manipulação ou acusação precipitada."),
    ], sources: ["Bíblia: Gênesis; Êxodo; Isaías; Daniel; Evangelhos; Atos; Hebreus; cartas; Apocalipse.", "Serge-Thomas Bonino, Angels in Christian Theology (SAET, 2024).", "Susan R. Garrett, No Ordinary Angel."]
  },
  "trindade-pai-filho-espirito": {
    title: "Trindade: Pai, Filho e Espírito", subtitle: "Do texto bíblico à formulação histórica, com linguagem clara para não confundir unidade de Deus, pessoas e analogias.", orientation: "‘Trindade’ é uma palavra pós-bíblica usada para organizar o testemunho bíblico sobre o único Deus, o Pai, o Filho e o Espírito. A palavra não substitui os textos; ela tenta servi-los.",
    modules: [
      module("um-deus", "1. O único Deus e a história de Israel", "Deuteronômio 6 · Isaías 40–48 · 1 Coríntios 8", "Como a fé cristã preserva o monoteísmo de Israel?", "Israel confessa que o Senhor é um. Profetas confrontam ídolos e apresentam Deus como criador, libertador e único digno de adoração. Paulo retoma esse universo ao falar de um Deus e um Senhor.", "A confissão de um Deus nasce contra ambientes com muitos deuses e poderes. Ela não é detalhe abstrato: organiza culto, justiça e lealdade.", "Qualquer reflexão trinitária precisa começar aqui: não existem três deuses. A pergunta cristã surge porque os textos também atribuem ao Filho e ao Espírito ações e honra que pertencem a Deus.", "Leitores divergem sobre como textos do Antigo Testamento se relacionam à linguagem trinitária posterior. É inadequado impor uma fórmula conciliar a cada versículo; é igualmente inadequado ignorar o desenvolvimento canônico.", "A leitura pentecostal confessa o Deus único e vivo, cuja presença é experimentada pelo Espírito sem dividir sua glória entre seres criados."),
      module("pai-filho", "2. Pai e Filho: Jesus no centro da confissão", "João 1; 5; 17 · Filipenses 2 · Colossenses 1 · Hebreus 1", "O que os textos afirmam sobre Jesus antes de qualquer fórmula?", "João chama o Verbo de Deus e fala de sua relação com o Pai; Paulo descreve Cristo em linguagem de humilhação, exaltação e primazia; Hebreus o distingue dos anjos e o apresenta como expressão do ser de Deus.", "As primeiras comunidades adoravam, oravam e batizavam em torno de Jesus dentro de uma fé monoteísta. Essa prática forçou reflexão cuidadosa sobre sua identidade.", "O Filho não é apresentado como criatura elevada nem como simples máscara do Pai. Ao mesmo tempo, os Evangelhos preservam relação, envio, obediência e oração entre Pai e Filho.", "A história cristã debateu arianismo, subordinação e modalismo. Esses debates surgem porque é difícil afirmar ao mesmo tempo unidade divina, plena divindade do Filho e distinção real.", "A leitura pentecostal adora Jesus como Senhor e recebe sua mediação como centro da salvação, evitando reduzir Pai, Filho e Espírito a papéis alternados de uma única pessoa."),
      module("espirito", "3. O Espírito é força, pessoa ou ambos?", "João 14–16 · Atos 5 · Romanos 8 · 1 Coríntios 12", "Como os textos descrevem o Espírito sem reduzi-lo a energia impessoal?", "O Espírito ensina, testemunha, intercede, guia, pode ser entristecido e distribui dons. Atos 5 associa mentir ao Espírito a mentir a Deus; Romanos 8 fala de adoção e intercessão.", "A linguagem bíblica inclui vento, sopro, unção, fogo e água. São imagens do agir de Deus, mas convivem com ações pessoais atribuídas ao Espírito.", "O Espírito torna presente a obra do Pai por meio do Filho, incorpora a comunidade em Cristo e capacita missão, santidade e esperança.", "Há diferenças entre tradições sobre a processão do Espírito, o filioque e a linguagem de pessoa. O leitor deve entender o que cada termo tenta proteger, não apenas decorar rótulos.", "Pentecostalmente, a experiência do Espírito é real e atual, mas não autoriza tratá-lo como força controlável: seus dons e frutos orientam-se para Cristo e a edificação do corpo."),
      module("formulacao", "4. Da Bíblia a Niceia: por que a igreja criou termos?", "Mateus 28:19 · 2 Coríntios 13:13 · Credo Niceno", "Por que usar ‘essência’ e ‘pessoa’ se essas palavras não aparecem como fórmula pronta na Bíblia?", "Fórmulas triádicas aparecem em batismo, bênção e oração. Os concílios usaram linguagem técnica para responder a leituras que negavam a plena divindade do Filho ou apagavam a distinção entre Pai, Filho e Espírito.", "Niceia e Constantinopla pertencem a disputas históricas reais, marcadas por linguagem grega, política imperial e necessidade pastoral de definir quem a igreja adorava.", "A formulação clássica procura guardar quatro afirmações: há um Deus; Pai, Filho e Espírito são distintos; cada um é plenamente divino; Deus não é três deuses.", "Analogias como água, ovo ou sol podem ensinar algo limitado, mas frequentemente criam erros. Elas não devem substituir a linguagem bíblica e a humildade diante do mistério.", "A leitura pentecostal/IDB confessional afirma a Trindade histórica e chama a igreja a orar ao Pai, por meio do Filho, no poder do Espírito, sem reduzir Deus a explicação fácil."),
    ], sources: ["Bíblia: Deuteronômio; Isaías; Evangelhos; cartas; Hebreus.", "Lewis Ayres, Nicaea and Its Legacy.", "The Gospel Coalition, The Doctrine of the Trinity (perspectiva evangélica)."]
  },
  "o-que-e-ser-igreja": {
    title: "O que é ser Igreja?",
    subtitle: "Povo de Deus, corpo de Cristo e comunidade do Espírito: identidade, serviço, liderança, missão e responsabilidade.",
    orientation: "Um percurso aprofundado em quatorze módulos e setenta leituras em camadas. Leia a Igreja como realidade recebida de Deus e praticada por pessoas concretas; avance da convocação e das promessas bíblicas para corpo, ministérios, dons, autoridade, cuidado, missão e diálogo teológico.",
    modules: churchStudyModules,
    sources: churchStudySources,
  }
};

export const studyLayerLabels: Record<StudyLayerKey, string> = { texto: "O que o texto diz", contexto: "Contexto e cenário", significado: "O que isso significa", debate: "Debates e limites", pentecostal: "Leitura pentecostal/IDB" };
