export type GuidedArticle = {
  firstAnswer: string;
  story: string[];
  meaning: { label: string; text: string }[];
  peopleAndPlaces: { label: string; text: string }[];
  connections: string[];
  receptionOrDebate: string[];
  terms: { word: string; meaning: string }[];
};

export const apocryphaArticles: Record<string, GuidedArticle> = {
  tobit: {
    firstAnswer: "Tobias é uma história de família. Ela acompanha um pai piedoso, seu filho, uma jovem em sofrimento e uma viagem em que Deus cuida de pessoas comuns por meio de oração, amizade, coragem e hospitalidade.",
    story: ["Tobit, israelita que vive longe de sua terra em Nínive, continua ajudando os pobres e enterrando mortos, mesmo quando isso lhe traz perigo. Ele perde a visão e entra em sofrimento.", "Ao mesmo tempo, Sara, jovem de outra cidade, sofre porque seus casamentos terminaram tragicamente. Tobit manda seu filho Tobias fazer uma viagem para recuperar uma quantia guardada. O companheiro de viagem é Rafael, um anjo que se apresenta como homem.", "Na viagem, Tobias encontra Sara, casa-se com ela e volta para casa. Rafael ajuda a curar Tobit. O desfecho mostra uma família restaurada, mas não vende uma vida sem dor: ela aprendeu a atravessar dor, espera e retorno."],
    meaning: [{ label: "O que o livro quer ensinar", text: "Fé não aparece apenas em milagres espetaculares. Ela aparece no cuidado com quem sofre, na generosidade, na oração e em decisões familiares." }, { label: "Por que a viagem importa", text: "A viagem junta duas famílias feridas. Ela funciona como imagem de amadurecimento: Tobias sai dependente do pai e volta capaz de formar uma nova casa." }],
    peopleAndPlaces: [{ label: "Tobit", text: "Pai fiel, cuja dor e cegueira mostram que uma pessoa piedosa também pode sofrer." }, { label: "Tobias e Sara", text: "O casal aprende a iniciar uma vida comum com oração e responsabilidade, não apenas com medo." }, { label: "Rafael", text: "Anjo cujo nome significa 'Deus cura'; ele mostra cuidado divino agindo de modo discreto." }, { label: "Nínive e Ecbátana", text: "Cidades fora de Judá. O cenário recorda que muitos judeus viviam espalhados por outros impérios." }],
    connections: ["Dialoga com Jó porque ambos enfrentam sofrimento sem uma resposta simples.", "Dialoga com Gênesis e Rute pelo tema de família, casamento e continuidade de uma casa.", "Ajuda a perceber práticas judaicas da diáspora que também formam o pano de fundo do Novo Testamento."],
    receptionOrDebate: ["Católicos e ortodoxos o recebem como Escritura. Bíblias protestantes históricas frequentemente o imprimiram entre os apócrifos, como leitura útil, mas não normativa para doutrina.", "A história é ambientada no mundo assírio, mas os estudiosos normalmente a leem como narrativa sapiencial posterior, feita para ensinar identidade e fidelidade; não como uma biografia verificável em todos os detalhes."],
    terms: [{ word: "Diáspora", meaning: "Vida de um povo fora de sua terra de origem." }, { word: "Esmola", meaning: "Ajuda concreta a quem precisa; no livro, é sinal de justiça e misericórdia." }, { word: "Anjo", meaning: "Mensageiro de Deus; Rafael guia a história sem substituir as escolhas humanas." }]
  },
  judith: {
    firstAnswer: "Judite é uma narrativa de coragem. Uma viúva usa inteligência, oração e risco pessoal para impedir que seu povo seja destruído por um exército invasor.",
    story: ["Um grande exército cerca Betúlia. Os moradores entram em pânico e pensam em se render se Deus não agir rapidamente.", "Judite, viúva respeitada, critica a ideia de colocar Deus contra o relógio. Ela se prepara, sai da cidade e entra no acampamento inimigo.", "Com estratégia, ela se aproxima do general Holofernes. Quando ele fica vulnerável, Judite o mata, volta à cidade e o exército inimigo se desorganiza. O povo então se defende."],
    meaning: [{ label: "O que a história retrata", text: "O livro inverte uma expectativa comum: uma mulher viúva, sem exército, se torna a figura decisiva da libertação." }, { label: "A pergunta maior", text: "Judite pergunta como um povo vive quando está cercado por forças maiores. Sua resposta não é passividade, mas confiança que também pensa, planeja e age." }],
    peopleAndPlaces: [{ label: "Judite", text: "Viúva rica e devota, descrita como estrategista e intercessora." }, { label: "Holofernes", text: "General que representa poder imperial arrogante." }, { label: "Betúlia", text: "Cidade simbólica; sua geografia difícil de identificar indica que o livro trabalha teologicamente a memória da ameaça." }],
    connections: ["Lembra Jael, que derrota Sísera em Juízes 4–5.", "Lembra Ester, outra mulher que arrisca a própria segurança para proteger seu povo.", "Conversa com os profetas ao criticar a idolatria de poder e a falsa segurança militar."],
    receptionOrDebate: ["O livro é canônico nas tradições católica e ortodoxa e é lido como apócrifo em tradições protestantes.", "Nomes de reis e locais não encaixam numa cronologia simples. Isso não torna o livro sem valor; indica que ele funciona como novela teológica, usando um cenário de crise para ensinar fidelidade."],
    terms: [{ word: "Viúva", meaning: "Mulher sem marido; no mundo antigo podia ser vulnerável, mas Judite também possui recursos e autoridade." }, { word: "Jejum", meaning: "Prática de oração e busca de direção, muito presente no livro." }, { word: "Novela teológica", meaning: "Narrativa construída para comunicar fé e identidade, não apenas registrar acontecimentos em ordem documental." }]
  },
  wisdom: {
    firstAnswer: "Sabedoria de Salomão é um livro de reflexão. Ele pergunta por que pessoas justas sofrem, o que é sabedoria e por que o poder precisa ser responsável diante de Deus.",
    story: ["O livro não conta uma aventura única. Ele reúne discursos e poemas colocados na voz literária de Salomão.", "Primeiro, contrasta o caminho de quem busca a justiça com o de quem vive apenas para o próprio prazer e poder.", "Depois, apresenta a Sabedoria como dom de Deus e relembra o êxodo para mostrar que o Deus de Israel age na história contra opressão e idolatria."],
    meaning: [{ label: "O que quer dizer por 'sabedoria'", text: "Não é ser esperto. É aprender a ver a vida a partir da justiça de Deus e ordenar escolhas, governo e desejos por esse critério." }, { label: "Por que fala de morte", text: "O livro fortalece pessoas justas que sofrem: a morte não tem a última palavra sobre uma vida vivida diante de Deus." }],
    peopleAndPlaces: [{ label: "Salomão", text: "É a voz literária do livro, não uma prova automática de autoria histórica do rei." }, { label: "Justos e ímpios", text: "São tipos morais: pessoas e sociedades que usam ou recusam justiça." }, { label: "Egito", text: "No relato do êxodo, simboliza um poder que oprime e transforma a criação em objeto de domínio." }],
    connections: ["Aproxima-se de Provérbios e Eclesiastes pela busca de sabedoria.", "Retoma o êxodo, como Salmos e profetas fazem.", "Ajuda a iluminar palavras do Novo Testamento sobre Palavra, luz, justiça e esperança, mas não deve ser tratado como se já fosse um Evangelho."],
    receptionOrDebate: ["É canônico para católicos e ortodoxos; protestantes o usam como literatura apócrifa importante para o período entre Testamentos.", "Foi escrito em grego e mostra diálogo com o mundo helenístico. Isso não o torna menos judaico; mostra judeus falando sua fé em uma cultura ampla."],
    terms: [{ word: "Imortalidade", meaning: "Esperança de que a vida justa permanece diante de Deus, não simples fuga do corpo ou da história." }, { word: "Idolatria", meaning: "Transformar coisas criadas, imagens ou poder em aquilo que recebe a confiança final." }, { word: "Helenístico", meaning: "Relacionado ao mundo de língua e cultura grega depois de Alexandre." }]
  },
  sirach: {
    firstAnswer: "Eclesiástico, também chamado Ben Sira, é um livro para aprender a viver. Ele fala de amizade, trabalho, fala, família, dinheiro, culto e respeito aos mais velhos.",
    story: ["Ben Sira reúne ensinamentos para jovens que desejam viver com discernimento. Em vez de uma única história, o livro oferece conselhos, poemas e orações.", "Ele afirma que a sabedoria vem de Deus e está ligada à Torá, à prática da justiça e à vida comunitária.", "No fim, percorre a história de Israel por meio de antepassados: Abraão, Moisés, Davi, Elias e muitos outros. Assim, aprender a viver hoje inclui lembrar quem veio antes."],
    meaning: [{ label: "O que é sabedoria aqui", text: "É aprender a agir bem no cotidiano: falar na hora certa, escolher amigos, ser justo no trabalho e reverenciar a Deus." }, { label: "O que o livro retrata", text: "Uma comunidade judaica que quer preservar sua identidade e formação moral num mundo culturalmente diverso." }],
    peopleAndPlaces: [{ label: "Ben Sira", text: "Mestre judeu de Jerusalém, associado à versão hebraica original do livro." }, { label: "O neto tradutor", text: "A tradução grega feita por seu neto mostra como os livros circulavam entre comunidades de língua diferente." }, { label: "Jerusalém e o templo", text: "O culto é importante, mas a vida justa também inclui casa, praça, trabalho e relações." }],
    connections: ["Dialoga com Provérbios por suas máximas e com Jó por sua pergunta sobre sofrimento.", "Seu louvor aos antepassados cria uma ponte com a memória histórica de Israel.", "Aparece no pano de fundo linguístico e moral de muitos debates do período do Novo Testamento."],
    receptionOrDebate: ["É canônico nas tradições católica e ortodoxa; protestantes o classificam entre os apócrifos.", "Fragmentos hebraicos encontrados em diferentes lugares lembram que a transmissão de um livro pode existir em mais de uma língua e forma."],
    terms: [{ word: "Torá", meaning: "Instrução de Deus para a vida do povo; não apenas uma lista de regras." }, { word: "Máxima", meaning: "Frase breve que concentra um conselho de vida." }, { word: "Antepassados", meaning: "Figuras do passado lembradas para formar identidade e responsabilidade no presente." }]
  },
  baruch: {
    firstAnswer: "Baruc reúne textos ligados à memória de Jeremias e do exílio. Ele ensina um povo ferido a confessar erros, lembrar sua história e reaprender a esperar.",
    story: ["A primeira parte coloca uma confissão nos lábios de judeus que vivem as consequências da queda de Jerusalém.", "Depois, uma grande meditação procura a sabedoria: ela não é encontrada no poder dos impérios, mas no caminho ensinado por Deus.", "A Carta de Jeremias ridiculariza ídolos feitos por mãos humanas para ensinar que eles não têm vida nem poder próprio."],
    meaning: [{ label: "O que o livro quer dizer", text: "Quando uma comunidade perde terra, templo e segurança, ela precisa perguntar como lembrar de Deus sem fingir que nada aconteceu." }, { label: "Por que falar contra ídolos", text: "O alvo não é apenas uma estátua. É a confiança em objetos e poderes incapazes de salvar ou responder." }],
    peopleAndPlaces: [{ label: "Baruc", text: "Escriba associado a Jeremias; seu nome dá autoridade literária ao conjunto." }, { label: "Jerusalém", text: "Cidade ferida cuja destruição organiza a memória do livro." }, { label: "Babilônia", text: "Lugar de exílio e também imagem de vida sob poder estrangeiro." }],
    connections: ["Retoma Jeremias, Lamentações e Deuteronômio no vocabulário de confissão e retorno.", "Conversa com Provérbios e Ben Sira pela busca de sabedoria.", "Ajuda a compreender por que o exílio é decisivo para livros posteriores."],
    receptionOrDebate: ["Baruc faz parte do cânon católico; coleções ortodoxas podem organizar seus textos de modos diferentes. Em Bíblias protestantes, é geralmente apócrifo.", "A ligação com o secretário histórico de Jeremias é uma moldura literária. Estudar essa moldura é perguntar como comunidades posteriores receberam e renovaram Jeremias."],
    terms: [{ word: "Exílio", meaning: "Vida forçada ou vivida fora da terra e de suas instituições habituais." }, { word: "Confissão", meaning: "Reconhecer coletivamente uma ruptura e buscar mudança, não apenas sentir culpa." }, { word: "Ídolo", meaning: "Algo feito ou elevado por pessoas para ocupar o lugar de confiança final." }]
  },
  "maccabees-1": {
    firstAnswer: "1 Macabeus conta uma crise política real do século II a.C.: tentativas de controlar práticas judaicas, a revolta de uma família e o surgimento de um novo governo judeu.",
    story: ["O rei selêucida Antíoco IV interfere em Jerusalém e profana o templo. Parte da população aceita a mudança; outra parte resiste.", "Matatias inicia uma revolta. Depois de sua morte, seu filho Judas, chamado Macabeu, conduz batalhas e recupera o templo. Essa dedicação está ligada à origem de Hanukkah.", "A história continua com os irmãos de Judas e com a ascensão da dinastia hasmoneia. O livro celebra sua luta, mas também mostra que religião, família e poder político se misturam."],
    meaning: [{ label: "Por que este livro importa", text: "Ele explica o mundo imediatamente anterior a Jesus: templo, partidos, memória de perseguição, esperança de libertação e tensão com governos estrangeiros." }, { label: "O que retrata", text: "Um povo discutindo até onde pode se adaptar a uma cultura dominante sem perder sua identidade." }],
    peopleAndPlaces: [{ label: "Antíoco IV", text: "Rei selêucida cuja política desencadeia a crise narrada." }, { label: "Matatias e Judas Macabeu", text: "Pai e filho ligados à resistência e à recuperação do templo." }, { label: "Jerusalém", text: "Centro religioso e político; o conflito pelo templo é o centro da narrativa." }],
    connections: ["Ajuda a situar Daniel 7–12, especialmente as visões de perseguição e profanação.", "Explica Hanukkah, festa mencionada em João 10.22.", "Forma parte do pano de fundo para os grupos judaicos e expectativas do tempo de Jesus."],
    receptionOrDebate: ["Católicos e ortodoxos o recebem como Escritura; protestantes o leem como apócrifo histórico relevante.", "O livro tem objetivo favorável à dinastia hasmoneia. Por isso, é fonte importante, mas não neutra; história sempre pergunta quem conta e por quê."],
    terms: [{ word: "Selêucida", meaning: "Dinastia que governou parte do antigo império de Alexandre, incluindo a Judeia em certo período." }, { word: "Hasmoneu", meaning: "Família que liderou a revolta e depois governou a Judeia." }, { word: "Hanukkah", meaning: "Festa judaica da dedicação do templo após sua recuperação." }]
  },
  "maccabees-2": {
    firstAnswer: "2 Macabeus conta parte da mesma crise de 1 Macabeus, mas por outra lente. Ele destaca o templo, a oração, pessoas que preferem morrer a abandonar sua fé e a esperança de ressurreição.",
    story: ["O livro começa com cartas que convidam judeus de fora da Judeia a celebrar a dedicação do templo.", "Em seguida, narra conflitos em Jerusalém e a perseguição de Antíoco IV. Sacerdotes, mães e jovens aparecem diante de escolhas duras.", "O relato dos sete irmãos e sua mãe se tornou uma das cenas mais marcantes: eles se recusam a violar sua fé e afirmam esperança de vida restaurada por Deus."],
    meaning: [{ label: "O que este livro está dizendo", text: "A fidelidade pode custar caro. O livro pergunta se o corpo, a memória e a justiça importam quando um governo tenta controlar a consciência." }, { label: "Por que fala de ressurreição", text: "A esperança não é uma desculpa para ignorar a violência. É a afirmação de que o perseguidor não possui a palavra final sobre quem morreu fazendo o bem." }],
    peopleAndPlaces: [{ label: "Judas Macabeu", text: "Líder militar, mas o livro dá destaque também a sacerdotes, mães e mártires." }, { label: "Sete irmãos e sua mãe", text: "Figuras de resistência religiosa e esperança." }, { label: "Templo de Jerusalém", text: "Lugar central de culto, memória e conflito político." }],
    connections: ["Conversa com Daniel 12 na esperança de ressurreição.", "Ajuda a entender a linguagem de martírio que aparece no judaísmo e cristianismo posteriores.", "Completa e também corrige a impressão de que 1 Macabeus é a única versão da revolta."],
    receptionOrDebate: ["É canônico para católicos e ortodoxos; protestantes geralmente o colocam nos apócrifos.", "Não deve ser usado como cópia de 1 Macabeus: os dois textos selecionam episódios e teologias diferentes. A diferença ensina o leitor a comparar fontes."],
    terms: [{ word: "Martírio", meaning: "Morte ou sofrimento aceito por fidelidade a uma convicção religiosa; não é busca de sofrimento por si só." }, { word: "Ressurreição", meaning: "Esperança de que Deus restaura a vida e faz justiça, especialmente desenvolvida em alguns textos tardios." }, { word: "Dedicação", meaning: "Rededicação do templo após sua profanação." }]
  },
  "greek-additions": {
    firstAnswer: "Os acréscimos gregos são partes de Ester e Daniel preservadas em grego que nem toda Bíblia coloca no mesmo lugar. Eles acrescentam orações, personagens e cenas que ajudam o leitor a enxergar o que estava implícito.",
    story: ["Em Ester, as versões gregas incluem orações de Ester e Mardoqueu e tornam mais explícita a presença de Deus numa narrativa que, em hebraico, quase não menciona seu nome.", "Em Daniel, a Oração de Azarias aparece dentro da fornalha; Susana conta a defesa de uma mulher injustamente acusada; Bel e o Dragão ridicularizam ídolos que parecem vivos, mas são manipulados.", "Cada acréscimo amplia um modo de ler: oração no perigo, justiça diante de abuso e crítica à idolatria."],
    meaning: [{ label: "Por que existem versões diferentes", text: "Antes de a imprensa fixar Bíblias padronizadas, livros podiam circular em hebraico, aramaico ou grego e receber traduções, expansões e arranjos diferentes." }, { label: "O que retratam", text: "Leitores antigos não queriam só preservar palavras; também queriam tornar visível a oração, a justiça e a ação de Deus que reconheciam na história." }],
    peopleAndPlaces: [{ label: "Ester e Mardoqueu", text: "Personagens da diáspora judaica na corte persa." }, { label: "Susana", text: "Mulher acusada injustamente por homens poderosos; Daniel intervém com interrogatório cuidadoso." }, { label: "Azarias", text: "Jovem que ora na fornalha com seus companheiros." }],
    connections: ["Ester grego ilumina como a oração foi recebida por leitores posteriores.", "Susana conversa com temas bíblicos de falso testemunho e justiça.", "Bel e o Dragão conversa com profetas que criticam ídolos fabricados."],
    receptionOrDebate: ["Católicos e ortodoxos incluem essas partes em Ester e Daniel; protestantes costumam imprimi-las em seção apócrifa ou não as incluem.", "A diferença não significa que uma comunidade 'escondeu' texto; significa que tradições herdaram e organizaram coleções diferentes."],
    terms: [{ word: "Septuaginta", meaning: "Nome usado para a ampla tradição grega das Escrituras judaicas; não é uma única edição idêntica." }, { word: "Versão", meaning: "Forma de um texto em outra língua ou arranjo; pode preservar diferenças importantes." }, { word: "Falso testemunho", meaning: "Acusação mentirosa usada para prejudicar alguém; tema central de Susana." }]
  },
  anagignoskomena: {
    firstAnswer: "Este grupo reúne textos que algumas tradições ortodoxas leem na igreja e em casa, embora nem todas as Bíblias os organizem da mesma maneira. Eles mostram que uma Bíblia antiga não era sempre uma lista idêntica em todo lugar.",
    story: ["O Salmo 151 dá voz a Davi antes de enfrentar Golias: ele é o menor da família, mas Deus o escolhe.", "A Oração de Manassés coloca arrependimento nos lábios de um rei lembrado por sua maldade, insistindo que o perdão ainda é possível.", "3 Macabeus narra uma crise de perseguição no Egito ptolomaico, não a mesma revolta macabeia de 1 e 2 Macabeus."],
    meaning: [{ label: "O que estes textos ajudam a ver", text: "A leitura bíblica antiga incluía oração, cântico, confissão e memória de perseguição além de uma única lista fechada." }, { label: "Por que são reunidos", text: "Eles permitem comparar como diferentes igrejas formaram coleções e usos litúrgicos." }],
    peopleAndPlaces: [{ label: "Davi", text: "No Salmo 151, aparece como jovem improvável escolhido por Deus." }, { label: "Manassés", text: "Rei de Judá cuja figura se torna exemplo de arrependimento." }, { label: "Alexandria", text: "Cenário importante de 3 Macabeus e da vida judaica no Egito helenístico." }],
    connections: ["O Salmo 151 relê 1 Samuel 16–17.", "A oração de Manassés conversa com 2 Crônicas 33 e com salmos penitenciais.", "3 Macabeus amplia a história judaica da diáspora no Egito."],
    receptionOrDebate: ["O termo grego anagignoskomena significa aproximadamente 'textos lidos'. Seu lugar exato varia entre igrejas ortodoxas e edições bíblicas.", "Em vez de perguntar apenas 'está ou não está?', o leitor iniciante pode perguntar: onde foi lido, por quem, em que língua e com que finalidade?"],
    terms: [{ word: "Liturgia", meaning: "Culto público e suas leituras, orações e cânticos." }, { word: "Penitência", meaning: "Reconhecimento de erro e busca de mudança diante de Deus." }, { word: "Ptolemaico", meaning: "Relacionado aos governantes gregos do Egito depois de Alexandre." }]
  },
  "enoch-jubilees": {
    firstAnswer: "1 Enoque e Jubileus são livros judaicos antigos que ajudam a entender o mundo de ideias do período do Segundo Templo. Eles falam de anjos, calendário, justiça, criação e juízo, mas não têm o mesmo lugar em todas as Bíblias.",
    story: ["1 Enoque reúne várias obras. Ele amplia a breve história de seres celestiais em Gênesis 6, fala de anjos rebeldes, viagens visionárias, julgamento e esperança de justiça.", "Jubileus reconta Gênesis e Êxodo dentro de um calendário rigoroso. Ele organiza a história em períodos chamados jubileus e enfatiza aliança, festas e separação de práticas consideradas impuras.", "Os dois livros mostram leitores judeus imaginando como a história humana se conecta ao mundo celestial e à ordem da criação."],
    meaning: [{ label: "O que eles retratam", text: "Um judaísmo plural, preocupado em explicar de onde vem o mal, como o tempo deve ser vivido e por que a justiça de Deus pode parecer demorada." }, { label: "Por que importam para a Bíblia", text: "Eles não substituem Gênesis ou Daniel, mas mostram como judeus antigos continuaram pensando as perguntas abertas por esses livros." }],
    peopleAndPlaces: [{ label: "Enoque", text: "Antepassado mencionado brevemente em Gênesis 5; o livro usa seu nome como voz de revelação." }, { label: "Moisés", text: "Em Jubileus, recebe uma história reorganizada em torno de calendário e aliança." }, { label: "Qumran", text: "Lugar onde fragmentos de 1 Enoque e Jubileus mostram sua circulação entre comunidades judaicas." }],
    connections: ["1 Enoque conversa com Gênesis 5–6 e é citado em Judas 14–15.", "Jubileus reconta Gênesis e Êxodo, ensinando como uma comunidade pode reler seus textos fundadores.", "Ambos ajudam a situar imagens de anjos, juízo e calendário presentes no mundo do Novo Testamento."],
    receptionOrDebate: ["1 Enoque é canônico na Igreja Ortodoxa Etíope; os dois estão fora dos cânones católico romano e protestante. Mesmo assim, são fontes centrais para estudar literatura judaica antiga.", "Atribuir um livro a Enoque ou Moisés é uma forma literária de falar com autoridade antiga; isso não exige concluir que a pessoa histórica escreveu cada linha."],
    terms: [{ word: "Pseudepígrafo", meaning: "Obra escrita em nome de uma figura antiga; descreve uma prática literária, não uma acusação automática de fraude." }, { word: "Segundo Templo", meaning: "Período entre a reconstrução do templo após o exílio e sua destruição pelos romanos em 70 d.C." }, { word: "Jubileu", meaning: "Período de tempo usado para organizar a história e o calendário no livro de Jubileus." }]
  }
};

export const historyArticles: Record<string, GuidedArticle> = {
  worlds: { firstAnswer: "Antes de Israel existir como povo, já havia grandes cidades, reis, rotas comerciais, rios e religiões no antigo Oriente. Gênesis fala desse mundo para responder quem é Deus, quem é o ser humano e como a violência entrou na história.", story: ["As histórias de criação, dilúvio, Babel e ancestrais não formam uma cronologia moderna. Elas apresentam o mundo como criação de Deus e mostram famílias tentando viver depois de rupturas, fome e migração.", "Abraão, Isaque, Jacó e José se movem entre Canaã, Egito e Mesopotâmia. As viagens fazem o leitor ver que fé bíblica nasce no caminho, não em um território sem conflitos."], meaning: [{ label: "Por que isto importa", text: "Você não começa a Bíblia entendendo datas; começa entendendo a pergunta: que tipo de mundo Deus criou e o que pessoas fazem com ele?" }, { label: "O que muda na leitura", text: "Cidades como Babel não são apenas pontos no mapa. Elas representam poder que tenta criar unidade sem Deus e sem justiça." }], peopleAndPlaces: [{ label: "Abraão e Sara", text: "Casal chamado a deixar sua terra e formar uma família de bênção." }, { label: "José", text: "Filho vendido que se torna administrador no Egito e salva sua família da fome." }, { label: "Mesopotâmia, Canaã e Egito", text: "Três grandes paisagens que explicam migração, comércio e sobrevivência nas narrativas." }], connections: ["Leia Gênesis 1–11 para perguntas sobre criação e ruptura.", "Leia Gênesis 12–50 para a história das famílias ancestrais.", "Use o atlas para enxergar por que rios e rotas eram tão importantes."], receptionOrDebate: ["Arqueologia ajuda a conhecer o mundo de cidades e rotas, mas não consegue testar cada cena de Gênesis como se fosse uma filmagem.", "O leitor pode receber o texto como Escritura e, ao mesmo tempo, aprender a perguntar como sua composição comunica verdade literária e teológica."], terms: [{ word: "Patriarca", meaning: "Nome tradicional para os ancestrais Abraão, Isaque e Jacó." }, { word: "Aliança", meaning: "Relação comprometida entre Deus e um povo, com promessa e responsabilidade." }, { word: "Oriente antigo", meaning: "Região de Egito, Levante e Mesopotâmia, onde muitas histórias bíblicas se passam." }] },
  exodus: { firstAnswer: "O êxodo é a grande memória de libertação de Israel: Deus ouve um povo escravizado, o conduz para fora do Egito e o chama a viver como comunidade de aliança.", story: ["Moisés nasce num tempo em que faraó tenta controlar a população israelita. Ele foge, encontra Deus no deserto e retorna para confrontar o poder egípcio.", "Depois das pragas e da saída, o povo atravessa o mar, mas descobre que ser livre é mais difícil do que sair de um lugar. No Sinai, recebe instruções para organizar culto, justiça e vida comum.", "A jornada pelo deserto mostra reclamação, medo, provisão e aprendizado. A terra prometida aparece como destino, mas também como responsabilidade."], meaning: [{ label: "O que o êxodo quer ensinar", text: "Deus não ignora opressão. Libertação, adoração e justiça pertencem à mesma história." }, { label: "Por que a lei vem depois", text: "A instrução não é um preço para ser liberto; ela é um caminho para pessoas livres não reconstruírem a opressão entre si." }], peopleAndPlaces: [{ label: "Moisés", text: "Mediador e líder que enfrenta faraó, aprende a depender de Deus e conduz um povo difícil." }, { label: "Faraó", text: "Imagem de poder que usa pessoas como recursos descartáveis." }, { label: "Egito, Sinai e Canaã", text: "Pontos da rota entre escravidão, formação do povo e promessa de terra." }], connections: ["Êxodo é lembrado nos Salmos, nos profetas e nos Evangelhos.", "A Páscoa judaica recorda a libertação; os relatos da última ceia de Jesus dialogam com essa memória.", "Leis sobre estrangeiro, pobre e descanso ganham força quando lembramos que Israel foi escravo."], receptionOrDebate: ["Os estudiosos discutem data, rota e escala do êxodo. A Bíblia, porém, usa a memória de libertação como centro de identidade e ética.", "Não é necessário escolher entre estudar as evidências e ouvir a mensagem do texto; são camadas diferentes de pergunta."], terms: [{ word: "Êxodo", meaning: "Saída; nome da libertação do Egito e do livro que a narra." }, { word: "Páscoa", meaning: "Festa que recorda a libertação do Egito." }, { word: "Sinai", meaning: "Região associada à aliança e à entrega da instrução a Israel." }] },
  judges: { firstAnswer: "Depois da entrada na terra, Israel não aparece como um país unido. Juízes mostra aldeias e tribos em conflito, com líderes locais que surgem em tempos de crise.", story: ["O livro repete um ciclo: o povo se afasta, sofre opressão, clama, recebe um libertador e volta a se perder. Débora, Gideão, Jefté e Sansão são diferentes entre si e nem sempre exemplares.", "Rute se passa no mesmo horizonte, mas olha para uma família comum: fome, migração, perda, amizade entre mulheres e cuidado com uma viúva.", "Juntos, os livros mostram que a história bíblica não é feita apenas de reis e guerras; casas e campos também carregam a memória de Deus."], meaning: [{ label: "O que o período retrata", text: "Falta de unidade, violência e busca de liderança. A frase 'cada um fazia o que parecia certo' é diagnóstico, não elogio." }, { label: "Por que Rute importa", text: "Rute oferece uma resposta pequena e humana à violência de Juízes: lealdade, acolhimento do estrangeiro e cuidado familiar." }], peopleAndPlaces: [{ label: "Débora", text: "Profetisa e juíza que lidera Israel em conflito." }, { label: "Sansão", text: "Libertador de grande força, cuja vida mostra que poder sem maturidade pode destruir." }, { label: "Belém e Moabe", text: "Lugares de Rute que introduzem migração e acolhimento na história de Davi." }], connections: ["Juízes prepara a pergunta que levará à monarquia em Samuel.", "Rute prepara a genealogia de Davi e, mais tarde, de Jesus em Mateus.", "O período ensina a ler lideranças bíblicas sem transformar cada líder em modelo moral simples."], receptionOrDebate: ["Os ciclos de Juízes parecem organizar tradições de forma literária; não devem ser automaticamente somados como uma linha de datas exata.", "A arqueologia ajuda a conhecer aldeias e mudanças de povoamento, mas não identifica todos os personagens do livro."], terms: [{ word: "Juiz", meaning: "No livro, é libertador ou líder local, não apenas alguém que decide processos legais." }, { word: "Tribo", meaning: "Grupo de parentesco e território dentro de Israel." }, { word: "Levirato", meaning: "Prática familiar ligada à continuidade de uma casa; aparece no contexto de Rute." }] },
  monarchy: { firstAnswer: "A monarquia começa quando Israel pede um rei. Samuel, Reis e Crônicas perguntam se ter um centro político pode ajudar o povo sem substituir Deus.", story: ["Saul se torna o primeiro rei, mas suas decisões entram em conflito com a liderança profética de Samuel.", "Davi unifica tribos, conquista Jerusalém e recebe uma promessa de dinastia. Sua história inclui fé, poesia, abuso de poder, arrependimento e violência familiar.", "Salomão constrói o templo e amplia relações políticas, mas seu governo também cobra trabalho e tributos. Depois de sua morte, o reino se divide."], meaning: [{ label: "O que o período ensina", text: "Poder político pode proteger e organizar, mas também pode explorar. A Bíblia não apresenta reis como salvadores automáticos." }, { label: "Por que Jerusalém importa", text: "A cidade vira centro de governo e culto, mas profetas lembram que Deus não cabe em palácio ou templo." }], peopleAndPlaces: [{ label: "Saul", text: "Primeiro rei, marcado pela insegurança e pelo conflito com Samuel." }, { label: "Davi", text: "Rei central na memória bíblica, mas também homem de falhas graves." }, { label: "Salomão", text: "Filho de Davi, lembrado por sabedoria, templo e administração pesada." }, { label: "Jerusalém", text: "Cidade de Davi, templo e debates sobre culto e poder." }], connections: ["2 Samuel 7 sustenta expectativas posteriores sobre um descendente de Davi.", "Salmos são ligados à memória davídica, mas precisam ser lidos como poesia e oração.", "Os Evangelhos chamam Jesus de 'Filho de Davi' para dialogar com essa esperança."], receptionOrDebate: ["Inscrições como a Estela de Tel Dan ajudam a confirmar a memória de uma 'casa de Davi', mas não resolvem todos os debates sobre o tamanho do reino.", "Samuel, Reis e Crônicas contam a monarquia por perspectivas distintas. Comparar as versões é parte da leitura enciclopédica."], terms: [{ word: "Monarquia", meaning: "Governo de um rei ou rainha." }, { word: "Dinastia", meaning: "Família que mantém direito de governar ao longo das gerações." }, { word: "Templo", meaning: "Centro de culto em Jerusalém; para a Bíblia, seu sentido depende também de justiça e fidelidade." }] },
  divided: { firstAnswer: "Depois de Salomão, o reino se divide: Israel ao norte e Judá ao sul. Os dois vivem entre escolhas internas e a pressão crescente da Assíria.", story: ["Israel tem capital em Samaria e várias dinastias. Judá permanece ligado à casa de Davi em Jerusalém.", "Profetas como Amós e Oséias falam no norte; Isaías e Miqueias falam principalmente em Judá. Eles denunciam injustiça social, culto vazio e alianças políticas sem discernimento.", "A Assíria conquista Samaria em 722 a.C. e deporta parte da população. Judá sobrevive por um tempo, mas fica vulnerável."], meaning: [{ label: "O que os profetas fazem", text: "Eles não são apenas pessoas que adivinham o futuro. Eles leem o presente diante de Deus e denunciam sistemas que machucam pessoas." }, { label: "Por que a Assíria aparece tanto", text: "Era a grande potência militar. Sua presença muda impostos, fronteiras, migrações e medo cotidiano." }], peopleAndPlaces: [{ label: "Amós", text: "Profeta que denuncia riqueza construída sobre exploração dos pobres." }, { label: "Oséias", text: "Profeta que usa imagens de casamento e infidelidade para falar da relação entre Deus e Israel." }, { label: "Samaria", text: "Capital do reino do norte, conquistada pela Assíria." }, { label: "Assíria", text: "Império com exército e administração que dominou grande parte do Levante." }], connections: ["Ajuda a entender por que livros proféticos falam de justiça social e idolatria juntos.", "Prepara a crise que Judá viverá depois com a Babilônia.", "Mostra que a história bíblica inclui povos vizinhos e impérios, não apenas Israel."], receptionOrDebate: ["Fontes assírias registram campanhas e reis, enquanto a Bíblia interpreta esses acontecimentos moral e teologicamente.", "O leitor ganha quando não força uma camada a fazer o trabalho da outra: inscrição imperial não substitui profeta, e profeta não é relatório militar."], terms: [{ word: "Profeta", meaning: "Pessoa chamada a falar a palavra de Deus para o presente de sua comunidade." }, { word: "Deportação", meaning: "Deslocamento forçado de populações pelo poder conquistador." }, { word: "Aliança política", meaning: "Acordo entre governos para buscar proteção ou vantagem." }] },
  "judah-babylon": { firstAnswer: "Judá perde Jerusalém e o templo para a Babilônia. O exílio obriga o povo a perguntar como continuar sendo povo de Deus sem rei, terra livre e centro de culto.", story: ["Depois da queda de Samaria, Judá vive entre Assíria, Egito e Babilônia. Reis fazem alianças arriscadas, e profetas como Jeremias alertam que Jerusalém não está protegida só por ter um templo.", "Em 586 a.C., os babilônios destroem Jerusalém e levam parte da população para o exílio. Lamentações dá voz ao luto; Ezequiel fala com exilados; Isaías 40–55 anuncia consolo e retorno.", "A derrota não encerra a história. Ela muda a forma de orar, lembrar, escrever e esperar."], meaning: [{ label: "O que é exílio", text: "Não é apenas mudar de endereço. É perder referências de terra, família, culto e governo, tentando reconstruir vida em outro império." }, { label: "Por que isto muda a Bíblia", text: "Muitos textos passam a perguntar como Deus pode ser fiel quando as instituições do povo falharam." }], peopleAndPlaces: [{ label: "Jeremias", text: "Profeta que fala antes e durante a queda de Jerusalém." }, { label: "Ezequiel", text: "Sacerdote e profeta entre os exilados na Babilônia." }, { label: "Babilônia", text: "Capital do império que destruiu Jerusalém; também se torna símbolo de poder opressor." }, { label: "Jerusalém", text: "Cidade destruída, lembrada em lamento e esperança." }], connections: ["Lamentações ensina que fé pode chorar sem respostas rápidas.", "Salmo 137 expressa a dor de viver longe de Sião.", "O livro de Daniel imagina fidelidade em corte estrangeira e dialoga com a vida na diáspora."], receptionOrDebate: ["Crônicas babilônicas, inscrições e tabletes ajudam a situar o império, mas a experiência de cada grupo exilado não foi igual.", "A Bíblia preserva vozes de luto, crítica, esperança e reconstrução. Não há uma única emoção chamada 'exílio'."], terms: [{ word: "Exílio", meaning: "Vida fora da terra, muitas vezes após derrota e deslocamento forçado." }, { word: "Lamento", meaning: "Oração que fala de dor, perda e protesto diante de Deus." }, { word: "Sião", meaning: "Nome poético e teológico para Jerusalém, especialmente o monte do templo." }] },
  persia: { firstAnswer: "Quando a Pérsia derrota a Babilônia, alguns judeus retornam a Jerusalém. A vida não volta ao que era: o povo precisa reconstruir templo, cidade, leis e identidade sob domínio persa.", story: ["Ciro, rei persa, permite políticas de retorno e restauração em vários lugares do império. Grupos judeus voltam gradualmente para Yehud, pequena província persa.", "Esdras e Neemias narram conflitos sobre culto, muralhas, dívidas, casamento, leitura pública da Torá e liderança. Ageu e Zacarias incentivam a reconstrução do templo.", "O período não é simplesmente 'fim feliz depois do exílio'. É trabalho lento, disputas internas e uma comunidade tentando definir quem é."], meaning: [{ label: "O que muda", text: "O povo deixa de ter rei próprio. Torá, templo, memória e comunidade passam a organizar sua vida de forma ainda mais decisiva." }, { label: "Por que ler Esdras e Neemias com cuidado", text: "Eles mostram fé e reconstrução, mas também tensões sobre poder, identidade e quem pertence ao grupo." }], peopleAndPlaces: [{ label: "Ciro", text: "Rei persa lembrado por permitir retorno e restauração de cultos locais." }, { label: "Esdras", text: "Escriba associado ao ensino da Torá." }, { label: "Neemias", text: "Administrador ligado à reconstrução das muralhas de Jerusalém." }, { label: "Yehud", text: "Nome da pequena província persa em torno de Jerusalém." }], connections: ["Esdras–Neemias conversa com Crônicas na importância de templo, culto e genealogias.", "A literatura do Segundo Templo começa a ganhar forma neste mundo pós-exílico.", "A leitura da Torá em Neemias ajuda a entender por que Escritura e interpretação se tornam centrais."], receptionOrDebate: ["O Cilindro de Ciro mostra uma política imperial de restauração, mas não é uma cópia do relato bíblico; comparar fontes exige atenção ao propósito de cada texto.", "Datas e ordem dos personagens em Esdras–Neemias são discutidas por estudiosos. A plataforma apresenta faixas e perguntas, não certezas artificiais."], terms: [{ word: "Pós-exílio", meaning: "Período depois da queda da Babilônia e do retorno de parte dos exilados." }, { word: "Torá", meaning: "Instrução divina que passa a organizar mais intensamente a comunidade." }, { word: "Yehud", meaning: "Província persa que corresponde aproximadamente à região de Judá." }] },
  hellenism: { firstAnswer: "Depois de Alexandre, o mundo do Oriente passa a falar muito grego e a viver sob novos governos. Judeus aprendem a preservar sua fé enquanto participam de cidades, mercados e debates de uma cultura ampla.", story: ["Alexandre conquista vastas regiões. Depois de sua morte, generais disputam territórios. A Judeia fica entre governos ptolomaico e selêucida.", "Antíoco IV tenta impor medidas que atingem práticas judaicas e o templo. A revolta dos Macabeus recupera o templo e forma um governo hasmoneu.", "Nesse período, são escritos ou copiados muitos textos: Daniel 7–12, Eclesiástico, Sabedoria, Macabeus, Enoque e outros. Eles mostram que judaísmo não era uma voz só."], meaning: [{ label: "O que é helenismo", text: "É a presença forte de língua e costumes gregos. Não significa que todos abandonaram sua fé; grupos responderam de formas diferentes." }, { label: "Por que isso prepara o Novo Testamento", text: "Jesus e Paulo vivem num mundo com estradas, cidades, língua grega, debates judaicos e presença romana construídos sobre essa história." }], peopleAndPlaces: [{ label: "Alexandre", text: "Conquistador macedônio cuja expansão altera idiomas e governos." }, { label: "Antíoco IV", text: "Rei selêucida associado à crise que provoca a revolta macabeia." }, { label: "Judas Macabeu", text: "Líder de resistência e figura central da recuperação do templo." }, { label: "Jerusalém", text: "Centro de disputa por culto, autoridade e identidade." }], connections: ["Daniel 7–12 é lido por muitos estudiosos em diálogo com esta crise.", "1–2 Macabeus contam a revolta por perspectivas diferentes.", "Os apócrifos e deuterocanônicos deixam de ser um apêndice quando você entende que pertencem ao mundo entre o retorno persa e Jesus."], receptionOrDebate: ["A palavra 'helenização' não descreve uma experiência única. Alguns grupos adotaram língua grega; outros resistiram; muitos fizeram as duas coisas em áreas diferentes da vida.", "É por isso que a seção de Apócrifos é uma porta de contexto, não uma lista de títulos estranhos."], terms: [{ word: "Helenismo", meaning: "Mundo moldado pela língua e cultura gregas após Alexandre." }, { word: "Selêucida", meaning: "Dinastia grega que governou a Judeia antes da revolta macabeia." }, { word: "Hasmoneu", meaning: "Família que liderou a revolta e depois governou a Judeia." }] },
  "roman-jesus": { firstAnswer: "Jesus nasce num mundo judaico sob domínio romano. Para entender os Evangelhos, é preciso ver templo, aldeias, impostos, soldados, festas e esperanças convivendo na mesma terra.", story: ["Roma toma a Judeia e governa por meio de reis locais, sacerdotes aliados e administradores. Herodes amplia o templo, mas seu governo também é marcado por violência e vigilância.", "Jesus cresce na Galileia, anuncia o reino de Deus, cura, ensina por parábolas e reúne discípulos. Ele vai a Jerusalém na Páscoa, confronta práticas do templo e é executado pelos romanos.", "Os Evangelhos anunciam que sua morte não encerra sua história: os discípulos proclamam sua ressurreição e formam comunidades."], meaning: [{ label: "O que é 'reino de Deus'", text: "Não é apenas ir para o céu. É a afirmação de que Deus é o verdadeiro rei, o que confronta injustiça, medo e poder opressor." }, { label: "Por que a cruz importa", text: "Era execução romana para quem parecia ameaça. Os cristãos a releram como entrega, julgamento do mal e início de uma nova vida." }], peopleAndPlaces: [{ label: "Jesus", text: "Mestre judeu do século I, centro dos Evangelhos e da fé cristã." }, { label: "Herodes e Pilatos", text: "Figuras políticas ligadas ao governo romano da região." }, { label: "Galileia e Jerusalém", text: "Regiões fundamentais: aldeias de ensino e cidade de templo, festa e conflito." }], connections: ["Evangelhos dialogam com Êxodo, profetas, Salmos e promessas davídicas.", "A Páscoa judaica forma parte do cenário da última semana de Jesus.", "Conhecer o Segundo Templo evita imaginar que Jesus apareceu num vazio entre Antigo e Novo Testamento."], receptionOrDebate: ["Os Evangelhos são relatos de fé e também fontes antigas sobre Jesus. Lê-los bem envolve observar sua narrativa, sua teologia e seu contexto romano-judaico.", "Reconstruções históricas trabalham com perguntas e probabilidades; elas não substituem a confissão cristã nem podem ser confundidas com ela."], terms: [{ word: "Roma", meaning: "Império que governava a Judeia no tempo de Jesus." }, { word: "Messias", meaning: "Ungido; título de esperança ligado a rei, libertação e missão de Deus." }, { word: "Páscoa", meaning: "Festa judaica que lembra o êxodo e enquadra a última semana de Jesus." }] },
  church: { firstAnswer: "Depois da ressurreição de Jesus, seus seguidores formam comunidades em cidades do Império Romano. Atos e as cartas mostram pessoas comuns aprendendo a viver uma fé nova em casas, mercados e conflitos reais.", story: ["Em Jerusalém, discípulos recebem o Espírito Santo e começam a anunciar Jesus. A mensagem alcança samaritanos, gentios e judeus da diáspora.", "Paulo viaja por cidades como Filipos, Tessalônica, Corinto e Éfeso. Suas cartas respondem a problemas concretos: divisões, sexualidade, trabalho, ceia, pobreza e liderança.", "As comunidades não são perfeitas. O Novo Testamento preserva correções porque seguir Jesus acontece em relações difíceis, não fora da vida."], meaning: [{ label: "O que é igreja", text: "No começo, não é prédio. É assembleia de pessoas que confessam Jesus e aprendem a partilhar vida, recursos e missão." }, { label: "Por que há tantas cartas", text: "Porque igrejas locais tinham perguntas próprias. Cada carta ensina dentro de uma situação, por isso contexto importa." }], peopleAndPlaces: [{ label: "Pedro", text: "Discípulo ligado à igreja de Jerusalém e à missão inicial." }, { label: "Paulo", text: "Missionário e escritor de cartas para várias comunidades." }, { label: "Antioquia, Corinto, Éfeso e Roma", text: "Cidades que mostram como a fé cristã circulou por redes urbanas." }], connections: ["Atos funciona como ponte entre Evangelhos e cartas.", "As cartas de Paulo devem ser lidas junto com os problemas das cidades para as quais foram enviadas.", "O atlas ajuda a perceber distâncias, rotas marítimas e diversidade cultural das comunidades."], receptionOrDebate: ["Atos e cartas não oferecem uma cronologia sem tensão. Compará-los ajuda a ver diferentes ângulos sobre viagens, decisões e conflitos.", "A diversidade das primeiras comunidades impede imaginar que todos os cristãos pensavam ou viviam de forma idêntica desde o início."], terms: [{ word: "Gentio", meaning: "Pessoa que não pertence ao povo judeu." }, { word: "Apóstolo", meaning: "Enviado ou testemunha com papel de anúncio e fundação de comunidades." }, { word: "Ceia", meaning: "Refeição de memória e comunhão que as comunidades cristãs partilhavam." }] },
  apocalypse: { firstAnswer: "Apocalipse não é um código para adivinhar datas. É uma visão escrita para comunidades pressionadas pelo poder romano, chamando-as a enxergar a história com esperança e fidelidade.", story: ["João escreve a sete igrejas da Ásia Menor. Ele reconhece suas virtudes e denuncia cansaço, riqueza sem amor, medo e compromisso com práticas injustas.", "Depois, vê tronos, selos, trombetas, monstros, uma cidade chamada Babilônia e uma nova criação. As imagens juntam profetas antigos, culto, política e esperança.", "O final não descreve pessoas abandonando a terra, mas uma nova Jerusalém e uma criação restaurada, onde Deus habita com seu povo."], meaning: [{ label: "O que as bestas representam", text: "Poderes que se apresentam como absolutos e exigem lealdade que pertence a Deus. No contexto inicial, Roma é parte essencial da imagem, mas o livro também fala de padrões de poder." }, { label: "O que é esperança", text: "Não é escapismo. É viver sem vender a consciência a um império, confiando que Deus fará justiça e renovará a criação." }], peopleAndPlaces: [{ label: "João", text: "Profeta e escritor que se dirige a igrejas concretas da Ásia Menor." }, { label: "Sete igrejas", text: "Comunidades reais em cidades reais, cada uma com desafios próprios." }, { label: "Babilônia", text: "Nome simbólico que relembra o antigo opressor e critica o poder imperial do presente." }], connections: ["Apocalipse cita e transforma imagens de Daniel, Ezequiel, Isaías, Zacarias e Êxodo.", "As cartas às sete igrejas exigem leitura local antes de qualquer teoria global.", "A seção escatológica compara escolas interpretativas sem fingir que o livro entrega uma agenda datada."], receptionOrDebate: ["Preterismo, historicismo, futurismo, idealismo e leituras ecléticas são maneiras de organizar a interpretação. Elas não devem ser confundidas com o próprio texto.", "A leitura pentecostal pode valorizar oração, discernimento e esperança, mas não autoriza marcar datas ou transformar símbolos em manchetes."], terms: [{ word: "Apocalipse", meaning: "Revelação ou desvelamento; gênero que usa visões e símbolos para interpretar a realidade." }, { word: "Besta", meaning: "Imagem de poder que imita a autoridade divina para dominar." }, { word: "Nova criação", meaning: "Esperança de que Deus renovará céu, terra e relações, vencendo morte e injustiça." }] }
};
