import { bibleBooks, type Book } from "@/lib/bible-data";

import { getBiographyEntities, getBiographyRelations } from "@/lib/biography-data";

// Cartografia de Leituras: este índice transforma a Bíblia em uma rede navegável de pessoas, lugares, eventos, temas e profecias.

export type EntityKind = "person" | "place" | "event" | "theme" | "prophecy";

export type KnowledgeEntity = {
  id: string;
  kind: EntityKind;
  name: string;
  aliases: string[];
  shortLabel: string;
  summary: string;
  biography: string;
  significance: string;
  refs: string[];
  books: string[];
  periods: string[];
  related: string[];
  lat?: number;
  lng?: number;
  primarySource?: string;
  academicNote?: string;
};

export type KnowledgeRelation = {
  id: string;
  from: string;
  to: string;
  label: string;
  type: "theological" | "prophetic" | "historical" | "geographic";
  explanation: string;
  refs: string[];
};

const person = (value: Omit<KnowledgeEntity, "kind">): KnowledgeEntity => ({ ...value, kind: "person" });
const place = (value: Omit<KnowledgeEntity, "kind">): KnowledgeEntity => ({ ...value, kind: "place" });

export const knowledgeEntities: KnowledgeEntity[] = [
  person({ id: "adam", name: "Adão", aliases: ["Adão", "Adam"], shortLabel: "Primeiro humano na narrativa de Gênesis", summary: "Figura de origem em Gênesis 1–5, apresentado como humano formado do solo e colocado no jardim para cultivar e guardar.", biography: "Adão não aparece em Gênesis como uma biografia moderna, mas como personagem de uma narrativa de origem. O nome hebraico ʾādām se relaciona a ʾădāmâ, “solo” ou “terra”, e o texto explora essa relação entre humanidade, trabalho, limite e mortalidade. Em Gênesis 2–3, ele recebe uma vocação, uma proibição e uma companheira; a transgressão reorganiza sua relação com o solo, com a mulher e com a presença divina. Gênesis 4–5 amplia seu lugar na genealogia, enquanto textos posteriores releem Adão teologicamente de modos diferentes.", significance: "Adão funciona como personagem de origem, elo entre criação, queda, trabalho, morte e genealogia. No Novo Testamento, Paulo o contrapõe a Cristo em Romanos 5 e 1 Coríntios 15; essas releituras não eliminam o contexto de Gênesis, mas mostram como a tradição cristã desenvolveu sua leitura.", refs: ["Gn 1–5", "Rm 5:12–21", "1Co 15:20–49", "1Tm 2:13–14"], books: ["Gênesis", "Romanos", "1 Coríntios", "1 Timóteo"], periods: ["Origens", "Apostólico"], related: ["eva", "queda", "noe", "cristo"], primarySource: "https://www.biblegateway.com/passage/?search=Genesis%201-5&version=ARA", academicNote: "A historicidade, o gênero e a relação com narrativas do antigo Oriente Próximo são debatidos; não se deve converter uma leitura teológica em consenso histórico." }),
  person({ id: "eva", name: "Eva", aliases: ["Eva", "Eve"], shortLabel: "Mulher associada à vida e à narrativa da queda", summary: "Personagem de Gênesis 2–4, formada no jardim, interlocutora da serpente e mãe de Caim, Abel e Sete.", biography: "Eva é apresentada como ʾēzer kenegdô, expressão frequentemente traduzida como “auxiliadora correspondente”, que não implica inferioridade no próprio uso bíblico de ʿēzer. Seu nome, Ḥawwâ, é associado a “vida” em Gênesis 3:20. A narrativa a coloca no centro do discernimento sobre o mandamento, da conversa com a serpente e da reorganização das relações após a transgressão. O texto não descreve uma mulher sem agência: Eva ouve, avalia, toma, come, oferece e nomeia; a interpretação responsável precisa observar tanto sua agência quanto a violência de leituras posteriores que transformaram a personagem em explicação única para o mal.", significance: "Eva liga criação, desejo, conhecimento, maternidade, conflito e esperança. A promessa de Gênesis 3:15 foi interpretada de maneiras variadas dentro do judaísmo e do cristianismo; a leitura cristã tradicional frequentemente a relaciona à vitória sobre a serpente, mas o sentido imediato deve ser estudado dentro da narrativa de Gênesis.", refs: ["Gn 2–4", "2Co 11:3", "1Tm 2:13–14"], books: ["Gênesis", "2 Coríntios", "1 Timóteo"], periods: ["Origens", "Apostólico"], related: ["adam", "queda", "serpente", "maria"], primarySource: "https://www.biblegateway.com/passage/?search=Genesis%202-4&version=ARA", academicNote: "As leituras de gênero, agência e simbolismo de Eva variam entre interpretações judaicas, cristãs, feministas e histórico-literárias." }),
  person({ id: "noah", name: "Noé", aliases: ["Noé", "Noah"], shortLabel: "Justo da narrativa do dilúvio", summary: "Personagem de Gênesis 5–10, associado à arca, ao dilúvio, à aliança e à repovoação da terra.", biography: "Noé é introduzido como alguém que encontrou favor diante de Deus em uma terra descrita como corrompida e violenta. A arca, a reunião dos animais, o dilúvio e a saída formam o núcleo narrativo. Depois das águas, o arco nas nuvens funciona como sinal de uma aliança que abrange a terra e os seres vivos. Gênesis 9, contudo, não encerra a narrativa com um herói sem falhas: o episódio da embriaguez e da exposição da nudez de Noé mostra a continuidade da ambiguidade humana depois do recomeço.", significance: "Noé conecta julgamento, preservação, aliança universal e o problema de reiniciar a história sem eliminar a violência humana. Jesus e Pedro usam a imagem dos dias de Noé em contextos escatológicos e de juízo, mas esses usos posteriores devem ser distinguidos do argumento de Gênesis.", refs: ["Gn 5–10", "Mt 24:37–39", "Lc 17:26–27", "1Pe 3:18–22", "2Pe 2:5"], books: ["Gênesis", "Mateus", "Lucas", "1 Pedro", "2 Pedro"], periods: ["Origens", "Apostólico"], related: ["diluvio", "alianca", "abraao"], primarySource: "https://www.biblegateway.com/passage/?search=Genesis%205-10&version=ARA", academicNote: "A narrativa dialoga com tradições de dilúvio do antigo Oriente Próximo, mas não é reduzida a uma cópia; relações literárias e históricas continuam debatidas." }),
  person({ id: "abraham", name: "Abraão", aliases: ["Abraão", "Abrão", "Abraham", "Abram"], shortLabel: "Patriarca das promessas, da migração e da aliança", summary: "Personagem de Gênesis 11–25, chamado a deixar sua terra e associado à promessa de descendência, terra e bênção.", biography: "Abrão entra na narrativa quando Terá e sua família deixam Ur dos caldeus em direção a Canaã, mas se estabelecem em Harã. Gênesis 12 retoma a marcha por meio de um chamado que combina saída, promessa e missão: ele será abençoado para que, nele, famílias da terra encontrem bênção. A trajetória inclui fome, deslocamentos ao Egito e Gerar, conflitos com Ló, guerras regionais, pactos, espera por um herdeiro, o nascimento de Ismael, a mudança de nome para Abraão e a narrativa difícil de Gênesis 22. Ele não é retratado como personagem linearmente idealizado; negocia, teme, erra, intercede e aprende a viver com promessas ainda não realizadas.", significance: "Abraão se torna eixo de memória para Israel, judaísmo, cristianismo e islamismo. Paulo o lê em Gálatas e Romanos como figura relacionada à fé e à inclusão dos gentios; Tiago enfatiza a fé que se torna ação. A enciclopédia precisa apresentar essas releituras sem apagar a narrativa de Gênesis nem a diversidade judaica.", refs: ["Gn 11:27–25:18", "Mt 1:1", "Jo 8:31–59", "Rm 4", "Gl 3", "Tg 2:14–26", "Hb 11:8–19"], books: ["Gênesis", "Mateus", "João", "Romanos", "Gálatas", "Tiago", "Hebreus"], periods: ["Patriarcas", "Apostólico"], related: ["sara", "isaque", "lote", "alianca", "promessa"], primarySource: "https://www.biblegateway.com/passage/?search=Genesis%2011%3A27-25%3A18&version=ARA", academicNote: "As tradições patriarcais são estudadas por crítica literária, história das tradições, arqueologia e antropologia; não existe consenso simples sobre uma biografia histórica de Abraão." }),
  person({ id: "sarah", name: "Sara", aliases: ["Sara", "Sarai", "Sarah"], shortLabel: "Matriarca da promessa e da maternidade tardia", summary: "Esposa de Abraão, originalmente Sarai, cuja história envolve esterilidade, migração, conflito doméstico, promessa e nascimento de Isaque.", biography: "Sarai aparece junto de Abrão em uma família migrante. A narrativa dá peso à sua esterilidade, não como diagnóstico isolado, mas como tensão central da promessa de descendência. O episódio de Hagar e Ismael expõe conflitos de poder, vulnerabilidade e herança dentro da casa patriarcal. A mudança de Sarai para Sara acompanha a reafirmação da promessa; Gênesis 18 apresenta a reação de riso e incredulidade diante da possibilidade de um filho, e Gênesis 21 transforma esse riso em nome e memória de Isaque. Sara morre em Hebrom, e sua sepultura em Macpela ancora a família na terra prometida.", significance: "Sara é lembrada como matriarca e mulher de fé em Hebreus 11 e 1 Pedro 3, mas uma leitura madura também considera Hagar e os efeitos de decisões tomadas por estruturas patriarcais. Sua história é indispensável para entender promessa, maternidade, herança e pertencimento.", refs: ["Gn 11:29–23:20", "Is 51:1–2", "Rm 4:19", "Gl 4:21–31", "Hb 11:11", "1Pe 3:5–6"], books: ["Gênesis", "Isaías", "Romanos", "Gálatas", "Hebreus", "1 Pedro"], periods: ["Patriarcas", "Apostólico"], related: ["abraham", "hagar", "isaque", "hebron"], primarySource: "https://www.biblegateway.com/passage/?search=Genesis%2011%3A29-23%3A20&version=ARA", academicNote: "A releitura de Sara em tradições judaicas e cristãs é ampla e, em Gálatas 4, Paulo usa uma alegoria que não esgota o sentido narrativo de Gênesis." }),
  person({ id: "jacob", name: "Jacó", aliases: ["Jacó", "Israel", "Jacob"], shortLabel: "Patriarca da luta, da astúcia e da formação das tribos", summary: "Filho de Isaque e Rebeca, irmão de Esaú, pai dos doze filhos e personagem que recebe o nome Israel.", biography: "Jacó nasce agarrado ao calcanhar de Esaú, imagem que antecipa a disputa por primogenitura e bênção. A narrativa combina sua astúcia, a manipulação da bênção paterna, a fuga para Harã, o trabalho com Labão, o casamento com Lia e Raquel, o crescimento da família e o retorno a Canaã. Em Peniel, luta durante a noite e recebe o nome Israel; o episódio não remove seu passado, mas marca uma transformação que permanece tensa. Jacó também precisa reencontrar Esaú, lidar com a violência de seus filhos e enfrentar a suposta morte de José.", significance: "Jacó/Israel articula biografia pessoal e origem coletiva. Seu nome passa do indivíduo para o povo, e seus conflitos familiares tornam-se memória nacional. Os profetas, Salmos e cartas usam Israel como categoria teológica e histórica em sentidos que precisam ser examinados em cada contexto.", refs: ["Gn 25–36", "Os 12", "Mt 8:11", "Rm 9:6–13", "Hb 11:21"], books: ["Gênesis", "Oseias", "Mateus", "Romanos", "Hebreus"], periods: ["Patriarcas", "Apostólico"], related: ["esau", "rebecca", "rachel", "joseph", "israel"], primarySource: "https://www.biblegateway.com/passage/?search=Genesis%2025-36&version=ARA", academicNote: "A relação entre Jacó como ancestral narrativo e Israel como entidade histórica é central para estudos de memória, etnogênese e formação textual." }),
  person({ id: "joseph", name: "José", aliases: ["José", "Joseph"], shortLabel: "Filho de Jacó cuja trajetória liga Canaã ao Egito", summary: "Filho de Jacó e Raquel, vendido por seus irmãos, elevado no Egito e agente de reconciliação e sobrevivência familiar.", biography: "A narrativa de José ocupa Gênesis 37–50 e possui uma arquitetura quase novelesca. O favoritismo de Jacó, o manto, os sonhos e a hostilidade dos irmãos conduzem à venda de José e à descida ao Egito. Lá, ele passa pela casa de Potifar, pela prisão e pela interpretação dos sonhos de Faraó. Sua ascensão administrativa durante a fome não é apenas triunfo individual: cria uma dependência econômica do Egito e, ao mesmo tempo, preserva a família de Jacó. Quando os irmãos retornam para comprar alimento, José testa, reconhece, chora, revela sua identidade e interpreta sua história sem negar o mal cometido contra ele.", significance: "José conecta a promessa patriarcal ao Egito e prepara a transição para Êxodo. A frase sobre Deus transformar o mal em bem em Gênesis 50:20 não é uma autorização para minimizar a violência; é uma interpretação teológica feita depois de um longo processo de perda, poder e reconciliação.", refs: ["Gn 37–50", "At 7:9–16", "Hb 11:22"], books: ["Gênesis", "Atos", "Hebreus"], periods: ["Patriarcas", "Apostólico"], related: ["jacob", "rachel", "egito", "exodo"], primarySource: "https://www.biblegateway.com/passage/?search=Genesis%2037-50&version=ARA", academicNote: "A história de José é analisada como narrativa de sabedoria, novela da diáspora, teologia da providência e memória de migração." }),
  person({ id: "moses", name: "Moisés", aliases: ["Moisés", "Moses"], shortLabel: "Libertador, mediador da aliança e legislador de Israel", summary: "Figura central de Êxodo–Deuteronômio, ligada ao êxodo, Sinai, tabernáculo e transmissão da lei.", biography: "Moisés é colocado entre a casa hebraica, a corte egípcia e o deserto de Midiã. Seu chamado na sarça o envia de volta ao poder de Faraó; ele conduz sinais, pragas, travessia do mar, aliança do Sinai e organização do culto. O personagem não é um herói sem conflito: hesita, perde a paciência, intercede, enfrenta rebeliões e não entra na terra de Canaã. A tradição judaica o torna o mediador por excelência da Torá; o Novo Testamento o apresenta em diálogo e contraste com Jesus em diferentes contextos.", significance: "Moisés articula libertação, lei, presença divina, liderança e limite humano. Na leitura pentecostal, sua vocação pode ser relacionada a chamado e missão, mas o texto também insiste na responsabilidade do líder e nos limites de qualquer mediação humana.", refs: ["Êx 2–40", "Dt 34", "Mt 17:1–8", "Jo 1:17", "Hb 3:1–6", "Ap 15:3"], books: ["Êxodo", "Deuteronômio", "Mateus", "João", "Hebreus", "Apocalipse"], periods: ["Êxodo", "Apostólico"], related: ["farao", "sinai", "alianca", "jesus"], primarySource: "https://www.biblegateway.com/passage/?search=Exodus%202-40&version=ARA", academicNote: "A relação entre Moisés narrativo, memória do êxodo e reconstrução histórica é um dos debates centrais da historiografia bíblica." }),
  person({ id: "david", name: "Davi", aliases: ["Davi", "David"], shortLabel: "Rei, guerreiro, poeta e origem da promessa dinástica", summary: "Pastor ungido, combatente, rei de Judá e Israel e figura central da memória monárquica.", biography: "Davi surge em 1 Samuel como o menor dos filhos de Jessé, escolhido por Samuel em uma cena que desloca a lógica da aparência e da primogenitura. Sua trajetória passa pelo conflito com Golias, pela amizade com Jônatas, pela perseguição de Saul, pela conquista de Jerusalém, pela centralização do reino e pelo pacto dinástico de 2 Samuel 7. A mesma narrativa expõe abusos de poder, o caso com Bate-Seba, o assassinato de Urias e as crises familiares que culminam na revolta de Absalão. Davi é simultaneamente rei idealizado, pecador confrontado e antepassado messiânico.", significance: "A promessa davídica é relida por Salmos, profetas, Evangelhos e cartas. O título “filho de Davi” carrega expectativa real e messiânica, mas os próprios textos preservam o escândalo da violência e da ambiguidade do rei.", refs: ["1Sm 16–31", "2Sm 1–24", "1Rs 1–2", "2Sm 7", "Sl 2", "Mt 1:1", "At 13:22–23"], books: ["1 Samuel", "2 Samuel", "1 Reis", "Salmos", "Mateus", "Atos"], periods: ["Monarquia", "Apostólico"], related: ["saul", "jonatas", "jerusalem", "jesus"], primarySource: "https://www.biblegateway.com/passage/?search=1%20Samuel%2016-31%3B%202%20Samuel%201-24&version=ARA", academicNote: "A chamada história da ascensão de Davi e os relatos deuteronomistas são lidos como narrativa histórica, propaganda real e memória teológica em combinações debatidas." }),
  person({ id: "jesus", name: "Jesus", aliases: ["Jesus", "Cristo", "Messias", "Jesus Cristo"], shortLabel: "Figura central dos Evangelhos e da fé cristã", summary: "Pregador judeu do século I, anunciado como Messias, crucificado sob autoridade romana e confessado pelos cristãos como ressuscitado.", biography: "Os quatro Evangelhos apresentam Jesus com ritmos, vocabulários e ênfases diferentes. Ele anuncia o reino de Deus, reúne discípulos, cura, ensina por parábolas, confronta interpretações da Torá, participa das festas judaicas, entra em conflito com autoridades e se dirige a pessoas socialmente marginalizadas. A crucificação sob o poder romano é o centro histórico da paixão; a ressurreição é apresentada pelos textos cristãos como a ação de Deus que reinterpreta a cruz e inaugura uma nova etapa da missão. A enciclopédia precisa estudar tanto o Jesus narrado pelos Evangelhos quanto os debates históricos sobre o Jesus da história e as formas de memória comunitária.", significance: "Jesus conecta criação, aliança, reino, profecia, templo, Espírito, nova comunidade e esperança escatológica. Na teologia pentecostal, sua obra é inseparável do Espírito Santo, da missão e da expectativa da consumação; ainda assim, cada afirmação deve ser ancorada no texto e em sua tradição interpretativa.", refs: ["Mt–Jo", "Mc 1:14–15", "Lc 4:16–21", "Jo 1:1–18", "Rm 5", "1Co 15", "Ap 5"], books: ["Mateus", "Marcos", "Lucas", "João", "Romanos", "1 Coríntios", "Apocalipse"], periods: ["Segundo Templo", "Romano", "Apostólico"], related: ["maria", "pedro", "paulo", "espirito-santo", "nova-criacao"], primarySource: "https://www.bibleodyssey.org/people/jesus/", academicNote: "A pesquisa histórica usa fontes cristãs, judaicas e romanas, com diferentes graus de proximidade e objetivos; confissão de fé e reconstrução histórica não são categorias idênticas." }),
  person({ id: "paul", name: "Paulo", aliases: ["Paulo", "Saulo", "Paul", "Saul"], shortLabel: "Apóstolo missionário e autor associado a cartas do Novo Testamento", summary: "Judeu da diáspora, fariseu segundo sua autodescrição, convertido seguidor de Jesus e missionário em redes urbanas do Mediterrâneo.", biography: "Paulo é conhecido por suas cartas e pela narrativa de Atos. Ele descreve sua formação judaica, sua antiga oposição ao movimento de Jesus e uma experiência de chamado que reorganiza sua missão entre gentios. Suas comunidades surgem em cidades conectadas por estradas, portos, oficinas e redes de patronato. As cartas tratam de conflitos concretos: alimentação, status, idolatria, sexualidade, trabalho, dons, autoridade, sofrimento, coleta e esperança da ressurreição. Paulo não escreve um sistema abstrato desligado das comunidades; ele argumenta pastoralmente em situações históricas específicas.", significance: "Paulo liga a morte e ressurreição de Jesus à inclusão dos gentios, à formação de comunidades e à ética do Espírito. A tradição pentecostal o lê como missionário, teólogo e testemunha de dons; a pesquisa acadêmica debate autoria, cronologia, retórica e relação entre as cartas e Atos.", refs: ["At 7–28", "Rm 1–16", "1Co 1–16", "Gl 1–6", "Fp 1–4", "2Tm 4"], books: ["Atos", "Romanos", "1 Coríntios", "Gálatas", "Filipenses", "2 Timóteo"], periods: ["Romano", "Apostólico"], related: ["jesus", "pedro", "antioquia", "roma", "espirito-santo"], primarySource: "https://www.bibleodyssey.org/people/paul/", academicNote: "As cartas paulinas autênticas e as deutero-paulinas precisam ser diferenciadas na pesquisa; “Paulo” não é uma voz homogênea em todo o corpus atribuído a ele." }),
  place({ id: "eden", name: "Éden", aliases: ["Éden", "Eden", "jardim do Éden", "jardim de Eden"], shortLabel: "Jardim da narrativa de criação e ruptura", summary: "Espaço narrativo de Gênesis 2–3 onde o humano recebe vocação, limite e presença de Deus.", biography: "Éden não é apresentado em Gênesis como uma cidade com coordenadas verificáveis. O jardim é descrito como espaço irrigado de onde saem rios, e sua função literária é colocar humanidade, animalidade, alimento, trabalho, limite e presença divina em uma paisagem de abundância. As tentativas de localizar o jardim no mapa moderno não alcançam consenso; o texto combina geografia imaginada, memória de rios conhecidos e teologia da origem.", significance: "Éden se torna matriz para temas de presença, perda, exílio, querubins, árvore da vida e restauração. Ezequiel e Apocalipse retomam imagens de jardim, água e vida, mas cada retomada deve ser estudada no seu próprio contexto.", refs: ["Gn 2–3", "Ez 28:12–19", "Ap 2:7", "Ap 22:1–5"], books: ["Gênesis", "Ezequiel", "Apocalipse"], periods: ["Origens", "Exílico", "Apostólico"], related: ["adam", "eva", "queda", "nova-criacao"], lat: 33.5, lng: 44.4, academicNote: "A coordenada é apenas um marcador didático associado à Mesopotâmia; não representa uma localização arqueológica comprovada." }),
  place({ id: "ur", name: "Ur", aliases: ["Ur", "Ur dos caldeus"], shortLabel: "Cidade mesopotâmica associada à origem da família de Abraão", summary: "Ur aparece na genealogia de Terá e na tradição de origem de Abraão, em uma região ligada ao sul da Mesopotâmia.", biography: "Ur foi uma cidade importante do sul da Mesopotâmia, associada à chamada Terceira Dinastia de Ur e a um complexo urbano e religioso centrado no zigurate de Nanna. Em Gênesis, a família de Terá parte de Ur dos caldeus em direção a Canaã, mas a identificação histórica exata da expressão e a relação entre a cidade arqueológica e a memória patriarcal são discutidas. A narrativa usa Ur como ponto de partida para uma história de deslocamento que passa por Harã e chega a Canaã.", significance: "Ur conecta migração, origem, cidade, império e memória ancestral. A arqueologia da cidade ilumina o mundo mesopotâmico, mas não prova individualmente a existência histórica de Abraão.", refs: ["Gn 11:27–32", "Gn 15:7", "Ne 9:7", "At 7:2–4"], books: ["Gênesis", "Neemias", "Atos"], periods: ["Patriarcas", "Mesopotâmia"], related: ["abraham", "haran", "mesopotamia"], lat: 30.96, lng: 46.1, academicNote: "A identificação tradicional com Tell el-Muqayyar é amplamente conhecida, mas a leitura histórica de Gênesis e a expressão “dos caldeus” exigem cautela cronológica." }),
  place({ id: "haran", name: "Harã", aliases: ["Harã", "Haran", "Padã-Arã"], shortLabel: "Entreposto mesopotâmico de Terá, Abraão e Jacó", summary: "Harã é ponto de parada e retorno nas narrativas patriarcais, entre Mesopotâmia e Canaã.", biography: "Harã aparece como lugar em que Terá morre, de onde Abraão recebe o chamado para continuar a viagem e para onde Jacó se dirige ao fugir de Esaú. A cidade situava-se em uma rede de rotas do norte da Mesopotâmia, próxima a importantes corredores comerciais. A narrativa bíblica não trata a migração como abstração: casamento, parentesco, rebanhos, servidão e herança dependem de lugares concretos.", significance: "Harã faz a ponte entre origem familiar e promessa territorial. Ela também impede uma leitura simplista de Abraão como alguém que salta diretamente de Ur para Canaã.", refs: ["Gn 11:31–32", "Gn 12:1–5", "Gn 27:43–31:55", "At 7:4"], books: ["Gênesis", "Atos"], periods: ["Patriarcas"], related: ["abraham", "jacob", "ur", "canaa"], lat: 36.87, lng: 39.03, academicNote: "A antiga Harran é arqueologicamente conhecida, mas a reconstrução das rotas patriarcais continua aproximada e dependente do texto." }),
  place({ id: "canaan", name: "Canaã", aliases: ["Canaã", "Canaan", "terra de Canaã"], shortLabel: "Território prometido e palco de conflitos de memória", summary: "Canaã é a região para a qual os patriarcas migram e que se torna território de promessa, disputa e formação de Israel.", biography: "Canaã não corresponde a uma fronteira política única ao longo da Bíblia. O termo pode designar uma região do Levante, uma população, uma rede de cidades ou o território prometido a Israel, dependendo do período e do texto. Gênesis narra a presença dos patriarcas como residentes estrangeiros com sepulturas, altares, poços e negociações locais; Êxodo–Josué transforma a terra em horizonte de libertação, conquista e aliança. A história arqueológica do Levante mostra uma paisagem plural, e não um vazio esperando ocupação.", significance: "Canaã concentra a tensão entre promessa, terra, memória, violência e justiça. Qualquer aplicação contemporânea precisa respeitar as diferenças entre os mundos narrados, históricos e políticos.", refs: ["Gn 12:5–7", "Gn 23", "Êx 3:8", "Js 1", "Am 2:9–10", "Hb 11:9"], books: ["Gênesis", "Êxodo", "Josué", "Amós", "Hebreus"], periods: ["Bronze", "Ferro", "Patriarcas", "Êxodo"], related: ["abraham", "jacob", "jerusalem", "exodo"], lat: 31.8, lng: 35.2, academicNote: "As fronteiras de Canaã variam; mapas didáticos não devem ser apresentados como fronteiras modernas ou como descrição única de uma entidade política." }),
  place({ id: "hebron", name: "Hebrom", aliases: ["Hebrom", "Hebron", "Manre", "Macpela"], shortLabel: "Centro patriarcal e lugar de sepultamento em Gênesis", summary: "Hebrom e os carvalhais de Manre aparecem associados a Abraão, Sara, Isaque, Rebeca, Jacó e Lia.", biography: "Hebrom é uma das âncoras geográficas da narrativa patriarcal. Abraão se estabelece junto aos carvalhais de Manre, recebe visitantes, negocia a sepultura de Sara e compra a caverna de Macpela. O lugar funciona como mais que cenário: uma sepultura adquirida torna-se sinal de pertencimento e esperança em uma terra onde a família ainda vive como estrangeira. Isaque e Rebeca, Jacó e Lia são associados ao mesmo espaço funerário, criando uma memória de linhagem.", significance: "Hebrom liga terra, morte, parentesco e promessa. O lugar continuará relevante na história de Davi e na memória política de Judá, mas seus usos posteriores não devem ser projetados automaticamente sobre Gênesis.", refs: ["Gn 13:18", "Gn 18", "Gn 23", "Gn 35:27–29", "Gn 49:29–33", "2Sm 5:1–5"], books: ["Gênesis", "2 Samuel"], periods: ["Patriarcas", "Monarquia"], related: ["abraham", "sarah", "isaque", "jacob", "canaa"], lat: 31.53, lng: 35.1, academicNote: "A identificação geográfica é sólida, mas os processos de memória e construção dos relatos patriarcais permanecem objeto de debate." }),
  place({ id: "egypt", name: "Egito", aliases: ["Egito", "Egypt", "terra do Egito"], shortLabel: "Potência e lugar de migração, opressão e preservação", summary: "Egito aparece em Gênesis como destino de fome e em Êxodo como sistema de trabalho forçado e lugar de onde Israel é libertado.", biography: "Em Gênesis, Abraão e Sara descem ao Egito durante uma fome; José chega como escravizado, ascende à administração e recebe sua família durante a crise alimentar. A mesma memória é reconfigurada em Êxodo, quando uma nova geração de faraós transforma os descendentes de Jacó em mão de obra submetida. O Egito é simultaneamente império, refúgio, mercado, casa de servidão e espaço de sobrevivência.", significance: "A saída do Egito torna-se matriz de libertação para profetas, salmos, Jesus e a teologia cristã. Uma leitura profunda mantém a tensão entre o Egito histórico plural e seu uso simbólico como memória de opressão.", refs: ["Gn 12", "Gn 37–50", "Êx 1–15", "Os 11:1", "Mt 2:13–15"], books: ["Gênesis", "Êxodo", "Oseias", "Mateus"], periods: ["Bronze", "Êxodo", "Romano"], related: ["joseph", "moses", "farao", "exodo"], lat: 29.98, lng: 31.13, academicNote: "O Egito bíblico não é uma imagem homogênea; cronologia, dinastias e relação entre narrativa e história precisam ser discutidas caso a caso." }),
  place({ id: "jerusalem", name: "Jerusalém", aliases: ["Jerusalém", "Jerusalem", "Sião", "Sion"], shortLabel: "Cidade do templo, da monarquia, da paixão e da esperança", summary: "Jerusalém atravessa monarquia, templo, exílio, ministério de Jesus, igreja primitiva e imaginação apocalíptica.", biography: "Jerusalém começa a ganhar centralidade na narrativa bíblica com Davi, que conquista a cidade e a transforma em capital; Salomão constrói o templo, e a cidade passa a concentrar culto, governo e memória. Sua destruição pela Babilônia e a reconstrução persa produzem lamento, profecia e reinterpretação. Nos Evangelhos, Jerusalém é o destino da paixão de Jesus; em Atos, é o ponto de partida da missão; em Gálatas e Hebreus, imagens de Jerusalém são usadas para pensar promessa e pertencimento; em Apocalipse, a Nova Jerusalém representa a consumação.", significance: "Jerusalém é lugar e símbolo, mas o símbolo nunca elimina o lugar histórico. A cidade precisa ser estudada em sua topografia, arqueologia, conflitos imperiais e usos teológicos diversos.", refs: ["2Sm 5–6", "1Rs 5–8", "2Rs 25", "Ed 1–6", "Mt 21–28", "At 1–2", "Ap 21–22"], books: ["2 Samuel", "1 Reis", "2 Reis", "Esdras", "Mateus", "Atos", "Apocalipse"], periods: ["Monarquia", "Exílico", "Segundo Templo", "Romano", "Apostólico"], related: ["david", "jesus", "templo", "nova-criacao"], lat: 31.78, lng: 35.22, academicNote: "A topografia histórica, o templo e as mudanças urbanas são estudados por arqueologia, fontes literárias e história política; a localização moderna não resolve todos os debates." }),
  place({ id: "babylon", name: "Babilônia", aliases: ["Babilônia", "Babilonia", "Babylon"], shortLabel: "Império, exílio, cidade simbólica e poder em julgamento", summary: "Babilônia é império histórico no exílio de Judá e símbolo teológico de arrogância, opressão e queda.", biography: "A Babilônia de Nabucodonosor destrói Jerusalém e deporta parte da elite de Judá, produzindo uma das maiores crises da memória bíblica. Jeremias interpreta o exílio, Ezequiel profetiza entre deportados, Daniel narra fidelidade em uma corte imperial e textos posteriores transformam Babilônia em símbolo de poder que se absolutiza. Apocalipse usa “Babilônia” como nome codificado para um sistema imperial e econômico, mas sua referência precisa ser investigada no contexto romano do livro.", significance: "Babilônia permite conectar história imperial, exílio, resistência, literatura apocalíptica e crítica econômica. A aplicação a qualquer potência moderna exige argumento, não apenas associação retórica.", refs: ["2Rs 24–25", "Jr 25", "Ez 1", "Dn 1–6", "Ap 14:8", "Ap 17–18"], books: ["2 Reis", "Jeremias", "Ezequiel", "Daniel", "Apocalipse"], periods: ["Babilônico", "Exílico", "Romano"], related: ["jerusalem", "daniel", "exilio", "apocalipse"], lat: 32.54, lng: 44.42, academicNote: "A cidade histórica e a Babilônia simbólica de Apocalipse devem ser relacionadas sem serem simplesmente igualadas." }),
  place({ id: "antioch", name: "Antioquia", aliases: ["Antioquia", "Antioch", "Antioquia da Síria"], shortLabel: "Centro urbano da missão gentílica e da identidade cristã", summary: "Antioquia da Síria é lugar de ensino, conflito, envio missionário e formação de uma comunidade multicultural.", biography: "Antioquia surge em Atos como cidade em que discípulos vindos de diferentes trajetórias formam uma comunidade e são chamados cristãos. Barnabé busca Saulo, a comunidade discerne uma missão e envia a primeira grande expedição missionária de Atos 13. Gálatas 2 preserva o conflito sobre mesa, circuncisão e comunhão entre judeus e gentios; o lugar torna-se laboratório de uma questão que atravessa a igreja primitiva: como formar um povo comum sem apagar diferenças históricas.", significance: "Antioquia conecta Espírito, missão, mesa, conflito, discernimento comunitário e expansão urbana. A tradição pentecostal pode reconhecer a centralidade do envio e da ação do Espírito, mas o conflito mostra que missão não elimina disputas de poder e identidade.", refs: ["At 11:19–30", "At 13–15", "Gl 2:11–14"], books: ["Atos", "Gálatas"], periods: ["Romano", "Apostólico"], related: ["paul", "barnabe", "espirito-santo", "jerusalem"], lat: 36.2, lng: 36.16, academicNote: "A geografia urbana e a composição étnica de Antioquia são importantes para interpretar a missão e os conflitos de Paulo." }),
  place({ id: "rome", name: "Roma", aliases: ["Roma", "Rome"], shortLabel: "Capital imperial e horizonte da missão apostólica", summary: "Roma é destino narrativo de Atos, comunidade destinatária de Romanos e cenário de relações entre evangelho e poder imperial.", biography: "Roma não é fundada por Paulo na narrativa bíblica; a carta aos Romanos pressupõe uma comunidade já existente e discute identidade, Israel, gentios, justiça e hospitalidade. Atos termina com Paulo em Roma, pregando sob custódia, sem apresentar uma conclusão triunfal. O espaço romano envolve estradas, cidadania, escravidão, patronato, cultos e violência imperial. Apocalipse, escrito para comunidades da Ásia, usa imagens de Babilônia para criticar a lógica imperial sem depender de uma nomeação direta.", significance: "Roma permite ler missão, cidadania, império, sofrimento, comunidade e escatologia em conjunto. O evangelho em Roma não é apenas geografia de expansão, mas encontro com estruturas de poder.", refs: ["At 28", "Rm 1–16", "Fp 1:12–14", "Ap 17–18"], books: ["Atos", "Romanos", "Filipenses", "Apocalipse"], periods: ["Romano", "Apostólico"], related: ["paul", "jesus", "babilonia", "apocalipse"], lat: 41.9, lng: 12.5, academicNote: "A relação entre Apocalipse e Roma é uma leitura influente, mas o livro trabalha com símbolo, alusão e crítica imperial em níveis que não se reduzem a um código simples." }),
];

export const knowledgeRelations: KnowledgeRelation[] = [
  { id: "r-eden-fall", from: "eden", to: "queda", label: "origem e ruptura", type: "theological", explanation: "O jardim é o espaço narrativo em que limite, desejo, discernimento e expulsão reorganizam a relação entre humanidade, solo e presença divina.", refs: ["Gn 2–3"] },
  { id: "r-abraham-promise", from: "abraham", to: "promessa", label: "aliança e promessa", type: "theological", explanation: "O chamado de Abraão abre uma linha narrativa de descendência, terra e bênção que será retomada por profetas, Paulo e Hebreus.", refs: ["Gn 12:1–3", "Gn 15", "Gl 3"] },
  { id: "r-exodus-egypt", from: "egypt", to: "exodo", label: "opressão e libertação", type: "historical", explanation: "O Egito funciona como lugar de preservação em Gênesis e como casa de servidão em Êxodo, criando a memória fundadora da libertação.", refs: ["Gn 37–50", "Êx 1–15"] },
  { id: "r-jerusalem-jesus", from: "jerusalem", to: "jesus", label: "paixão e ressurreição", type: "theological", explanation: "Jerusalém é o destino da paixão nos Evangelhos e o ponto de partida da missão em Atos.", refs: ["Lc 9:51", "At 1:8"] },
  { id: "r-babylon-exile", from: "babylon", to: "exilio", label: "cidade e exílio", type: "historical", explanation: "A Babilônia histórica desloca Judá; a literatura bíblica converte o trauma em lamento, resistência e esperança de restauração.", refs: ["2Rs 24–25", "Jr 29", "Dn 1"] },
  { id: "r-babylon-apocalypse", from: "babylon", to: "apocalipse", label: "império em julgamento", type: "prophetic", explanation: "Apocalipse retoma o nome Babilônia para criticar concentração de poder, luxo, violência e comércio imperial.", refs: ["Ap 17–18"] },
  { id: "r-paul-antioch", from: "paul", to: "antioch", label: "envio missionário", type: "geographic", explanation: "Antioquia é base de envio e espaço de negociação sobre a inclusão de gentios.", refs: ["At 11:25–26", "At 13:1–3", "Gl 2:11–14"] },
  { id: "r-paul-rome", from: "paul", to: "rome", label: "missão e império", type: "geographic", explanation: "Roma representa o horizonte urbano e imperial da missão de Paulo e o destinatário de uma carta teológica central.", refs: ["At 28", "Rm 1:10–15"] },
  { id: "r-adam-christ", from: "adam", to: "jesus", label: "Adão e Cristo", type: "theological", explanation: "Paulo contrasta Adão e Cristo em uma releitura da morte, da humanidade e da ressurreição.", refs: ["Rm 5:12–21", "1Co 15:20–49"] },
];

export function getAllKnowledgeEntities() {
  const seen = new Set<string>();
  return [...getBiographyEntities(), ...knowledgeEntities].filter((entity) => {
    const key = `${entity.kind}:${normalizeEntityKey(entity.name)}`;
    if (seen.has(key)) return false;
    seen.add(key);
    return true;
  });
}

export function getAllKnowledgeRelations() {
  return [...getBiographyRelations(), ...knowledgeRelations];
}

export function normalizeEntityKey(value: string) {
  return value.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
}

export function findKnowledgeEntity(id: string) {
  return getAllKnowledgeEntities().find((entity) => entity.id === id) || null;
}

export function getEntitiesForBook(bookName: string) {
  const normalized = normalizeEntityKey(bookName);
  return getAllKnowledgeEntities().filter((entity) => entity.books.some((book) => normalizeEntityKey(book) === normalized));
}

function escapeRegExp(value: string) {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

export function decorateMarkdown(markdown: string, bookName: string, extraEntities: KnowledgeEntity[] = []) {
  const candidates = [...extraEntities, ...getAllKnowledgeEntities(), ...getEntitiesForBook(bookName)];
  const aliases = new Map<string, { label: string; entity: KnowledgeEntity }>();
  for (const entity of candidates) for (const alias of [entity.name, ...entity.aliases]) {
    const key = alias.toLocaleLowerCase();
    if (alias.length > 3 && !aliases.has(key)) aliases.set(key, { label: alias, entity });
  }
  const sortedAliases = Array.from(aliases.values()).sort((a, b) => b.label.length - a.label.length);
  const protectedLinks: string[] = [];
  const skeleton = markdown.replace(/\[[^\]]+\]\([^)]*\)/g, (link: string) => `@@LINK_${protectedLinks.push(link) - 1}@@`);
  const decorated = sortedAliases.reduce((current, item) => current.replace(new RegExp(`(?<![\\w#])${escapeRegExp(item.label)}(?![\\w])`, "giu"), `[${item.label}](#entity-${item.entity.id})`), skeleton);
  return decorated.replace(/@@LINK_(\d+)@@/g, (_match: string, index: string) => protectedLinks[Number(index)] || "");
}

export function searchKnowledge(query: string, kind = "all") {
  const normalized = query.trim().toLowerCase();
  const entityResults = getAllKnowledgeEntities().filter((entity) => (kind === "all" || kind === entity.kind) && (!normalized || [entity.name, entity.summary, entity.biography, entity.significance, entity.books.join(" "), entity.refs.join(" ")].join(" ").toLowerCase().includes(normalized)));
  const bookResults = bibleBooks.filter((book) => (kind === "all" || kind === "book") && (!normalized || [book.name, book.author, book.summary, book.category, book.themes.join(" ")].join(" ").toLowerCase().includes(normalized)));
  const relationResults = getAllKnowledgeRelations().filter((relation) => (kind === "all" || kind === "relation") && (!normalized || [relation.label, relation.explanation, relation.refs.join(" ")].join(" ").toLowerCase().includes(normalized)));
  return { entityResults, bookResults, relationResults };
}

export function bookFromEntityReference(name: string): Book | null {
  return bibleBooks.find((book) => normalizeEntityKey(book.name) === normalizeEntityKey(name)) || null;
}
