// Cartografia de Leituras: coleções levam o grupo por estações textuais, históricas e práticas, sem tratar um encontro como resumo isolado.
export type GroupStudyCollection = {
  id: string;
  code: string;
  title: string;
  subtitle: string;
  audience: string;
  duration: string;
  overview: string;
  objectives: string[];
  sessions: Array<{ number: string; title: string; scripture: string; aim: string; movement: string; questions: string[]; practice: string; atlas: string; source: { label: string; url: string } }>;
};

export const groupStudyCollections: GroupStudyCollection[] = [
  {
    id: "alianca-no-caminho", code: "COLEÇÃO 01", title: "Aliança no caminho", subtitle: "Santidade, crise, memória e serviço", audience: "Escola Dominical · jovens · pequenos grupos", duration: "4 encontros de 60–75 minutos", overview: "Uma coleção para acompanhar como uma comunidade aprende a viver diante de Deus entre culto, trabalho, deserto, medo e compromisso público. Ela utiliza os novos comentários de Levítico, Números e Josué como rota de estudo, sem reduzir cada texto a uma moral rápida.", objectives: ["Ler santidade como vida comunitária e não como aparência religiosa.", "Discutir fé e medo sem negar os obstáculos reais do caminho.", "Relacionar memória bíblica, liderança responsável e compromisso coletivo."],
    sessions: [
      { number: "01", title: "Santidade que alcança o próximo", scripture: "Levítico 19:1–18", aim: "Reconhecer que a santidade reúne adoração, justiça, trabalho e amor ao próximo.", movement: "Abra com a pergunta: onde a fé aparece na forma como tratamos quem vive e trabalha perto de nós? Leia o texto em blocos, localize as práticas de colheita, salário e tribunal, e volte ao mandamento do amor.", questions: ["Que práticas cotidianas o texto coloca dentro da santidade?", "Que formas de favoritismo ou exploração este capítulo confronta hoje?", "Como a comunidade pode transformar amor ao próximo em prática verificável?"], practice: "Cada participante escolhe uma ação de reparação, cuidado ou justiça para realizar e retomar no próximo encontro.", atlas: "Região montanhosa de Canaã · aldeias, campos e redes de sobrevivência", source: { label: "Society of Biblical Literature", url: "https://www.sbl-site.org/" } },
      { number: "02", title: "Quando o medo interpreta a realidade", scripture: "Números 13:1–33", aim: "Distinguir avaliação responsável, imaginação do medo e confiança comunitária.", movement: "Compare os elementos comuns aos relatórios dos espias e o ponto em que as leituras se dividem. Trabalhe a diferença entre negar a dificuldade e permitir que a dificuldade defina toda a identidade do povo.", questions: ["O que todos os espias realmente viram?", "Quando uma análise prudente se transforma em paralisia?", "Como um grupo pode ouvir vozes diferentes sem produzir pânico ou silenciamento?"], practice: "Mapeie um desafio real do grupo em duas colunas: fatos observáveis e interpretações que precisam de discernimento.", atlas: "Deserto e terra de Canaã · rotas de reconhecimento e fronteiras aproximadas", source: { label: "Bible Odyssey · lugares e contextos", url: "https://www.bibleodyssey.org/theme/places/" } },
      { number: "03", title: "Água, conflito e liderança", scripture: "Números 20:1–13", aim: "Ler uma crise de necessidade sem naturalizar abuso, medo ou autoritarismo religioso.", movement: "Observe a sede, a queixa, a instrução recebida e a resposta de Moisés. Em seguida, compare Meribá com Êxodo 17 e discuta por que a memória bíblica preserva falhas de lideranças importantes.", questions: ["Por que a necessidade material do povo é relevante para a leitura?", "O que o texto preserva de complexo sobre Moisés e Arão?", "Como líderes e comunidades podem enfrentar crise com responsabilidade?"], practice: "Prepare uma breve oração de intercessão que nomeie necessidades concretas, responsabilidades e caminhos de cuidado.", atlas: "Sinai e wadis do deserto · água, deslocamento e memória da aliança", source: { label: "Society of Biblical Literature", url: "https://www.sbl-site.org/" } },
      { number: "04", title: "Memória para servir", scripture: "Josué 24:1–28", aim: "Entender a renovação da aliança como resposta pública e comunitária, não como decisão sem história.", movement: "Leia o discurso de Josué como uma recapitulação do caminho. Marque os verbos de Deus antes da resposta do povo, situe Siquém no atlas e explore a imagem da pedra como testemunha de memória e compromisso.", questions: ["Que memórias Josué seleciona para formar a comunidade?", "O que se perde quando ‘escolhei hoje’ vira apenas escolha individual?", "Que práticas ajudam uma igreja a servir sem sincretismo ou triunfalismo?"], practice: "Escrevam uma breve regra de serviço do grupo, com um compromisso de oração, cuidado e ação comunitária para o próximo mês.", atlas: "Siquém e a região montanhosa central · memória patriarcal e alianças", source: { label: "Pleiades · gazetteer histórico", url: "https://pleiades.stoa.org/places" } },
    ],
  },
  {
    id: "cidades-imperios-testemunho", code: "COLEÇÃO 02", title: "Cidades, impérios e testemunho", subtitle: "Babilônia, Galileia e Roma como paisagens de leitura", audience: "Pequenos grupos · classes de história bíblica", duration: "4 encontros de 60–75 minutos", overview: "Uma rota para ler cidades e impérios como contextos que moldam linguagem, culto, economia, exílio e missão. As pranchas do atlas entram como orientação geográfica; o texto bíblico continua sendo o centro de cada encontro.", objectives: ["Situar passagens bíblicas dentro de cidades, rotas e relações de poder.", "Distinguir contexto histórico, interpretação teológica e aplicação contemporânea.", "Relacionar testemunho cristão a fidelidade, justiça e presença pública."],
    sessions: [
      { number: "01", title: "Às margens da Babilônia", scripture: "Salmo 137; Ezequiel 1:1–3", aim: "Explorar exílio, memória e a presença de Deus fora de Jerusalém.", movement: "Abra a prancha de Babilônia, localize o Eufrates e observe como lamento e visão profética recusam tanto esquecimento quanto desespero. Diferencie a cidade histórica das imagens simbólicas que ela recebe em textos posteriores.", questions: ["Que tipo de perda o salmo nomeia?", "Como Ezequiel altera a pergunta sobre onde Deus pode ser encontrado?", "Que usos abusivos de ‘Babilônia’ precisam ser evitados?"], practice: "Escrevam uma oração de lamento que também preserve esperança e responsabilidade.", atlas: "Babilônia neo-babilônica · Eufrates, deportação e arquivos de diáspora", source: { label: "British Museum · Mesopotâmia", url: "https://www.britishmuseum.org/collection/galleries/mesopotamia" } },
      { number: "02", title: "Galileia e a boa notícia aos pobres", scripture: "Lucas 4:16–30", aim: "Situar a missão de Jesus em aldeias, sinagogas, economia rural e fronteiras sociais.", movement: "Use a vista da Galileia para observar lago, campos e caminhos. Leia a citação de Isaías, depois o conflito gerado quando Jesus recorda estrangeiros alcançados por misericórdia.", questions: ["Que dimensões sociais aparecem na leitura de Isaías?", "Por que a reação muda durante a cena?", "Como anunciar boas-novas sem espiritualizar pobreza e exclusão?"], practice: "Identifiquem uma fronteira de acolhimento que o grupo precisa atravessar com escuta e serviço.", atlas: "Baixa Galileia · aldeias, lago e redes de circulação no século I", source: { label: "Bible Odyssey · lugares e contextos", url: "https://www.bibleodyssey.org/theme/places/" } },
      { number: "03", title: "Roma, corpo e dons", scripture: "Romanos 12:1–8", aim: "Ler culto e carisma como serviço corporal, renovação e pertença mútua.", movement: "Aproxime Roma como horizonte urbano e imperial da carta. Em seguida, acompanhe a transição da misericórdia de Deus para corpo, mente, dons e comunidade, evitando tratar carisma como prestígio.", questions: ["O que muda quando culto inclui todo o corpo e a vida comum?", "Por que dons não são degraus de status?", "Que renovação de mente o grupo precisa praticar juntos?"], practice: "Cada pessoa identifica um dom ou recurso que pode ser colocado a serviço do corpo durante a semana.", atlas: "Roma imperial · cidade, redes urbanas e comunidades de Jesus", source: { label: "Society of Biblical Literature", url: "https://www.sbl-site.org/" } },
      { number: "04", title: "Testemunho diante do poder", scripture: "Apocalipse 13:1–18", aim: "Discernir idolatria e poder sem converter o texto em um código de notícias.", movement: "Retome Babilônia e Roma como memórias que Apocalipse transforma em imagética de crítica ao poder. Leia o capítulo com Daniel 7 e identifique adoração, economia, lealdade e resistência.", questions: ["Que relações entre culto, economia e violência o texto desenha?", "Por que o capítulo não autoriza identificar automaticamente cada adversário com a besta?", "Como fidelidade ao Cordeiro ganha forma concreta hoje?"], practice: "Formulem uma prática comunitária de consumo, serviço ou solidariedade que resista à idolatria do poder.", atlas: "Ásia romana e Mediterrâneo · cidades, culto imperial e redes comerciais", source: { label: "Yale Bible Study · Apocalipse", url: "https://yalebiblestudy.org/courses/revelation/lessons/introduction-to-the-course-3/" } },
    ],
  },
];
