export type QuestionGuide = {
  question: string;
  keywords: string[];
  answer: string;
  references: string[];
  book?: string;
  next: string;
};

export const questionGuides: QuestionGuide[] = [
  { question: "Por que Jó sofreu?", keywords: ["jó", "sofreu", "sofrimento"], answer: "O livro de Jó não entrega uma explicação única para todo sofrimento. Ele recusa a ideia de que cada dor prova culpa pessoal, mostra a limitação dos amigos que falam com excesso de certeza e conduz o leitor a uma conversa sobre justiça, criação, lamento e confiança sem respostas fáceis.", references: ["Jó 1–2", "Jó 19", "Jó 38–42"], book: "Jó", next: "Abra Jó no roteiro dos 66 livros e acompanhe as falas dos amigos, a queixa de Jó e a resposta final." },
  { question: "O que é graça?", keywords: ["graça", "graca", "salvação", "salvacao"], answer: "Na linguagem paulina, graça descreve a iniciativa generosa de Deus que alcança pessoas sem tratá-la como pagamento por mérito. A palavra não elimina responsabilidade ética; ela altera a base da relação: a vida nova é resposta à dádiva, não moeda para comprar aceitação.", references: ["Romanos 3:21–26", "Romanos 5:1–11", "Efésios 2:1–10"], book: "Romanos", next: "Continue em Romanos para observar como justiça, fé, pecado e vida no Espírito se relacionam." },
  { question: "O que a Bíblia fala sobre dívida, trabalho e generosidade?", keywords: ["dívida", "divida", "trabalho", "generosidade", "finanças", "financas", "dinheiro"], answer: "A Bíblia fala de trabalho, empréstimo, pobreza, riqueza, justiça e partilha em muitos gêneros e épocas. Ela não oferece uma fórmula automática de investimento; convida a examinar como poder econômico, cuidado do vulnerável, responsabilidade, contentamento e comunidade aparecem em cada texto.", references: ["Deuteronômio 15", "Provérbios 11", "Lucas 12", "2 Coríntios 8–9"], next: "Abra o percurso Finanças, trabalho e generosidade para seguir a pergunta em etapas e contextos diferentes." },
  { question: "O que é o batismo no Espírito Santo?", keywords: ["batismo", "espírito", "espirito", "línguas", "linguas", "dons"], answer: "Atos apresenta o Espírito capacitando a comunidade para testemunho, missão e vida comum. As tradições cristãs concordam sobre a centralidade do Espírito, mas divergem sobre a relação entre conversão, experiências subsequentes, línguas e dons. A leitura pentecostal deve ser mostrada com respeito, sem apagar outras interpretações.", references: ["Atos 1–2", "Atos 8", "Atos 10", "Atos 19", "1 Coríntios 12–14"], book: "Atos", next: "Abra Atos e depois o percurso Espírito Santo e dons para distinguir narrativa, doutrina e prática comunitária." },
  { question: "Quem é Melquisedeque?", keywords: ["melquisedeque", "melquisedeque"], answer: "Melquisedeque aparece brevemente como rei de Salém e sacerdote de Deus Altíssimo que abençoa Abraão. O texto de Gênesis é conciso; Salmo 110 e Hebreus desenvolvem sua figura para falar de realeza, sacerdócio e da singularidade de Cristo. É importante não ler de volta em Gênesis tudo o que textos posteriores elaboram.", references: ["Gênesis 14:18–20", "Salmo 110", "Hebreus 5–7"], book: "Gênesis", next: "Siga as conexões de Gênesis a Hebreus para perceber como a leitura canônica trabalha uma figura breve." },
  { question: "O que Apocalipse quer dizer?", keywords: ["apocalipse", "besta", "666", "milênio", "milenio", "arrebatamento"], answer: "Apocalipse é literatura visionária e simbólica dirigida a comunidades reais sob pressão imperial. Ele fala de fidelidade, adoração, violência, juízo, esperança e nova criação. Há desacordo honesto sobre como relacionar suas imagens com épocas históricas; por isso a plataforma apresenta escolas interpretativas em vez de datas ou certezas artificiais.", references: ["Apocalipse 1", "Apocalipse 13", "Apocalipse 20–22"], book: "Apocalipse", next: "Abra a rota escatológica para comparar escolas de leitura, símbolos e textos-base." },
];
