// Cartografia de Leituras: comparar traduções sem transformar uma versão em medida única de fidelidade.

export type TranslationComparisonRow = {
  version: string;
  approach: string;
  note: string;
};

export type TranslationComparison = {
  id: string;
  reference: string;
  title: string;
  originalIssue: string;
  context: string;
  rows: TranslationComparisonRow[];
  textualNote: string;
  sources: { label: string; url: string }[];
};

export const translationComparisons: TranslationComparison[] = [
  { id: "gen-1-2", reference: "Gênesis 1:2", title: "Ruach: vento, sopro ou Espírito?", originalIssue: "O hebraico ruach pode sustentar mais de uma imagem em sequência.", context: "A abertura da criação trabalha com águas, escuridão, movimento e palavra. A tradução escolhe uma imagem principal, mas o leitor pode recuperar o campo semântico inteiro.", rows: [{ version: "Tradução formal", approach: "Preserva a proximidade lexical", note: "Tende a manter ‘Espírito’ e abre uma leitura teológica forte." }, { version: "Tradução dinâmica", approach: "Expõe a imagem para o leitor", note: "Pode preferir ‘vento’ ou ‘sopro’, tornando a cena mais concreta." }, { version: "Nota de estudo", approach: "Registra a ambiguidade", note: "Mostra que vento, sopro e Espírito pertencem ao mesmo debate lexical." }], textualNote: "Não existe uma tradução neutra que elimine a decisão; a questão é mostrar a decisão e seu efeito.", sources: [{ label: "Bible Odyssey — cânon e tradições", url: "https://www.bibleodyssey.org/articles/why-does-the-bible-look-the-way-it-does/" }] },
  { id: "ex-3-14", reference: "Êxodo 3:14", title: "O nome divino e a forma verbal", originalIssue: "A expressão hebraica ehyeh asher ehyeh comporta decisões sobre tempo, presença e tradução.", context: "A resposta a Moisés ocorre em uma cena de vocação e libertação. O sentido não deve ser isolado da promessa de presença no capítulo.", rows: [{ version: "Tradução tradicional", approach: "Prioriza a fórmula consagrada", note: "‘Eu sou o que sou’ enfatiza identidade e mistério." }, { version: "Tradução aspectual", approach: "Prioriza a ação verbal", note: "‘Eu serei o que serei’ ou formas próximas destacam presença e futuro aberto." }, { version: "Nota de estudo", approach: "Mantém as duas possibilidades", note: "Relaciona a frase a Êxodo 3:12 e à presença que acompanha a missão." }], textualNote: "O problema é semântico e teológico ao mesmo tempo; uma nota responsável evita declarar que uma única paráfrase esgota o hebraico.", sources: [{ label: "Society of Biblical Literature", url: "https://www.sbl-site.org/" }] },
  { id: "ps-22-16", reference: "Salmo 22:16", title: "Uma variante que atravessa traduções", originalIssue: "A leitura tradicional e os testemunhos textuais antigos diferem na imagem do verbo ligado a mãos e pés.", context: "O salmo é poesia de lamento e confiança. A recepção cristã relacionou o texto à paixão, mas a exegese deve começar pelo lamento em seu contexto poético.", rows: [{ version: "Leitura tradicional", approach: "Segue a forma hebraica massorética tradicional", note: "Apresenta a imagem de perfuração ou ferimento conforme a tradição recebida." }, { version: "Leitura crítica", approach: "Considera testemunhos e emenda possível", note: "Pode apresentar a imagem de ‘como um leão’ e sinalizar a discussão em nota." }, { version: "Leitura canônica", approach: "Lê o salmo em sua recepção", note: "Relaciona a paixão sem apagar o sentido do lamento original." }], textualNote: "Uma variante textual não é um detalhe sem importância, mas também não permite afirmar que a forma posterior seja automaticamente uma fraude; é preciso comparar testemunhos e argumentos.", sources: [{ label: "Leon Levy Dead Sea Scrolls Digital Library", url: "https://www.deadseascrolls.org.il/?locale=en_US" }, { label: "Yale — crítica textual do NT", url: "https://guides.library.yale.edu/newtestament/textualcriticism" }] },
  { id: "is-7-14", reference: "Isaías 7:14", title: "Almah, parthenos e recepção", originalIssue: "O hebraico almah e a tradução grega parthenos participam de histórias semânticas e canônicas diferentes.", context: "Isaías 7 está ligado a uma crise política no reino de Judá. Mateus relê a passagem em uma teologia de cumprimento.", rows: [{ version: "Hebraico contextual", approach: "Começa com o sinal para a crise de Acaz", note: "Investiga a função de almah no contexto histórico e literário de Isaías." }, { version: "Septuaginta", approach: "Considera a tradução grega antiga", note: "Observa a escolha de parthenos e sua circulação entre leitores gregos." }, { version: "Leitura cristã", approach: "Lê a passagem em Mateus", note: "Apresenta a recepção cristológica como releitura canônica, não como apagamento do contexto de Isaías." }], textualNote: "A mesma passagem pode carregar sentido no contexto original e novo sentido em uma releitura posterior; a tarefa é descrever a relação, não escolher uma camada e eliminar a outra.", sources: [{ label: "Bible Odyssey — por que existem várias Bíblias", url: "https://www.bibleodyssey.org/articles/why-does-the-bible-look-the-way-it-does/" }] },
  { id: "mt-5-3", reference: "Mateus 5:3", title: "Pobres de espírito e a bem-aventurança", originalIssue: "A construção grega combina pobreza, espírito e a forma da bem-aventurança.", context: "O Sermão do Monte apresenta uma inversão de valores que precisa ser lida junto das promessas e da ética do capítulo.", rows: [{ version: "Literal", approach: "Preserva a construção", note: "Mantém ‘pobres em espírito’ e exige uma explicação do sentido." }, { version: "Interpretativa", approach: "Explicita dependência e vulnerabilidade", note: "Pode comunicar humildade ou necessidade, mas corre o risco de fechar o debate." }, { version: "Nota de estudo", approach: "Distingue leituras", note: "Relaciona o verso ao conjunto das bem-aventuranças e às reversões sociais de Mateus." }], textualNote: "A comparação deve evitar tanto espiritualizar a pobreza quanto reduzir o verso a um programa sociológico isolado.", sources: [{ label: "Society of Biblical Literature", url: "https://www.sbl-site.org/" }] },
  { id: "jo-1-1", reference: "João 1:1", title: "Logos, relação e identidade", originalIssue: "A ordem e a ausência de artigo definido na última oração grega geram traduções e debates teológicos.", context: "O prólogo de João combina linguagem de criação, sabedoria, testemunho e encarnação.", rows: [{ version: "Tradução tradicional", approach: "Usa ‘Verbo’", note: "Carrega uma longa história teológica e filosófica em português." }, { version: "Tradução transparente", approach: "Usa ‘Palavra’", note: "Ajuda o leitor contemporâneo a perceber a ideia de discurso e revelação." }, { version: "Nota de método", approach: "Evita argumento isolado de artigo", note: "Explica que sintaxe, contexto e teologia do prólogo importam juntos." }], textualNote: "A tradução de logos é uma decisão de interpretação; a interface deve mostrar as consequências sem declarar que uma palavra portuguesa contém todo o campo grego.", sources: [{ label: "Yale — recursos de crítica textual e estudos do NT", url: "https://guides.library.yale.edu/newtestament/textualcriticism" }] },
  { id: "rm-3-22", reference: "Romanos 3:22", title: "Pistis Christou: fé em Cristo ou fidelidade de Cristo?", originalIssue: "A construção grega pode ser lida como genitivo objetivo ou subjetivo.", context: "Paulo articula justiça de Deus, fé, inclusão de judeus e gentios e o problema da vanglória.", rows: [{ version: "Leitura objetiva", approach: "Fé em Cristo", note: "Enfatiza a resposta humana de confiança no Messias." }, { version: "Leitura subjetiva", approach: "Fidelidade de Cristo", note: "Enfatiza a ação fiel de Cristo como fundamento da justiça de Deus." }, { version: "Leitura integrada", approach: "Mantém a tensão", note: "Reconhece que o argumento paulino pode relacionar a fidelidade de Cristo e a fé dos que participam dele." }], textualNote: "A diferença não é resolvida apenas por dicionário; exige sintaxe, argumento da carta e comparação com outras ocorrências paulinas.", sources: [{ label: "Society of Biblical Literature", url: "https://www.sbl-site.org/" }] },
  { id: "ap-13-18", reference: "Apocalipse 13:18", title: "Número, nome e cálculo", originalIssue: "O número da besta depende de práticas antigas de cálculo de nomes e de hipóteses sobre a referência histórica.", context: "A cena participa de uma crítica simbólica ao poder imperial e à adoração. O texto convida ao discernimento, não ao cálculo de manchetes contemporâneas.", rows: [{ version: "Tradução formal", approach: "Preserva número e sabedoria", note: "Mantém a instrução para que o leitor calcule o número." }, { version: "Comentário histórico", approach: "Compara gematria e candidatos antigos", note: "Apresenta hipóteses como Nero César e outras propostas com limites." }, { version: "Leitura pentecostal responsável", approach: "Discernimento sem datação", note: "Relaciona idolatria, poder e perseverança sem transformar especulação em profecia certa." }], textualNote: "O texto pede sabedoria e resistência; o método da plataforma registra convergências, divergências e incertezas.", sources: [{ label: "Bible Odyssey — tradição e cânon", url: "https://www.bibleodyssey.org/articles/the-new-testament-canon/" }] },
];
