// Cartografia de Leituras: comentários focais desenvolvidos e um mapa honesto de cobertura por livro.

import { bibleBooks } from "@/lib/bible-data";

export type VerseCommentary = {
  id: string;
  book: string;
  chapter: number;
  verses: string;
  title: string;
  textLayer: string;
  contextLayer: string;
  interpretationLayer: string;
  pentecostalLayer: string;
  references: string[];
  source: { label: string; url: string };
};

export type BookCoverage = {
  book: string;
  chapters: number;
  status: "Foco detalhado" | "Índice em expansão";
  note: string;
};

const bibleOdyssey = "https://www.bibleodyssey.org/articles/why-does-the-bible-look-the-way-it-does/";
const sbl = "https://www.sbl-site.org/";

export const verseCommentaries: VerseCommentary[] = [
  { id: "gn-1-1-5", book: "Gênesis", chapter: 1, verses: "1–5", title: "Criação como separação, nomeação e ordem", textLayer: "O relato abre com uma cena de escuridão, águas e a ação criadora de Deus por palavra. A repetição de ‘e disse’, ‘separou’, ‘chamou’ e ‘viu’ constrói um mundo inteligível e habitável.", contextLayer: "A linguagem conversa com cosmologias do antigo Oriente Próximo, mas desloca o foco: não há batalha divina narrada como origem do cosmos, e os astros aparecem posteriormente como elementos ordenados, não como deuses.", interpretationLayer: "O texto não funciona apenas como cronograma físico. Sua forma litúrgica e repetitiva confessa que a criação é boa, ordenada e dependente da palavra de Deus, ao mesmo tempo em que deixa perguntas sobre composição e relação com outros relatos antigos.", pentecostalLayer: "Uma leitura pentecostal pode afirmar a soberania criadora de Deus e a dignidade da criação sem usar o texto para encerrar debates científicos que pertencem a outros campos. O testemunho teológico é forte; a cronologia material requer método próprio.", references: ["Jo 1:1–5", "2Co 4:6", "Ap 21:1–5"], source: { label: "Society of Biblical Literature", url: sbl } },
  { id: "gn-3-1-7", book: "Gênesis", chapter: 3, verses: "1–7", title: "A queda como ruptura de confiança e percepção", textLayer: "A serpente reorganiza a palavra recebida, a mulher avalia o fruto e o casal percebe a nudez. A narrativa trabalha com desejo, voz, limite e vergonha antes de qualquer formulação sistemática sobre pecado.", contextLayer: "Serpentes possuem significados ambivalentes no antigo Oriente Próximo. No relato de Gênesis, ela não é apresentada como um deus rival, mas como personagem astuto que tensiona a confiança na palavra divina.", interpretationLayer: "O texto descreve uma ruptura que se espalha para relações, trabalho, corpo e território. Ler a queda apenas como culpa individual perde a dimensão social e cósmica que os capítulos seguintes desenvolvem.", pentecostalLayer: "A leitura pentecostal reconhece a realidade do pecado e a necessidade de reconciliação, mas deve resistir a usar o texto para culpar um sexo, um povo ou a materialidade do corpo. O chamado é discernimento, responsabilidade e restauração.", references: ["Rm 5:12–21", "2Co 11:3", "Ap 12:9"], source: { label: "Bible Odyssey — cânon e tradições", url: bibleOdyssey } },
  { id: "ex-3-1-12", book: "Êxodo", chapter: 3, verses: "1–12", title: "Vocação, memória e presença na libertação", textLayer: "A sarça ardente combina visão, chamado, memória dos antepassados e envio. Deus não entrega a Moisés apenas uma ideia; apresenta uma presença que escuta o clamor e o envia de volta ao lugar de opressão.", contextLayer: "A narrativa de vocação se encaixa em padrões antigos de comissão profética, mas articula a identidade de Deus com a história de um povo escravizado e com a política do faraó.", interpretationLayer: "O ‘eu estarei contigo’ é a resposta imediata à insegurança de Moisés. A missão não depende da autossuficiência do mediador, e a libertação bíblica não é separável de memória, justiça e reorganização comunitária.", pentecostalLayer: "Para a tradição pentecostal, o texto continua convocando pessoas para uma missão dependente da presença de Deus. Essa aplicação precisa ser discernida comunitariamente e não pode transformar todo desejo pessoal em mandato divino.", references: ["At 7:30–34", "Mt 22:31–32", "Hb 11:23–29"], source: { label: "Leon Levy Dead Sea Scrolls Digital Library", url: "https://www.deadseascrolls.org.il/?locale=en_US" } },
  { id: "mt-5-1-12", book: "Mateus", chapter: 5, verses: "1–12", title: "Bem-aventuranças e inversão do status", textLayer: "Jesus chama bem-aventuradas pessoas descritas por pobreza, luto, mansidão, fome de justiça, misericórdia, pureza, pacificação e perseguição. O texto não romantiza automaticamente a dor; anuncia uma reordenação do horizonte de Deus.", contextLayer: "As bem-aventuranças dialogam com salmos, profetas e expectativas do reino. O auditório vive em um mundo de honra, patronagem, violência e tributação, de modo que a promessa tem peso social e escatológico.", interpretationLayer: "O conjunto deve ser lido com as antíteses e as práticas do Sermão do Monte. ‘Reino dos céus’ não é fuga da terra, mas linguagem de governo de Deus que reeduca desejo, justiça e relação com inimigos.", pentecostalLayer: "A leitura pentecostal pode unir esperança escatológica e presença atual do reino, permitindo que a igreja console, pratique misericórdia e busque justiça sem reduzir a promessa a prosperidade ou a sofrimento como mérito.", references: ["Is 61:1–3", "Lc 6:20–26", "Tg 2:1–7"], source: { label: "Bible Odyssey — cânon e tradições", url: bibleOdyssey } },
  { id: "jo-1-1-18", book: "João", chapter: 1, verses: "1–18", title: "O Logos entre criação, testemunho e encarnação", textLayer: "O prólogo passa da Palavra junto de Deus à Palavra que se faz carne, articulando criação, vida, luz, testemunho e graça. A passagem é poética e argumentativa ao mesmo tempo.", contextLayer: "O texto conversa com a linguagem sapiencial judaica e com o vocabulário grego de logos, mas o utiliza dentro de uma narrativa de revelação e conflito. A relação com Gênesis é marcada pela abertura ‘no princípio’.", interpretationLayer: "A encarnação impede que a revelação seja tratada como abstração. O Logos é reconhecido na história, na carne e no testemunho; a cristologia joanina nasce da combinação entre preexistência e presença concreta.", pentecostalLayer: "A teologia pentecostal pode ligar o Logos encarnado à ação vivificante do Espírito, mantendo a distinção entre Cristo e o Espírito e evitando linguagem que dissolva a humanidade real de Jesus.", references: ["Gn 1:1–5", "1Jo 1:1–4", "Ap 19:13"], source: { label: "Yale — guia de estudos textuais do NT", url: "https://guides.library.yale.edu/newtestament/textualcriticism" } },
  { id: "at-2-1-21", book: "Atos", chapter: 2, verses: "1–21", title: "Pentecostes como linguagem pública e missão", textLayer: "O vento, o fogo, as línguas e o discurso de Pedro transformam uma experiência comunitária em testemunho público. A citação de Joel interpreta o acontecimento como derramamento do Espírito sobre pessoas de diferentes idades e posições.", contextLayer: "Jerusalém está cheia de peregrinos e línguas da diáspora. A narrativa aproveita a festa e a diversidade linguística para apresentar a missão como comunicação inteligível, não como espetáculo privado.", interpretationLayer: "O episódio não deve ser separado do restante de Atos: o Espírito produz testemunho, partilha, conflito, discernimento e fronteiras ampliadas. A experiência carismática é orientada para Cristo e para a formação de uma comunidade.", pentecostalLayer: "A perspectiva pentecostal da IDB encontra aqui a afirmação do batismo no Espírito e dos dons, mas o próprio texto pede fruto missionário, edificação, arrependimento, justiça comunitária e centralidade de Jesus.", references: ["Jl 2:28–32", "Lc 24:49", "1Co 12:4–13"], source: { label: "Society of Biblical Literature", url: sbl } },
  { id: "rm-8-18-30", book: "Romanos", chapter: 8, verses: "18–30", title: "Criação, gemido e esperança corporificada", textLayer: "Paulo descreve criação, comunidade e Espírito como sujeitos que gemem e aguardam. A esperança inclui redenção do corpo e não apenas sobrevivência da alma.", contextLayer: "A linguagem de parto, adoção e primícias reúne imagens judaicas de restauração e a experiência de comunidades que vivem entre sofrimento presente e promessa futura.", interpretationLayer: "O texto não oferece uma fórmula para explicar cada sofrimento. Ele reconfigura a dor em uma espera ativa, intercessora e escatológica, na qual a criação participa do drama da redenção.", pentecostalLayer: "Uma leitura pentecostal pode relacionar o gemido do Espírito à oração e à esperança, sem usar a promessa para negar doença, luto ou responsabilidade ambiental. O Espírito sustenta perseverança e compaixão.", references: ["Gn 3:17–19", "2Co 5:1–5", "Ap 21:1–5"], source: { label: "Bible Odyssey — investigação bíblica", url: bibleOdyssey } },
  { id: "ap-13-1-18", book: "Apocalipse", chapter: 13, verses: "1–18", title: "Besta, poder imperial e discernimento", textLayer: "A besta emerge do mar, recebe autoridade do dragão e combina violência, adoração e marca econômica. O capítulo trabalha com paródia de poder e com uma comunidade pressionada a reconhecer quem realmente governa.", contextLayer: "A imagem combina Daniel 7 com experiências de império, culto e coerção. A identificação histórica exata do referente é debatida, mas o vocabulário de adoração e dominação é central.", interpretationLayer: "O texto critica sistemas que exigem lealdade total e convertem economia em instrumento de culto. As escolas preterista, historicista, futurista, idealista e eclética iluminam dimensões diferentes, mas nenhuma autoriza cálculo infalível de datas.", pentecostalLayer: "O discernimento pentecostal precisa denunciar idolatria, violência e manipulação religiosa sem transformar qualquer adversário político em ‘besta’. A fidelidade é medida por testemunho, santidade, perseverança e esperança em Cristo.", references: ["Dn 7:1–8", "2Ts 2:1–12", "Ap 14:9–12"], source: { label: "Bible Odyssey — cânon e tradições", url: "https://www.bibleodyssey.org/articles/the-new-testament-canon/" } },
];

export const bookCoverage: BookCoverage[] = bibleBooks.map(book => ({ book: book.name, chapters: book.chapters, status: verseCommentaries.some(comment => comment.book === book.name) ? "Foco detalhado" : "Índice em expansão", note: verseCommentaries.some(comment => comment.book === book.name) ? "Há comentários focais com separação entre texto, contexto e interpretação." : "O catálogo de capítulos e o leitor exegético já existem; o lote versículo por versículo será ampliado sem apresentar cobertura inexistente como concluída." }));
