/* Cartografia de Leituras: biblioteca profunda para leitores que já conhecem o básico. */
import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, ArrowRight, BookOpen, CircleHelp, ExternalLink, FileText, GitBranch, Search, ShieldCheck } from "lucide-react";
import { Streamdown } from "streamdown";
import { Input } from "@/components/ui/input";
import { bibleBooks, bibleCategories, type Book } from "@/lib/bible-data";
import { ADVANCED_BOOK_DOSSIERS_URL, canonicalBookKey, normalizeAdvancedBookPayload, type AdvancedBookDossier } from "@/lib/advanced-book-data";
import ExegesisBookReader from "@/components/ExegesisBookReader";

function linkify(text: string) {
  return text.split(/(https?:\/\/[^\s)]+)/g).map((part, index) => part.startsWith("http") ? <a key={`${part}-${index}`} href={part} target="_blank" rel="noreferrer">{part}</a> : <span key={`${part}-${index}`}>{part}</span>);
}

function sourceList(value: string) {
  return <ol className="source-list">{value.split(/;\s*/).filter(Boolean).map((source, index) => <li key={`${source}-${index}`}>{linkify(source)}</li>)}</ol>;
}

function BookDossier({ book, dossier, close, onOpenBook }: { book: Book; dossier: AdvancedBookDossier; close: () => void; onOpenBook: (name: string) => void }) {
  const [tab, setTab] = useState<"dossier" | "exegesis" | "primary" | "bibliography" | "limits">("dossier");
  return <section className="advanced-book-detail page-section"><button className="back-action" onClick={close}><ArrowLeft size={15} /> Voltar aos 66 dossiês</button><div className="advanced-book-heading"><div><span className="advanced-book-kicker">{book.testament} · {book.category} · {book.chapters} capítulos</span><h1>{book.name}</h1><p>{book.summary}</p></div><div className="advanced-book-seal"><strong>{String(bibleBooks.findIndex(item => item.id === book.id) + 1).padStart(2, "0")}</strong><span>/ 66<br />dossiê</span></div></div><div className="advanced-book-meta"><div><span>Autoria na ficha geral</span><strong>{book.author}</strong></div><div><span>Período indicado</span><strong>{book.period}</strong></div><div><span>Temas indexados</span><strong>{book.themes.join(" · ")}</strong></div></div><div className="advanced-book-tabs" role="tablist">{[["dossier", "Dossiê analítico", FileText], ["exegesis", "Exegese capítulo a capítulo", GitBranch], ["primary", "Fontes primárias", BookOpen], ["bibliography", "Bibliografia", ExternalLink], ["limits", "Limites e confiança", ShieldCheck]].map(([id, label, Icon]) => <button key={id as string} className={tab === id ? "is-active" : ""} onClick={() => setTab(id as typeof tab)} role="tab" aria-selected={tab === id}><Icon size={15} />{label as string}</button>)}</div><article className="advanced-book-reading">{tab === "dossier" && <Streamdown>{dossier.dossier_markdown}</Streamdown>}{tab === "exegesis" && <ExegesisBookReader book={book} onOpenBook={onOpenBook} />}{tab === "primary" && <div className="source-panel"><h2>Fontes primárias e testemunhos antigos</h2><p>As referências abaixo são pontos de partida para comparar o texto bíblico com inscrições, manuscritos, historiadores antigos e outros testemunhos. A existência de uma fonte não prova automaticamente uma correlação.</p>{sourceList(dossier.primary_sources)}</div>}{tab === "bibliography" && <div className="source-panel"><h2>Bibliografia acadêmica</h2><p>Use estas obras para aprofundar autoria, composição, história, literatura e recepção do livro. Links externos abrem em nova aba.</p>{sourceList(dossier.academic_bibliography)}</div>}{tab === "limits" && <div className="source-panel source-panel--limits"><h2>Confiança, limites e controvérsias</h2><p>{dossier.confidence_limits}</p><div className="method-legend"><span><i className="legend-dot legend-dot--blue" /> Texto e evidência</span><span><i className="legend-dot legend-dot--wine" /> Interpretação</span><span><i className="legend-dot legend-dot--gold" /> Hipótese ou tradição</span></div></div>}</article></section>;
}

export default function AdvancedBookLibrary() {
  const [records, setRecords] = useState<Record<string, AdvancedBookDossier>>({});
  const [query, setQuery] = useState("");
  const [testament, setTestament] = useState("Todos");
  const [category, setCategory] = useState("Todos");
  const [selected, setSelected] = useState<Book | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  useEffect(() => { fetch(ADVANCED_BOOK_DOSSIERS_URL).then(response => { if (!response.ok) throw new Error("Não foi possível carregar os dossiês avançados."); return response.json(); }).then(payload => setRecords(normalizeAdvancedBookPayload(payload))).catch(reason => setError(reason instanceof Error ? reason.message : "Falha ao carregar os dossiês.")).finally(() => setLoading(false)); }, []);
  const books = useMemo(() => bibleBooks.filter(book => { const text = [book.name, book.author, book.category, book.summary, book.period, ...book.themes].join(" ").toLowerCase(); const normalized = query.toLowerCase().trim(); return (!normalized || text.includes(normalized)) && (testament === "Todos" || book.testament === testament) && (category === "Todos" || book.category === category); }), [query, testament, category]);
  const openBookByName = (name: string) => { const target = bibleBooks.find(item => canonicalBookKey(item.name) === canonicalBookKey(name)); if (target) setSelected(target); };
  if (selected) { const dossier = records[canonicalBookKey(selected.name)]; return dossier ? <BookDossier book={selected} dossier={dossier} close={() => setSelected(null)} onOpenBook={openBookByName} /> : <section className="page-section"><button className="back-action" onClick={() => setSelected(null)}><ArrowLeft size={15} /> Voltar</button><div className="empty-state"><CircleHelp size={30} /><h3>Dossiê ainda não carregado</h3><p>{selected.name} permanece disponível na ficha resumida enquanto a fonte é atualizada.</p></div></section>; }
  return <section className="page-section advanced-library-page"><div className="page-intro"><div className="section-eyebrow"><span className="eyebrow-line" /><span className="eyebrow-number">05</span><span>66 dossiês histórico-teológicos</span></div><div className="page-title-row"><div><h1>Os 66 livros<br /><em>sem atalhos.</em></h1><p>Cada livro agora é estudado como documento literário, histórico, teológico e situado em redes de pessoas, lugares, impérios e tradições.</p></div><div className="result-count"><strong>{Object.keys(records).length || 66}</strong><span>dossiês<br />disponíveis</span></div></div></div><div className="advanced-library-note"><ShieldCheck size={18} /><span>O conteúdo avançado separa texto, evidência, reconstrução histórica, interpretação pentecostal, posição IDB e hipótese acadêmica.</span></div><div className="library-toolbar"><div className="search-wrap"><Search size={17} /><Input value={query} onChange={event => setQuery(event.target.value)} placeholder="Buscar livro, autor, tema ou período..." aria-label="Buscar nos dossiês avançados" /></div><div className="filter-cluster"><select value={testament} onChange={event => setTestament(event.target.value)} aria-label="Filtrar por testamento"><option>Todos</option><option>Antigo Testamento</option><option>Novo Testamento</option></select><select value={category} onChange={event => setCategory(event.target.value)} aria-label="Filtrar por categoria"><option>Todos</option>{bibleCategories.map(item => <option key={item}>{item}</option>)}</select></div></div>{loading && <div className="advanced-loading">Carregando 66 dossiês e suas referências...</div>}{error && <div className="map-error-banner"><CircleHelp size={15} />{error}</div>}<div className="advanced-book-grid">{books.map((book, index) => <button className="advanced-book-card" key={book.id} onClick={() => setSelected(book)}><div className="advanced-book-card-top"><span>{String(index + 1).padStart(2, "0")}</span><span>{book.testament === "Novo Testamento" ? "NT" : "AT"} · {book.short}</span></div><h2>{book.name}</h2><p>{book.summary}</p><div className="advanced-book-card-foot"><span>{book.category}</span><span>{records[canonicalBookKey(book.name)] ? "Dossiê completo" : "Ficha de orientação"}<ArrowRight size={14} /></span></div></button>)}</div></section>;
}
