// Cartografia de Leituras: cada corpus é uma estação de rota, não um cartão isolado.
import { useMemo, useState } from "react";
import { ArrowRight, BookMarked, ExternalLink, Layers3, ScrollText, ShieldCheck } from "lucide-react";
import { apocryphaEntries, apocryphaSources, canonLenses, type ApocryphaEntry, type CanonLens } from "@/lib/apocrypha-data";
import { apocryphaArticles, type GuidedArticle } from "@/lib/encyclopedic-reading-data";
import { CloseReadingTrack } from "@/components/CloseReadingTrack";
import type { JourneyView } from "@/components/JourneyNavigator";
import "@/apocrypha-hub.css";
import "@/encyclopedic-reading.css";

export default function ApocryphaHub({ go }: { go: (view: JourneyView) => void }) {
  const [lens, setLens] = useState<CanonLens | "all">("all");
  const [activeId, setActiveId] = useState(apocryphaEntries[0].id);
  const entries = useMemo(() => lens === "all" ? apocryphaEntries : apocryphaEntries.filter(entry => entry.lenses.includes(lens)), [lens]);
  const active = entries.find(entry => entry.id === activeId) || entries[0];
  return <section className="apocrypha-hub page-section">
    <header className="apocrypha-hub__hero"><div><span className="apocrypha-hub__kicker"><ScrollText size={14} /> Literatura do Segundo Templo, recepção e cânon</span><h1>Textos que moldaram<br /><em>o mundo da Bíblia.</em></h1><p>Este é um dossiê enciclopédico de dez corpora: narrativas, sabedoria, oração, resistência, versões gregas e apocalíptica judaica. Cada entrada localiza o texto, percorre seus movimentos internos, identifica personagens, debates de recepção e suas conexões com a Escritura.</p></div><div className="apocrypha-hub__seal"><strong>10</strong><span>corpora<br />documentados</span></div></header>
    <section className="apocrypha-hub__method"><ShieldCheck size={18} /><div><strong>Leitura em camadas, não resumo</strong><p>Selecione um corpus e percorra cinco movimentos de leitura. Em cada parada há cena, tese, pessoa ou lugar, conexão bíblica e termo técnico; depois, compare a recepção católica, ortodoxa e protestante.</p></div><button type="button" onClick={() => go("canon")}>Comparar tradições canônicas <ArrowRight size={15} /></button></section>
    <div className="atlas-route-ledger apocrypha-route-ledger" aria-label="Rota de leitura dos apócrifos"><span>Rota 03 · arquivo intertestamentário</span><strong>Corpus <i /> cenas <i /> recepção <i /> fontes</strong><em>05 estações por dossiê</em></div>
    <div className="apocrypha-hub__layout"><aside className="apocrypha-hub__index"><span>Filtro de recepção</span><button type="button" className={lens === "all" ? "is-active" : ""} onClick={() => setLens("all")}>Todas as coleções <em>{apocryphaEntries.length}</em></button>{canonLenses.map(item => <button type="button" key={item.id} className={lens === item.id ? "is-active" : ""} onClick={() => setLens(item.id)}><div><strong>{item.label}</strong><small>{item.note}</small></div><em>{apocryphaEntries.filter(entry => entry.lenses.includes(item.id)).length}</em></button>)}<div className="apocrypha-hub__index-note"><Layers3 size={15} /> Filtrar não decide autoridade; apenas mostra como as coleções são recebidas e estudadas.</div></aside>
      <main className="apocrypha-hub__content"><div className="apocrypha-hub__catalog-head"><div><span>Selecione um corpus</span><h2>{entries.length} corpora para <em>estudar a fundo.</em></h2></div><p>Não há cartão de resumo: cada dossiê abre uma tese, cinco movimentos internos e seis camadas de interpretação e recepção.</p></div><div className="apocrypha-hub__catalog">{entries.map((entry, index) => <button type="button" key={entry.id} className={entry.id === active.id ? "is-active" : ""} onClick={() => setActiveId(entry.id)}><span>{String(index + 1).padStart(2, "0")}</span><div><small>{entry.collection} · {entry.period}</small><strong>{entry.title}</strong><em>{entry.genre}</em></div><ArrowRight size={15} /></button>)}</div>{active && <ApocryphaDetail key={active.id} entry={active} article={apocryphaArticles[active.id]} />}</main></div>
    <footer className="apocrypha-hub__sources"><div><span>Rastro de pesquisa</span><h2>Continue pelas <em>fontes.</em></h2></div><div>{apocryphaSources.map(source => <a href={source.url} target="_blank" rel="noreferrer" key={source.url}><ExternalLink size={15} /><span><small>{source.kind}</small>{source.label}</span><ArrowRight size={14} /></a>)}</div></footer>
  </section>;
}

function ApocryphaDetail({ entry, article }: { entry: ApocryphaEntry; article: GuidedArticle }) {
  const [stage, setStage] = useState<GuideStage>("start");
  return <article className="apocrypha-detail"><header><div><span>{entry.collection}</span><h2>{entry.title}</h2><p>{article.firstAnswer}</p></div><BookMarked size={28} /></header><EncyclopediaGuide article={article} stage={stage} setStage={setStage} readingId={entry.id} /><footer><span>Âncoras de leitura</span><strong>{entry.references}</strong></footer></article>;
}

type GuideStage = "start" | "story" | "meaning" | "people" | "connections" | "advance";
const guideSteps: { id: GuideStage; label: string }[] = [{ id: "start", label: "Comece aqui" }, { id: "story", label: "O que acontece" }, { id: "meaning", label: "O que significa" }, { id: "people", label: "Quem aparece" }, { id: "connections", label: "Conexões" }, { id: "advance", label: "Aprofundar" }];

export function EncyclopediaGuide({ article, stage, setStage, readingId }: { article: GuidedArticle; stage: GuideStage; setStage: (stage: GuideStage) => void; readingId?: string }) {
  return <section className="encyclopedia-guide"><nav className="encyclopedia-guide__nav" aria-label="Etapas de leitura do verbete">{guideSteps.map((step, index) => <button type="button" key={step.id} className={stage === step.id ? "is-active" : ""} onClick={() => setStage(step.id)}><i>{String(index + 1).padStart(2, "0")}</i><span>{step.label}</span></button>)}</nav><div className="encyclopedia-guide__body">{stage === "start" && <><span className="encyclopedia-guide__eyebrow">Em uma frase</span><h3>O que você precisa saber <em>primeiro.</em></h3><p className="encyclopedia-guide__lead">{article.firstAnswer}</p><div className="encyclopedia-guide__next">Agora siga para <strong>“O que acontece”</strong> e leia a história em partes.</div></>}{stage === "story" && <CloseReadingTrack readingId={readingId} article={article} />}{stage === "meaning" && <GuideCards eyebrow="Por que importa" title={<>O que o texto <em>quer comunicar.</em></>} items={article.meaning} />}{stage === "people" && <GuideCards eyebrow="Pessoas e lugares" title={<>Quem aparece e <em>por que importa.</em></>} items={article.peopleAndPlaces} />}{stage === "connections" && <><span className="encyclopedia-guide__eyebrow">Lendo junto</span><h3>Onde isso conversa <em>com a Bíblia.</em></h3><ul className="encyclopedia-guide__connections">{article.connections.map((item, index) => <li key={item}><b>{String(index + 1).padStart(2, "0")}</b><span>{item}</span></li>)}</ul></>}{stage === "advance" && <><span className="encyclopedia-guide__eyebrow">Termos, debates e recepção</span><h3>Agora você pode <em>aprofundar.</em></h3><div className="encyclopedia-guide__advance"><div><h4>Como as tradições o leem</h4>{article.receptionOrDebate.map(item => <p key={item}>{item}</p>)}</div><div><h4>Palavras para guardar</h4>{article.terms.map(term => <p key={term.word}><strong>{term.word}</strong>{term.meaning}</p>)}</div></div></>}</div></section>;
}

function GuideCards({ eyebrow, title, items }: { eyebrow: string; title: React.ReactNode; items: { label: string; text: string }[] }) { return <><span className="encyclopedia-guide__eyebrow">{eyebrow}</span><h3>{title}</h3><div className="encyclopedia-guide__cards">{items.map(item => <article key={item.label}><span>{item.label}</span><p>{item.text}</p></article>)}</div></>; }
