// Cartografia de Leituras: módulo 11 em formato de atlas escatológico, com contexto, comparação e discernimento.
import { useState } from "react";
import { ArrowRight, BookOpen, ChevronRight, ExternalLink, Eye, FileText, Map, ShieldCheck, Sparkles, Timer, Users } from "lucide-react";
import { apocalypseChapters, apocalypseSources, apocalypseUnits, interpretationSchools, millennialViews, revelationChurches } from "@/lib/apocalypse-data";

type ApocalypseTab = "comentario" | "capitulos" | "igrejas" | "escolas" | "consumacao" | "fontes";

export default function ApocalypseHub() {
  const [tab, setTab] = useState<ApocalypseTab>("comentario");
  const [unitIndex, setUnitIndex] = useState(0);
  const [chapterIndex, setChapterIndex] = useState(0);
  const [churchIndex, setChurchIndex] = useState(0);
  const [schoolIndex, setSchoolIndex] = useState(0);
  const unit = apocalypseUnits[unitIndex];
  const chapter = apocalypseChapters[chapterIndex];
  const church = revelationChurches[churchIndex];
  const school = interpretationSchools[schoolIndex];
  const tabs: { id: ApocalypseTab; label: string; icon: typeof BookOpen }[] = [
    { id: "comentario", label: "Comentário por blocos", icon: BookOpen },
    { id: "capitulos", label: "Capítulo a capítulo", icon: FileText },
    { id: "igrejas", label: "Sete igrejas", icon: Map },
    { id: "escolas", label: "Escolas de interpretação", icon: Eye },
    { id: "consumacao", label: "Milênio e consumação", icon: Timer },
    { id: "fontes", label: "Fontes e método", icon: FileText },
  ];

  return <section className="apocalypse-page page-section">
    <header className="apocalypse-hero">
      <div className="apocalypse-hero-copy">
        <div className="apocalypse-kicker"><span /> Módulo 11 · estudo escatológico</div>
        <h1>Apocalipse<br /><em>sem atalhos.</em></h1>
        <p>Uma investigação guiada pelas visões, símbolos, cidades, impérios, esperanças e teorias que formam o último livro da Bíblia.</p>
        <div className="apocalypse-hero-note"><ShieldCheck size={17} /><span>Contexto primeiro. Convicção depois. Nenhuma data será tratada como certeza.</span></div>
      </div>
      <div className="apocalypse-hero-mark"><strong>11</strong><span>unidades<br />de pesquisa</span></div>
    </header>
    <div className="apocalypse-stat-strip"><div><Sparkles size={16} /><strong>22</strong><span>capítulos indexados</span></div><div><Map size={16} /><strong>07</strong><span>cidades reais</span></div><div><Eye size={16} /><strong>05</strong><span>escolas comparadas</span></div><div><Users size={16} /><strong>04</strong><span>camadas de autoridade</span></div></div>
    <nav className="apocalypse-tabs" aria-label="Seções do módulo 11">{tabs.map(item => { const Icon = item.icon; return <button key={item.id} className={tab === item.id ? "is-active" : ""} onClick={() => setTab(item.id)} aria-pressed={tab === item.id}><Icon size={15} /><span>{item.label}</span><ChevronRight size={13} /></button>; })}</nav>

    {tab === "comentario" && <section className="apocalypse-panel apocalypse-commentary"><div className="apocalypse-panel-heading"><div><span className="apocalypse-section-label">Leitura progressiva</span><h2>Visão, <em>contexto</em> e resposta.</h2><p>Selecione um bloco. O comentário mostra o movimento do texto e uma pergunta de discernimento para não confundir símbolo com cronograma.</p></div><div className="apocalypse-panel-count"><strong>{String(unitIndex + 1).padStart(2, "0")}</strong><span>/ {apocalypseUnits.length}</span></div></div><div className="apocalypse-commentary-layout"><aside className="apocalypse-unit-list" aria-label="Unidades de comentário">{apocalypseUnits.map((item, index) => <button key={item.id} className={index === unitIndex ? "is-active" : ""} onClick={() => setUnitIndex(index)}><span>{String(index + 1).padStart(2, "0")}</span><div><small>{item.range}</small><strong>{item.title}</strong><em>{item.subtitle}</em></div><ChevronRight size={14} /></button>)}</aside><article className="apocalypse-unit-detail"><div className="apocalypse-unit-meta"><span>{unit.range}</span><span>Comentário editorial</span></div><h3>{unit.title}</h3><p className="apocalypse-unit-lede">{unit.summary}</p><div className="apocalypse-reference-box"><BookOpen size={16} /><div><span>Textos em diálogo</span><strong>{unit.scriptures}</strong></div></div><div className="apocalypse-method-box"><Eye size={16} /><div><span>Pergunta de discernimento</span><p>{unit.interpretiveNote}</p></div></div><div className="apocalypse-unit-nav"><button disabled={unitIndex === 0} onClick={() => setUnitIndex(current => Math.max(0, current - 1))}>Anterior</button><button disabled={unitIndex === apocalypseUnits.length - 1} onClick={() => setUnitIndex(current => Math.min(apocalypseUnits.length - 1, current + 1))}>Próxima unidade <ArrowRight size={14} /></button></div></article></div></section>}

    {tab === "capitulos" && <section className="apocalypse-panel apocalypse-chapters"><div className="apocalypse-panel-heading"><div><span className="apocalypse-section-label">Comentário sequencial</span><h2>Apocalipse,<br /><em>capítulo a capítulo.</em></h2><p>Uma ficha de orientação para cada capítulo. Ela indica movimento, textos em diálogo e uma pergunta de leitura antes do comentário ampliado.</p></div><div className="apocalypse-panel-count"><strong>{String(chapter.chapter).padStart(2, "0")}</strong><span>/ 22</span></div></div><div className="chapter-explorer"><div className="chapter-list" aria-label="Índice de capítulos">{apocalypseChapters.map((item, index) => <button key={item.chapter} className={index === chapterIndex ? "is-active" : ""} onClick={() => setChapterIndex(index)}><span>{String(item.chapter).padStart(2, "0")}</span><div><strong>{item.title}</strong><small>{item.refs}</small></div><ChevronRight size={14} /></button>)}</div><article className="chapter-detail"><div className="chapter-detail-top"><span>Apocalipse {chapter.chapter}</span><i>{String(chapter.chapter).padStart(2, "0")}</i></div><h3>{chapter.title}</h3><p>{chapter.summary}</p><div className="chapter-refs"><BookOpen size={16} /><div><span>Referências principais</span><strong>{chapter.refs}</strong></div></div><div className="chapter-reading-rule"><ShieldCheck size={15} /><p>Leia o capítulo em três movimentos: o que a visão comunica aos primeiros ouvintes, como suas imagens dialogam com o Antigo Testamento e que esperança ou advertência produz na comunidade.</p></div><div className="chapter-nav"><button disabled={chapterIndex === 0} onClick={() => setChapterIndex(current => Math.max(0, current - 1))}>Capítulo anterior</button><button disabled={chapterIndex === apocalypseChapters.length - 1} onClick={() => setChapterIndex(current => Math.min(apocalypseChapters.length - 1, current + 1))}>Próximo capítulo <ArrowRight size={14} /></button></div></article></div></section>}

    {tab === "igrejas" && <section className="apocalypse-panel apocalypse-churches"><div className="apocalypse-panel-heading"><div><span className="apocalypse-section-label">Cartografia da Ásia Menor</span><h2>Sete cidades,<br /><em>sete diagnósticos.</em></h2><p>As cidades são históricas; o sete também comunica totalidade. A interface mantém as duas camadas sem transformar a carta em uma biografia completa da igreja.</p></div><div className="apocalypse-map-legend"><i /> cidade no texto <i className="is-wine" /> tensão narrada</div></div><div className="church-explorer"><div className="church-map"><div className="church-map-grid" />{revelationChurches.map((item, index) => <button key={item.name} className={`church-map-point church-map-point--${index + 1} ${index === churchIndex ? "is-active" : ""}`} onClick={() => setChurchIndex(index)} aria-label={`Selecionar ${item.name}`}><span>{index + 1}</span>{item.name}</button>)}</div><div className="church-detail"><div className="church-detail-kicker">Carta {String(churchIndex + 1).padStart(2, "0")} · {church.city}</div><h3>{church.name}</h3><strong>{church.image}</strong><p>{church.text}</p><div className="church-context"><span>Contexto urbano</span><p>{church.location}</p></div><div className="church-caution"><Eye size={15} /><p>{church.caution}</p></div><div className="church-switcher">{revelationChurches.map((item, index) => <button key={item.name} className={index === churchIndex ? "is-active" : ""} onClick={() => setChurchIndex(index)}>{item.name}</button>)}</div></div></div></section>}

    {tab === "escolas" && <section className="apocalypse-panel apocalypse-schools"><div className="apocalypse-panel-heading"><div><span className="apocalypse-section-label">Cinco lentes</span><h2>Uma visão,<br /><em>várias leituras.</em></h2><p>Compare os modelos sem caricaturá-los. Cada lente ilumina uma dimensão e também possui limites.</p></div><div className="apocalypse-panel-count"><strong>{String(schoolIndex + 1).padStart(2, "0")}</strong><span>/ {interpretationSchools.length}</span></div></div><div className="school-layout"><div className="school-list">{interpretationSchools.map((item, index) => <button key={item.name} className={index === schoolIndex ? "is-active" : ""} onClick={() => setSchoolIndex(index)}><span>{String(index + 1).padStart(2, "0")}</span><div><strong>{item.name}</strong><small>{item.short}</small></div><ChevronRight size={14} /></button>)}</div><article className="school-detail"><div className="school-detail-top"><span>Escola selecionada</span><i>{String(schoolIndex + 1).padStart(2, "0")}</i></div><h3>{school.name}</h3><p className="school-core">{school.core}</p><div className="school-columns"><div><span>O que ilumina</span><p>{school.strength}</p></div><div><span>Onde exige cuidado</span><p>{school.tension}</p></div></div><div className="school-rule"><ShieldCheck size={15} /><p>Uma leitura madura pode reconhecer o horizonte original, a esperança futura e a função pastoral do livro sem forçar todos os símbolos em uma única explicação.</p></div></article></div></section>}

    {tab === "consumacao" && <section className="apocalypse-panel apocalypse-consummation"><div className="apocalypse-panel-heading"><div><span className="apocalypse-section-label">Ap 19–22</span><h2>Como as tradições<br /><em>entendem o fim?</em></h2><p>A consumação é confessada de formas diferentes. Compare o milênio sem transformar uma posição denominacional em consenso universal.</p></div></div><div className="millennial-grid">{millennialViews.map((item, index) => <article className={`millennial-card millennial-card--${index + 1}`} key={item.name}><span>Posição {String(index + 1).padStart(2, "0")}</span><h3>{item.name}</h3><p>{item.core}</p><strong>{item.keyText}</strong></article>)}</div><div className="tribulation-strip"><div><span>Declaração da Church of God</span><strong>Pré-milenista</strong><p>A declaração internacional consultada afirma a segunda vinda em duas etapas, a ressurreição dos justos, o arrebatamento e um reinado de mil anos.</p></div><div><span>Limite editorial</span><strong>Não marcar datas</strong><p>O módulo ensinará posições e argumentos, não previsões sobre governos, tecnologias ou acontecimentos atuais.</p></div></div></section>}

    {tab === "fontes" && <section className="apocalypse-panel apocalypse-sources"><div className="apocalypse-panel-heading"><div><span className="apocalypse-section-label">Método e referências</span><h2>Estude com<br /><em>discernimento.</em></h2><p>As fontes orientam o módulo; o site resumirá os argumentos sem substituir comentários especializados, Bíblias de estudo ou documentos confessionais completos.</p></div></div><div className="apocalypse-source-grid">{apocalypseSources.map((source, index) => <a key={source.url} href={source.url} target="_blank" rel="noreferrer"><span>{String(index + 1).padStart(2, "0")}</span><div><strong>{source.label}</strong><small>{source.url.replace(/^https?:\/\//, "")}</small></div><ExternalLink size={15} /></a>)}</div><div className="apocalypse-caution"><ShieldCheck size={18} /><div><strong>Regra de leitura</strong><p>O Apocalipse será lido como profecia, carta e apocalipse; com contexto do primeiro século, esperança de consumação e humildade diante das divergências.</p></div></div></section>}
  </section>;
}
