import { useState } from "react";
import { ArrowRight, BookOpen, ExternalLink, Landmark, MapPinned, ScrollText } from "lucide-react";
import { historyPeriods, type HistoryPeriod } from "@/lib/biblical-history-data";
import { historyArticles, type GuidedArticle } from "@/lib/encyclopedic-reading-data";
import { EncyclopediaGuide } from "@/components/ApocryphaHub";
import type { JourneyView } from "@/components/JourneyNavigator";
import "@/biblical-history.css";
import "@/encyclopedic-reading.css";

export default function BiblicalHistoryHub({ go }: { go: (view: JourneyView) => void }) {
  const [activeId, setActiveId] = useState(historyPeriods[0].id);
  const active = historyPeriods.find(period => period.id === activeId) || historyPeriods[0];
  return <section className="history-hub page-section"><header className="history-hub__hero"><div><span><Landmark size={14} /> História bíblica em ordem cronológica</span><h1>O que aconteceu?<br /><em>Depois, veja onde a Bíblia entra.</em></h1><p>Comece pela história simples de cada período. Em seguida, descubra como ela aparece nos livros bíblicos, quem viveu nela, por que ela importa e onde os historiadores ainda discutem.</p></div><div className="history-hub__meter"><strong>11</strong><span>períodos<br />conectados</span></div></header><div className="history-hub__legend"><MapPinned size={17} /><div><strong>Use três perguntas</strong><p>O que aconteceu? Onde isso aparece na Bíblia? Por que esse momento muda a leitura dos livros? As camadas avançadas ficam disponíveis quando você quiser.</p></div><button type="button" onClick={() => go("atlas")}>Ver os lugares no atlas <ArrowRight size={15} /></button></div><div className="history-hub__layout"><aside className="history-hub__rail"><span>Estações da história</span>{historyPeriods.map(period => <button type="button" key={period.id} className={period.id === active.id ? "is-active" : ""} onClick={() => setActiveId(period.id)}><i>{period.order}</i><div><small>{period.date}</small><strong>{period.label}</strong><em>{period.empire}</em></div></button>)}</aside><main className="history-hub__main"><HistoryDetail key={active.id} period={active} article={historyArticles[active.id]} go={go} /></main></div><footer className="history-hub__footer"><ScrollText size={19} /><p>Datas e fronteiras são aproximações didáticas. Primeiro acompanhe a história; depois, quando quiser, compare texto, arqueologia, inscrições e debates.</p><button type="button" onClick={() => go("bibliography")}>Abrir bibliografia acadêmica <BookOpen size={15} /></button></footer></section>;
}

function HistoryDetail({ period, article, go }: { period: HistoryPeriod; article: GuidedArticle; go: (view: JourneyView) => void }) { const [stage, setStage] = useState<"start" | "story" | "meaning" | "people" | "connections" | "advance">("start"); return <article className="history-detail"><header><div><span>Estação {period.order} · {period.date}</span><h2>{period.label}</h2><p>{article.firstAnswer}</p></div><div className="history-detail__empire"><small>Força no horizonte</small><strong>{period.empire}</strong></div></header><EncyclopediaGuide article={article} stage={stage} setStage={setStage} readingId={period.id} /><section className="history-detail__layers"><div><span>Onde a Bíblia entra</span><p>{period.textLayer}</p></div><div><span>Fontes e vestígios</span><p>{period.evidence}</p></div><div><span>Debate e limite</span><p>{period.debate}</p></div></section><footer><a href={period.sourceUrl} target="_blank" rel="noreferrer"><ExternalLink size={15} /> {period.source}</a><button type="button" onClick={() => go(period.destination)}>{period.destinationLabel} <ArrowRight size={15} /></button></footer></article>; }
