import { useState } from "react";
import { ArrowRight, BookOpen, ExternalLink, Landmark, MapPinned, ScrollText } from "lucide-react";
import { historyPeriods, type HistoryPeriod } from "@/lib/biblical-history-data";
import type { JourneyView } from "@/components/JourneyNavigator";
import "@/biblical-history.css";

export default function BiblicalHistoryHub({ go }: { go: (view: JourneyView) => void }) {
  const [activeId, setActiveId] = useState(historyPeriods[0].id);
  const active = historyPeriods.find(period => period.id === activeId) || historyPeriods[0];
  return <section className="history-hub page-section"><header className="history-hub__hero"><div><span><Landmark size={14} /> História bíblica em ordem cronológica</span><h1>Textos, povos e impérios.<br /><em>Antes de uma conclusão.</em></h1><p>Uma rota de contexto para acompanhar a Bíblia como memória, literatura e recepção dentro de paisagens históricas reais — sem fazer da arqueologia uma prova automática ou da narrativa uma simples crônica.</p></div><div className="history-hub__meter"><strong>11</strong><span>períodos<br />conectados</span></div></header><div className="history-hub__legend"><MapPinned size={17} /><div><strong>Como usar a cronologia</strong><p>Em cada estação, compare quatro camadas: a narrativa bíblica, fontes materiais ou documentais, debate histórico e rota de pesquisa.</p></div><button onClick={() => go("atlas")}>Abrir atlas em camadas <ArrowRight size={15} /></button></div><div className="history-hub__layout"><aside className="history-hub__rail"><span>Estações da história</span>{historyPeriods.map(period => <button key={period.id} className={period.id === active.id ? "is-active" : ""} onClick={() => setActiveId(period.id)}><i>{period.order}</i><div><small>{period.date}</small><strong>{period.label}</strong><em>{period.empire}</em></div></button>)}</aside><main className="history-hub__main"><HistoryDetail period={active} go={go} /></main></div><footer className="history-hub__footer"><ScrollText size={19} /><p>Datas e fronteiras são aproximações didáticas. O objetivo é tornar visíveis as perguntas que mudam quando texto, arqueologia, inscrições, memória e tradição são lidos em conjunto.</p><button onClick={() => go("bibliography")}>Abrir bibliografia acadêmica <BookOpen size={15} /></button></footer></section>;
}

function HistoryDetail({ period, go }: { period: HistoryPeriod; go: (view: JourneyView) => void }) { return <article className="history-detail"><header><div><span>Estação {period.order} · {period.date}</span><h2>{period.label}</h2><p>{period.narrative}</p></div><div className="history-detail__empire"><small>Força no horizonte</small><strong>{period.empire}</strong></div></header><section className="history-detail__layers"><div><span>Texto e memória</span><p>{period.textLayer}</p></div><div><span>Fontes e vestígios</span><p>{period.evidence}</p></div><div><span>Debate e limite</span><p>{period.debate}</p></div></section><footer><a href={period.sourceUrl} target="_blank" rel="noreferrer"><ExternalLink size={15} /> {period.source}</a><button onClick={() => go(period.destination)}>{period.destinationLabel} <ArrowRight size={15} /></button></footer></article>; }
