/* Cartografia de Leituras: Gênesis é apresentado como uma rede pesquisável, não como uma ficha isolada. */
import { useMemo, useState } from "react";
import { ArrowLeft, ArrowRight, BookOpen, Compass, ExternalLink, FileText, GitBranch, Map, Search, ShieldCheck, Sparkles, Users } from "lucide-react";
import { toast } from "sonner";
import { bibleBooks, type Book } from "@/lib/bible-data";
import { genesisArcs, genesisChapterBands, genesisContinuity, genesisEntities, genesisEvents, genesisPlaces, genesisProphecies, genesisSources, type GenesisEntityType } from "@/lib/genesis-relational-data";
import EntityPanel from "@/components/EntityPanel";
import { getAllKnowledgeEntities, normalizeEntityKey } from "@/lib/entity-graph";
import "@/entity-link-controls.css";

type Props = { book: Book; saved: boolean; save: () => void; close: () => void; openBook: (book: Book) => void; note: string; setNote: (value: string) => void };
type Panel = "overview" | "people" | "events" | "map" | "prophecy" | "continuity" | "sources";

export default function GenesisRelationalDetail({ book, saved, save, close, openBook, note, setNote }: Props) {
  const [panel, setPanel] = useState<Panel>("overview");
  const [entityType, setEntityType] = useState<GenesisEntityType | "Todos">("Todos");
  const [query, setQuery] = useState("");
  const [selectedEntity, setSelectedEntity] = useState(genesisEntities[0]);
  const [selectedPlace, setSelectedPlace] = useState(genesisPlaces[0]);
  const [selectedEvent, setSelectedEvent] = useState(genesisEvents[0]);
  const [entityId, setEntityId] = useState<string | null>(null);
  const filteredEntities = useMemo(() => genesisEntities.filter(entity => (entityType === "Todos" || entity.type === entityType) && (!query.trim() || `${entity.name} ${entity.role} ${entity.summary} ${entity.tags.join(" ")}`.toLowerCase().includes(query.toLowerCase().trim()))), [entityType, query]);
  const tabs: { id: Panel; label: string; icon: typeof BookOpen }[] = [
    { id: "overview", label: "Visão integral", icon: BookOpen },
    { id: "people", label: "Pessoas e povos", icon: Users },
    { id: "events", label: "Eventos e capítulos", icon: GitBranch },
    { id: "map", label: "Mapa de Gênesis", icon: Map },
    { id: "prophecy", label: "Profecias e ecos", icon: Sparkles },
    { id: "continuity", label: "Do início ao fim", icon: ArrowRight },
    { id: "sources", label: "Fontes", icon: FileText },
  ];
  const connectBook = (name: string) => { const target = bibleBooks.find(item => item.name === name); if (target) openBook(target); else toast.info(`${name} será conectado na próxima camada.`); };
  const openEntity = (label: string) => { const normalized = normalizeEntityKey(label); const id = getAllKnowledgeEntities().find(entity => [entity.name, ...entity.aliases].some(alias => normalizeEntityKey(alias) === normalized))?.id; if (id) setEntityId(id); else toast.info(`${label} ainda não possui verbete global; consulte a ficha local.`); };
  return <section className="genesis-relational-page">
    <div className="genesis-relational-top"><button className="back-action" onClick={close}><ArrowLeft size={15} /> Voltar aos 66 livros</button><div className="genesis-relational-actions"><span>Enciclopédia relacional · modelo 01/66</span><button className={`save-detail ${saved ? "is-saved" : ""}`} onClick={save}>{saved ? "Salvo" : "Salvar"}</button></div></div>
    <header className="genesis-relational-hero"><div><div className="genesis-relational-kicker"><span>Antigo Testamento · Pentateuco</span><span>50 capítulos · 9 arcos</span></div><h1>Gênesis <em>em rede.</em></h1><p>Não é apenas “o livro dos começos”. É a rede em que humanidade, família, terra, promessa, violência, exílio e providência começam a adquirir nomes.</p></div><div className="genesis-relational-question"><Compass size={19} /><span>Pergunta-guia</span><strong>Como Deus preserva a promessa quando cada família e cada geração falha?</strong></div></header>
    <div className="genesis-relational-stats"><div><strong>50</strong><span>capítulos em percurso</span></div><div><strong>15</strong><span>pessoas e povos</span></div><div><strong>10</strong><span>lugares cartografados</span></div><div><strong>7</strong><span>livros de continuidade</span></div></div>
    <nav className="genesis-relational-tabs" aria-label="Áreas do dossiê relacional de Gênesis">{tabs.map(tab => { const Icon = tab.icon; return <button key={tab.id} className={panel === tab.id ? "is-active" : ""} onClick={() => setPanel(tab.id)} aria-pressed={panel === tab.id}><Icon size={14} /><span>{tab.label}</span></button>; })}</nav>
    {panel === "overview" && <OverviewPanel onPanel={setPanel} />}
    {panel === "people" && <PeoplePanel query={query} setQuery={setQuery} entityType={entityType} setEntityType={setEntityType} entities={filteredEntities} selectedEntity={selectedEntity} setSelectedEntity={setSelectedEntity} openEntity={openEntity} />}
    {panel === "events" && <EventsPanel selectedEvent={selectedEvent} setSelectedEvent={setSelectedEvent} openEntity={openEntity} />}
    {panel === "map" && <MapPanel selectedPlace={selectedPlace} setSelectedPlace={setSelectedPlace} openEntity={openEntity} />}
    {panel === "prophecy" && <ProphecyPanel connectBook={connectBook} />}
    {panel === "continuity" && <ContinuityPanel connectBook={connectBook} />}
    {panel === "sources" && <SourcesPanel />}
    <section className="genesis-relational-margin"><div><span className="genesis-relational-small-label">Anotação de pesquisa</span><h2>O que esta rede <em>muda</em> na sua leitura?</h2></div><div><textarea value={note} onChange={event => setNote(event.target.value)} placeholder="Registre uma pergunta, conexão ou hipótese..." aria-label="Anotação de pesquisa sobre Gênesis" /><div className="genesis-relational-note-footer"><span>{note ? `${note.length} caracteres` : "Notas desta sessão"}</span><button onClick={() => toast.success("Anotação guardada nesta sessão.")}>Guardar <ArrowRight size={14} /></button></div></div></section>
    <EntityPanel entityId={entityId} close={() => setEntityId(null)} onOpenEntity={setEntityId} onOpenBook={connectBook} />
  </section>;
}

function OverviewPanel({ onPanel }: { onPanel: (panel: Panel) => void }) { return <div className="genesis-relational-body"><section className="genesis-relational-intro"><div><span className="genesis-relational-small-label">Como navegar</span><h2>Leia o livro como <em>uma história conectada.</em></h2></div><p>Abra uma pessoa para saber quem ela é, o que acontece com ela, onde ela aparece, quais conflitos carrega e como a Bíblia relê sua história. Depois, siga o mapa, os eventos e as continuidades.</p></section><section className="genesis-arcs"><div className="genesis-section-heading"><span className="genesis-relational-small-label">Percurso integral · 1–50</span><strong>O argumento em nove movimentos</strong></div>{genesisArcs.map((arc, index) => <article key={arc.range} className="genesis-arc-card"><span className="genesis-arc-number">{String(index + 1).padStart(2, "0")}</span><div><span className="genesis-arc-range">{arc.range}</span><h3>{arc.title}</h3><p>{arc.summary}</p><strong className="genesis-arc-question">{arc.question}</strong><div className="genesis-ref-row">{arc.entities.map(entity => <button key={entity} onClick={() => onPanel("people")}>{entity}</button>)}</div></div><ArrowRight size={15} /></article>)}</section><section className="genesis-chapter-bands"><div className="genesis-section-heading"><span className="genesis-relational-small-label">Índice de investigação</span><strong>50 capítulos, 9 portas de entrada</strong></div><div className="genesis-band-grid">{genesisChapterBands.map(band => <article key={band.range}><span>{band.range}</span><h3>{band.title}</h3><p>{band.question}</p></article>)}</div></section><div className="genesis-next-grid"><button onClick={() => onPanel("people")}><Users size={17} /><strong>Quem aparece?</strong><span>Adão, Eva, Abraão, Sara, Jacó, José e suas relações.</span><ArrowRight size={14} /></button><button onClick={() => onPanel("map")}><Map size={17} /><strong>Onde acontece?</strong><span>Éden, Ur, Harã, Canaã, Hebrom, Sodoma e Egito.</span><ArrowRight size={14} /></button><button onClick={() => onPanel("prophecy")}><Sparkles size={17} /><strong>O que continua?</strong><span>Semente, bênção, Judá, vida, serpente e nova criação.</span><ArrowRight size={14} /></button></div></div>; }

function PeoplePanel({ query, setQuery, entityType, setEntityType, entities, selectedEntity, setSelectedEntity, openEntity }: { query: string; setQuery: (value: string) => void; entityType: GenesisEntityType | "Todos"; setEntityType: (value: GenesisEntityType | "Todos") => void; entities: typeof genesisEntities; selectedEntity: typeof genesisEntities[number]; setSelectedEntity: (entity: typeof genesisEntities[number]) => void; openEntity: (label: string) => void }) { return <div className="genesis-relational-body"><section className="genesis-relational-intro"><div><span className="genesis-relational-small-label">Rede de personagens</span><h2>Quem é quem em <em>Gênesis?</em></h2></div><p>O personagem não é apenas uma biografia. É uma posição narrativa: quem fala, quem sofre, quem decide, quem é nomeado, quem muda e quem permanece como memória para os livros seguintes.</p></section><div className="genesis-people-toolbar"><div><Search size={15} /><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Buscar Adão, Abraão, queda, promessa..." aria-label="Buscar entidades de Gênesis" /></div><div>{(["Todos", "Pessoa", "Povo", "Instituição"] as const).map(type => <button key={type} className={entityType === type ? "is-active" : ""} onClick={() => setEntityType(type)}>{type}</button>)}</div></div><div className="genesis-people-layout"><div className="genesis-entity-list">{entities.map(entity => <button key={entity.id} className={selectedEntity.id === entity.id ? "is-active" : ""} onClick={() => setSelectedEntity(entity)}><span>{entity.type}</span><strong>{entity.name}</strong><small>{entity.role}</small></button>)}</div><article className="genesis-entity-detail"><div className="genesis-entity-detail-top"><span>{selectedEntity.type}</span><span>{selectedEntity.refs.length} referências-base</span></div><h3>{selectedEntity.name}</h3><strong>{selectedEntity.role}</strong><p className="genesis-entity-summary">{selectedEntity.summary}</p><p>{selectedEntity.narrative}</p><div className="genesis-entity-tags">{selectedEntity.tags.map(tag => <span key={tag}># {tag}</span>)}</div><div className="genesis-entity-refs"><span>Onde ler</span>{selectedEntity.refs.map(ref => <span key={ref}>{ref}</span>)}</div><button className="genesis-open-entity" onClick={() => openEntity(selectedEntity.name)}>Abrir verbete global <ArrowRight size={14} /></button></article></div></div>; }

function EventsPanel({ selectedEvent, setSelectedEvent, openEntity }: { selectedEvent: typeof genesisEvents[number]; setSelectedEvent: (event: typeof genesisEvents[number]) => void; openEntity: (label: string) => void }) { return <div className="genesis-relational-body"><section className="genesis-relational-intro"><div><span className="genesis-relational-small-label">Eventos e capítulos</span><h2>O que aconteceu e <em>o que mudou?</em></h2></div><p>Cada evento é lido em três níveis: o acontecimento narrado, a consequência dentro de Gênesis e as entidades que carregam a tensão para a cena seguinte.</p></section><div className="genesis-events-layout"><div className="genesis-event-list">{genesisEvents.map(event => <button key={event.id} className={selectedEvent.id === event.id ? "is-active" : ""} onClick={() => setSelectedEvent(event)}><span>{event.number}</span><div><strong>{event.title}</strong><small>{event.refs}</small></div><ArrowRight size={14} /></button>)}</div><article className="genesis-event-detail"><span className="genesis-event-ref">{selectedEvent.refs}</span><h3>{selectedEvent.title}</h3><p className="genesis-event-summary">{selectedEvent.summary}</p><div><span>O que muda</span><p>{selectedEvent.consequence}</p></div><div><span>Entidades relacionadas</span><div className="genesis-ref-row">{selectedEvent.entities.map(entity => <button key={entity} onClick={() => openEntity(entity)}>{entity}</button>)}</div></div></article></div></div>; }

function MapPanel({ selectedPlace, setSelectedPlace, openEntity }: { selectedPlace: typeof genesisPlaces[number]; setSelectedPlace: (place: typeof genesisPlaces[number]) => void; openEntity: (label: string) => void }) { return <div className="genesis-relational-body"><section className="genesis-relational-intro"><div><span className="genesis-relational-small-label">Geografia narrativa</span><h2>Onde a promessa <em>se move?</em></h2></div><p>O mapa diferencia lugares geográficos, espaços simbólicos e localizações disputadas. Não transforma uma geografia literária — como o Éden — em coordenada certa.</p></section><div className="genesis-map-layout"><div className="genesis-map-canvas"><div className="genesis-map-grid" /><svg viewBox="0 0 760 480" role="img" aria-label="Mapa esquemático das rotas narrativas de Gênesis"><path className="genesis-map-river" d="M540 64 C496 122 471 160 450 226 S353 335 285 406" /><path className="genesis-map-route genesis-map-route--warm" d="M562 77 C502 108 457 126 383 146 S267 205 237 288" /><path className="genesis-map-route genesis-map-route--wine" d="M237 288 C287 301 347 320 395 359 S353 417 292 428" /><path className="genesis-map-route genesis-map-route--blue" d="M383 146 C341 203 340 282 402 348 S465 407 514 429" />{genesisPlaces.map(place => <g key={place.id} className="genesis-map-point" onClick={() => setSelectedPlace(place)} role="button" tabIndex={0} aria-label={`Abrir ${place.name}`}><circle cx={`${place.x * 7.2}`} cy={`${place.y * 4.6}`} r={selectedPlace.id === place.id ? 10 : 6} /><circle className="genesis-map-point-ring" cx={`${place.x * 7.2}`} cy={`${place.y * 4.6}`} r="14" /></g>)}</svg><span className="genesis-map-north">N</span><div className="genesis-map-label genesis-map-label--east">Mesopotâmia</div><div className="genesis-map-label genesis-map-label--center">Canaã</div><div className="genesis-map-label genesis-map-label--south">Egito</div></div><aside className="genesis-place-detail"><span className="genesis-place-status">{selectedPlace.status}</span><h3>{selectedPlace.name}</h3><p>{selectedPlace.note}</p><span>Referências</span><div>{selectedPlace.refs.map(ref => <small key={ref}>{ref}</small>)}</div><button className="genesis-open-entity" onClick={() => openEntity(selectedPlace.name)}>Abrir lugar no atlas <Map size={14} /></button><div className="genesis-place-list">{genesisPlaces.map(place => <button key={place.id} className={selectedPlace.id === place.id ? "is-active" : ""} onClick={() => setSelectedPlace(place)}><span>{place.name}</span><small>{place.status}</small></button>)}</div></aside></div></div>; }

function ProphecyPanel({ connectBook }: { connectBook: (name: string) => void }) { return <div className="genesis-relational-body"><section className="genesis-relational-intro"><div><span className="genesis-relational-small-label">Grafo profético</span><h2>Promessas que <em>continuam andando.</em></h2></div><p>Uma referência cruzada não é uma prova automática de que um versículo “prediz” outro. Ela pode ser citação, alusão, tipologia, releitura teológica ou recepção posterior — e o dossiê precisa dizer qual é a relação.</p></section><div className="genesis-prophecy-list">{genesisProphecies.map(item => <article key={item.source}><div className="genesis-prophecy-source">{item.source}</div><div><h3>{item.title}</h3><p className="genesis-prophecy-reading">{item.reading}</p><div className="genesis-prophecy-connections">{item.connections.map(connection => <button key={connection} onClick={() => { const target = bibleBooks.find(book => connection.includes(book.name)); if (target) connectBook(target.name); else toast.info(`${connection} é uma ligação interpretativa dentro deste dossiê.`); }}>{connection}</button>)}</div><p className="genesis-prophecy-note"><ShieldCheck size={14} /> {item.note}</p></div></article>)}</div></div>; }

function ContinuityPanel({ connectBook }: { connectBook: (name: string) => void }) { return <div className="genesis-relational-body"><section className="genesis-relational-intro"><div><span className="genesis-relational-small-label">Do início ao fim</span><h2>Gênesis não termina em <em>Gênesis.</em></h2></div><p>O livro termina com uma família viva, mas fora da terra prometida e dentro do Egito. Cada conexão abaixo mostra como outros livros retomam, deslocam ou reimaginam suas perguntas.</p></section><div className="genesis-continuity-list">{genesisContinuity.map(item => <button key={item.book} onClick={() => connectBook(item.book)}><span>{item.refs}</span><div><h3>{item.book}</h3><p>{item.reason}</p></div><ArrowRight size={16} /></button>)}</div></div>; }

function SourcesPanel() { return <div className="genesis-relational-body"><section className="genesis-relational-intro"><div><span className="genesis-relational-small-label">Rastreabilidade</span><h2>Leia além do <em>resumo.</em></h2></div><p>Estas fontes orientam o dossiê. A plataforma deve mostrar o que o texto afirma, o que a história permite reconstruir, o que uma tradição confessa e onde a pesquisa permanece em debate.</p></section><div className="genesis-source-grid">{genesisSources.map(source => <a key={source.url} href={source.url} target="_blank" rel="noreferrer"><ExternalLink size={15} /><span>{source.label}</span><ArrowRight size={14} /></a>)}</div><div className="genesis-method-box"><ShieldCheck size={18} /><div><strong>Regra de método</strong><p>Não chamar uma hipótese acadêmica de fato bíblico, nem usar uma leitura cristológica posterior como se fosse o único sentido histórico de Gênesis.</p></div></div></div>; }
