import { useMemo, useState } from "react";
import { ArrowLeft, ArrowRight, BookOpen, Compass, ExternalLink, FileText, GitBranch, Map, Search, ShieldCheck, Sparkles, Users } from "lucide-react";
import { toast } from "sonner";
import { bibleBooks, type Book } from "@/lib/bible-data";
import { canonicalRelationalBookKey, type RelationalBookData, type RelationalRow, type RelationalSource } from "@/lib/relational-book-data";
import ExegesisBookReader from "@/components/ExegesisBookReader";
import EntityPanel from "@/components/EntityPanel";
import { getAllKnowledgeEntities, normalizeEntityKey } from "@/lib/entity-graph";
import "@/entity-link-controls.css";

type Props = { book: Book; data: RelationalBookData; saved: boolean; save: () => void; close: () => void; openBook: (book: Book) => void; note: string; setNote: (value: string) => void };
type Panel = "overview" | "entities" | "events" | "chapters" | "places" | "prophecies" | "continuity" | "sources";

function refs(value: string) { return value.split(/;|·/).map(item => item.trim()).filter(Boolean); }
function titleFrom(row: RelationalRow, keys: string[]) { return keys.map(key => row[key]).find(Boolean) || "Sem título"; }
function relatedBook(name: string) { return bibleBooks.find(item => canonicalRelationalBookKey(item.name) === canonicalRelationalBookKey(name)); }
function relationNames(value: string) { return value.split(/[;·|]/).map(item => item.trim()).filter(Boolean); }
function entityIdFromLabel(label: string) { const normalized = normalizeEntityKey(label); return getAllKnowledgeEntities().find(entity => [entity.name, ...entity.aliases].some(alias => normalizeEntityKey(alias) === normalized))?.id || null; }
function booksMentioned(value: string) { return bibleBooks.filter(book => new RegExp(`(^|[^\p{L}])${book.name.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}(?=$|[^\p{L}])`, "iu").test(value)); }

export default function RelationalBookDetail({ book, data, saved, save, close, openBook, note, setNote }: Props) {
  const [panel, setPanel] = useState<Panel>("overview");
  const [entityQuery, setEntityQuery] = useState("");
  const [entityType, setEntityType] = useState("Todos");
  const [selectedEntity, setSelectedEntity] = useState(data.entities[0]);
  const [selectedPlace, setSelectedPlace] = useState(data.places[0]);
  const [entityId, setEntityId] = useState<string | null>(null);
  const filteredEntities = useMemo(() => data.entities.filter(entity => (entityType === "Todos" || entity.type === entityType) && (!entityQuery.trim() || Object.values(entity).join(" ").toLowerCase().includes(entityQuery.toLowerCase().trim()))), [data.entities, entityQuery, entityType]);
  const index = bibleBooks.findIndex(item => item.id === book.id);
  const tabs: { id: Panel; label: string; icon: typeof BookOpen }[] = [
    { id: "overview", label: "Visão integral", icon: BookOpen },
    { id: "entities", label: "Pessoas e povos", icon: Users },
    { id: "events", label: "Eventos", icon: GitBranch },
    { id: "chapters", label: "Capítulos", icon: FileText },
    { id: "places", label: "Mapa e lugares", icon: Map },
    { id: "prophecies", label: "Profecias", icon: Sparkles },
    { id: "continuity", label: "Continuidade", icon: ArrowRight },
    { id: "sources", label: "Fontes", icon: ShieldCheck },
  ];
  const connectBook = (name: string) => { const target = relatedBook(name); if (target) openBook(target); else toast.info(`${name} será conectado na próxima camada.`); };
  const openEntity = (label: string) => { const id = entityIdFromLabel(label); if (id) setEntityId(id); else toast.info(`${label} ainda não possui verbete global; a ficha local permanece disponível.`); };
  return <section className="relational-book-page">
    <div className="relational-book-top"><button className="back-action" onClick={close}><ArrowLeft size={15} /> Voltar aos 66 livros</button><div className="relational-book-actions"><span>Enciclopédia relacional · modelo {String(index + 1).padStart(2, "0")}/66</span><button className={`save-detail ${saved ? "is-saved" : ""}`} onClick={save}>{saved ? "Salvo" : "Salvar"}</button></div></div>
    <header className="relational-book-hero"><div><div className="relational-book-kicker"><span>{book.testament} · {book.category}</span><span>{data.chapterCount || book.chapters} capítulos · {data.chapterArcs.length} arcos</span></div><h1>{book.name} <em>em rede.</em></h1><p>{data.identity}</p></div><div className="relational-book-question"><Compass size={19} /><span>Pergunta-guia</span><strong>O que este livro conecta, desloca e deixa em aberto na história bíblica?</strong></div></header>
    <div className="relational-book-stats"><div><strong>{data.chapterCount || book.chapters}</strong><span>capítulos</span></div><div><strong>{data.entities.length}</strong><span>entidades</span></div><div><strong>{data.places.length}</strong><span>lugares</span></div><div><strong>{data.continuity.length}</strong><span>conexões canônicas</span></div></div>
    <nav className="relational-book-tabs" aria-label={`Áreas do dossiê relacional de ${book.name}`}>{tabs.map(tab => { const Icon = tab.icon; return <button key={tab.id} className={panel === tab.id ? "is-active" : ""} onClick={() => setPanel(tab.id)} aria-pressed={panel === tab.id}><Icon size={14} /><span>{tab.label}</span></button>; })}</nav>
    {panel === "overview" && <Overview data={data} setPanel={setPanel} />}
    {panel === "entities" && <Entities data={data} query={entityQuery} setQuery={setEntityQuery} type={entityType} setType={setEntityType} filtered={filteredEntities} selected={selectedEntity} setSelected={setSelectedEntity} openEntity={openEntity} />}
    {panel === "events" && <Events data={data} openEntity={openEntity} />}
    {panel === "chapters" && <div className="relational-panel relational-panel--reader"><ExegesisBookReader book={book} onOpenBook={name => { const target = relatedBook(name); if (target) openBook(target); }} /></div>}
    {panel === "places" && <Places data={data} selected={selectedPlace} setSelected={setSelectedPlace} openEntity={openEntity} />}
    {panel === "prophecies" && <Prophecies data={data} connectBook={connectBook} />}
    {panel === "continuity" && <Continuity data={data} connectBook={connectBook} />}
    {panel === "sources" && <Sources data={data} />}
    <section className="relational-book-margin"><div><span className="relational-small-label">Anotação de pesquisa</span><h2>O que esta rede <em>muda</em> na sua leitura?</h2></div><div><textarea value={note} onChange={event => setNote(event.target.value)} placeholder={`Registre uma pergunta, conexão ou hipótese sobre ${book.name}...`} aria-label={`Anotação de pesquisa sobre ${book.name}`} /><div className="relational-note-footer"><span>{note ? `${note.length} caracteres` : "Notas desta sessão"}</span><button onClick={() => toast.success("Anotação guardada nesta sessão.")}>Guardar <ArrowRight size={14} /></button></div></div></section>
    <EntityPanel entityId={entityId} close={() => setEntityId(null)} onOpenEntity={setEntityId} onOpenBook={(bookName) => connectBook(bookName)} />
  </section>;
}

function Overview({ data, setPanel }: { data: RelationalBookData; setPanel: (panel: Panel) => void }) { return <div className="relational-panel"><section className="relational-intro"><div><span className="relational-small-label">Como navegar</span><h2>Leia o livro como <em>uma história conectada.</em></h2></div><p>Abra uma entidade para saber quem ela é e o que acontece com ela. Depois, siga os eventos, os lugares, as profecias e os livros que continuam suas perguntas.</p></section><section className="relational-arcs"><div className="relational-section-heading"><span className="relational-small-label">Percurso integral · {data.chapterCount} capítulos</span><strong>O argumento em {data.chapterArcs.length} movimentos</strong></div>{data.chapterArcs.map((arc, index) => <article key={`${arc.range}-${index}`} className="relational-arc-card"><span className="relational-arc-number">{String(index + 1).padStart(2, "0")}</span><div><span className="relational-arc-range">{arc.range}</span><h3>{arc.title}</h3><p>{arc.summary}</p>{arc.question && <strong className="relational-arc-question">{arc.question}</strong>}<div className="relational-ref-row"><button onClick={() => setPanel("entities")}>Abrir entidades</button><button onClick={() => setPanel("places")}>Abrir lugares</button><button onClick={() => setPanel("prophecies")}>Abrir profecias</button></div></div><ArrowRight size={15} /></article>)}</section><div className="relational-next-grid"><button onClick={() => setPanel("entities")}><Users size={17} /><strong>Quem aparece?</strong><span>{data.entities.slice(0, 5).map(item => titleFrom(item, ["name"])).join(", ")}.</span><ArrowRight size={14} /></button><button onClick={() => setPanel("places")}><Map size={17} /><strong>Onde acontece?</strong><span>{data.places.slice(0, 5).map(item => titleFrom(item, ["name"])).join(", ")}.</span><ArrowRight size={14} /></button><button onClick={() => setPanel("continuity")}><Sparkles size={17} /><strong>O que continua?</strong><span>{data.continuity.slice(0, 3).map(item => titleFrom(item, ["book"])).join(", ")} e outros fios.</span><ArrowRight size={14} /></button></div></div>; }

function Entities({ data, query, setQuery, type, setType, filtered, selected, setSelected, openEntity }: { data: RelationalBookData; query: string; setQuery: (value: string) => void; type: string; setType: (value: string) => void; filtered: RelationalRow[]; selected: RelationalRow; setSelected: (row: RelationalRow) => void; openEntity: (label: string) => void }) { const types = ["Todos", ...Array.from(new Set(data.entities.map(item => item.type).filter(Boolean)))]; return <div className="relational-panel"><section className="relational-intro"><div><span className="relational-small-label">Rede de entidades</span><h2>Quem é quem <em>neste livro?</em></h2></div><p>Uma entidade é uma posição dentro da narrativa: quem fala, sofre, decide, muda, é lembrado ou reaparece em outros textos.</p></section><div className="relational-toolbar"><div><Search size={15} /><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Buscar pessoa, povo, instituição ou conceito..." aria-label="Buscar entidades" /></div><div>{types.map(item => <button key={item} className={type === item ? "is-active" : ""} onClick={() => setType(item)}>{item}</button>)}</div></div><div className="relational-entity-layout"><div className="relational-entity-list">{filtered.map((entity, index) => <button key={`${entity.name}-${index}`} className={selected === entity ? "is-active" : ""} onClick={() => setSelected(entity)}><span>{entity.type}</span><strong>{entity.name}</strong><small>{entity.role}</small></button>)}</div>{selected && <article className="relational-entity-detail"><div className="relational-entity-detail-top"><span>{selected.type}</span><span>{refs(selected.refs).length || "—"} referências</span></div><h3>{selected.name}</h3><strong>{selected.role}</strong><p className="relational-entity-summary">{selected.summary}</p><p>{selected["function"] || selected.what || "A entidade é apresentada em relação ao argumento, aos conflitos e às consequências do livro."}</p><div className="relational-entity-refs"><span>Onde ler</span>{refs(selected.refs).map(ref => <span key={ref}>{ref}</span>)}</div><button className="relational-open-entity" onClick={() => openEntity(selected.name)}>Abrir verbete global <ArrowRight size={14} /></button></article>}</div></div>; }

function Events({ data, openEntity }: { data: RelationalBookData; openEntity: (label: string) => void }) { const [selected, setSelected] = useState(data.events[0]); if (!selected) return <div className="relational-panel"><p>Este dossiê ainda não tem eventos estruturados.</p></div>; return <div className="relational-panel"><section className="relational-intro"><div><span className="relational-small-label">Eventos e consequências</span><h2>O que aconteceu e <em>o que mudou?</em></h2></div><p>Cada evento é lido como acontecimento narrado, consequência no argumento e mudança nas relações de poder, promessa, culto ou comunidade.</p></section><div className="relational-event-layout"><div className="relational-event-list">{data.events.map((event, index) => <button key={`${event.title}-${index}`} className={selected === event ? "is-active" : ""} onClick={() => setSelected(event)}><span>{String(index + 1).padStart(2, "0")}</span><div><strong>{titleFrom(event, ["title"])}</strong><small>{event.chapters}</small></div><ArrowRight size={14} /></button>)}</div><article className="relational-event-detail"><span>{selected.chapters}</span><h3>{selected.title}</h3><p className="relational-entity-summary">{selected.what}</p><div><span>O que muda</span><p>{selected.consequence}</p></div><div><span>Entidades relacionadas</span><div className="relational-ref-row">{relationNames(selected.entities || "").map(entity => <button key={entity} onClick={() => openEntity(entity)}>{entity}</button>)}</div></div></article></div></div>; }

function Places({ data, selected, setSelected, openEntity }: { data: RelationalBookData; selected: RelationalRow; setSelected: (row: RelationalRow) => void; openEntity: (label: string) => void }) { return <div className="relational-panel"><section className="relational-intro"><div><span className="relational-small-label">Geografia narrativa</span><h2>Onde a história <em>se move?</em></h2></div><p>O mapa editorial diferencia lugar geográfico, espaço simbólico e localização disputada; não transforma uma geografia literária em coordenada certa.</p></section><div className="relational-place-layout"><div className="relational-map-canvas"><div className="relational-map-grid" /><div className="relational-map-water" /><span className="relational-map-label relational-map-label--one">Oriente Próximo</span><span className="relational-map-label relational-map-label--two">Cenário do livro</span>{data.places.map((place, index) => <button key={`${place.name}-${index}`} className={`relational-map-point ${selected === place ? "is-active" : ""}`} style={{ left: `${18 + ((index * 17) % 68)}%`, top: `${24 + ((index * 23) % 52)}%` }} onClick={() => setSelected(place)} aria-label={`Abrir ${place.name}`}><i /> <span>{place.name}</span></button>)}</div><aside className="relational-place-detail"><span>{selected?.status}</span><h3>{selected?.name}</h3><p>{selected?.function}</p><div><span>Referências</span>{refs(selected?.refs || "").map(ref => <small key={ref}>{ref}</small>)}</div><button className="relational-open-entity" onClick={() => openEntity(selected?.name || "")}>Abrir lugar no atlas <Map size={14} /></button><div className="relational-place-list">{data.places.map((place, index) => <button key={`${place.name}-${index}`} className={selected === place ? "is-active" : ""} onClick={() => setSelected(place)}><span>{place.name}</span><small>{place.status}</small></button>)}</div></aside></div></div>; }

function Prophecies({ data, connectBook }: { data: RelationalBookData; connectBook: (name: string) => void }) { const [selected, setSelected] = useState(data.prophecies[0]); if (!selected) return <div className="relational-panel"><p>Este dossiê não possui relações proféticas estruturadas.</p></div>; const books = booksMentioned(selected.connections || ""); return <div className="relational-panel"><section className="relational-intro"><div><span className="relational-small-label">Grafo profético</span><h2>Como o texto é <em>retomado?</em></h2></div><p>As referências são classificadas como citação, alusão, tipologia, oráculo ou recepção posterior. Relação não significa previsão automática.</p></section><div className="relational-prophecy-layout"><div className="relational-prophecy-list">{data.prophecies.map((item, index) => <button key={`${item.source}-${index}`} className={selected === item ? "is-active" : ""} onClick={() => setSelected(item)}><span>{item.type}</span><strong>{item.source}</strong><small>{item.connections}</small></button>)}</div><article className="relational-prophecy-detail"><span>{selected.type}</span><h3>{selected.source}</h3><p>{selected.interpretations}</p><div className="relational-entity-refs"><span>Textos relacionados</span>{refs(selected.connections).map(ref => <span key={ref}>{ref}</span>)}</div>{books.length > 0 && <div className="relational-ref-row">{books.map(book => <button key={book.id} onClick={() => connectBook(book.name)}>Abrir {book.name} <ArrowRight size={13} /></button>)}</div>}<div className="relational-method-box"><ShieldCheck size={16} /><p>Divergências devem ser lidas como parte da história da interpretação, não apagadas em nome de uma única teoria.</p></div></article></div></div>; }

function Continuity({ data, connectBook }: { data: RelationalBookData; connectBook: (name: string) => void }) { return <div className="relational-panel"><section className="relational-intro"><div><span className="relational-small-label">Do início ao fim</span><h2>Este livro não termina <em>nele mesmo.</em></h2></div><p>Cada conexão mostra como outro livro retoma, desloca, interpreta ou contesta uma pergunta do dossiê atual.</p></section><div className="relational-continuity-list">{data.continuity.map((item, index) => <button key={`${item.book}-${index}`} onClick={() => connectBook(item.book)}><span>{item.refs}</span><div><h3>{item.book}</h3><p>{item.reason}</p></div><ArrowRight size={16} /></button>)}</div></div>; }

function Sources({ data }: { data: RelationalBookData }) { const render = (items: RelationalSource[]) => <div className="relational-source-list">{items.map((source, index) => source.url ? <a key={`${source.label}-${index}`} href={source.url} target="_blank" rel="noreferrer"><ExternalLink size={15} /><span>{source.label}</span><ArrowRight size={14} /></a> : <div className="relational-source-unverified" key={`${source.label}-${index}`}><FileText size={15} /><span>{source.label}<small>URL a verificar</small></span></div>)}</div>; return <div className="relational-panel"><section className="relational-intro"><div><span className="relational-small-label">Rastreabilidade</span><h2>Leia além do <em>resumo.</em></h2></div><p>Fontes primárias e bibliografia acadêmica são pontos de partida; o dossiê distingue evidência, reconstrução, interpretação e confissão.</p></section><div className="relational-source-columns"><article><h3>Fontes primárias e institucionais</h3>{render(data.primarySources)}</article><article><h3>Bibliografia acadêmica</h3>{render(data.academicSources)}</article></div><div className="relational-method-box"><ShieldCheck size={18} /><p>{data.qualityNote}</p></div><div className="relational-layer-notes"><article><span>Leitura pentecostal</span><p>{data.pentecostal}</p></article><article><span>Posição IDB</span><p>{data.idbStatus}</p></article><article><span>Debates acadêmicos</span><p>{data.academicDebates.join(" ")}</p></article></div></div>; }
