// Cartografia de Leituras: índice de proveniência com filtros para evidência, método e confissão.

import { useMemo, useState } from "react";
import { ExternalLink, Filter, ShieldCheck } from "lucide-react";
import { confidenceLevels, sourceKinds, sourceLayers, sourceLedger, type ConfidenceLevel, type SourceKind, type SourceLayer } from "@/lib/source-ledger-data";
import "@/source-ledger.css";

export default function SourceLedger() {
  const [kind, setKind] = useState<SourceKind | "Todos">("Todos");
  const [layer, setLayer] = useState<SourceLayer | "Todas">("Todas");
  const [confidence, setConfidence] = useState<ConfidenceLevel | "Todas">("Todas");
  const [query, setQuery] = useState("");
  const records = useMemo(() => sourceLedger.filter(record => (kind === "Todos" || record.kind === kind) && (layer === "Todas" || record.layer === layer) && (confidence === "Todas" || record.confidence === confidence) && (!query.trim() || `${record.title} ${record.institution} ${record.scope} ${record.limit} ${record.related.join(" ")}`.toLowerCase().includes(query.toLowerCase().trim()))), [confidence, kind, layer, query]);
  return <section className="source-ledger" aria-labelledby="source-ledger-title"><header><div><div className="source-ledger-kicker"><span /> Proveniência e limites · ledger editorial</div><h2 id="source-ledger-title">Toda fonte tem<br /><em>um alcance.</em></h2><p>Use os filtros para separar testemunho material, pesquisa histórica, crítica textual, divulgação acadêmica e posição de fé. Link não é sinônimo de certeza.</p></div><div className="source-ledger-seal"><ShieldCheck size={19} /><strong>{records.length}</strong><span>fontes<br />visíveis</span></div></header><div className="source-ledger-tools"><label><span>Buscar</span><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Instituição, tema ou limite" aria-label="Buscar no ledger de fontes" /></label><div><Filter size={15} /><select value={kind} onChange={event => setKind(event.target.value as SourceKind | "Todos")} aria-label="Filtrar por tipo de fonte">{sourceKinds.map(option => <option key={option}>{option}</option>)}</select><select value={layer} onChange={event => setLayer(event.target.value as SourceLayer | "Todas")} aria-label="Filtrar por camada">{sourceLayers.map(option => <option key={option}>{option}</option>)}</select><select value={confidence} onChange={event => setConfidence(event.target.value as ConfidenceLevel | "Todas")} aria-label="Filtrar por confiança">{confidenceLevels.map(option => <option key={option}>{option}</option>)}</select></div></div><div className="source-ledger-grid">{records.map(record => <article key={record.id}><div className="source-ledger-card-top"><span>{record.kind}</span><b>{record.confidence}</b></div><h3>{record.title}</h3><small>{record.institution} · {record.layer}</small><p>{record.scope}</p><blockquote>Limite: {record.limit}</blockquote><div className="source-ledger-card-foot"><div>{record.related.map(tag => <span key={tag}>#{tag}</span>)}</div><a href={record.url} target="_blank" rel="noreferrer">Abrir fonte <ExternalLink size={13} /></a></div></article>)}{!records.length && <div className="source-ledger-empty">Nenhuma fonte corresponde a estes filtros.</div>}</div></section>;
}
