// Cartografia de Leituras: centro de percursos conectando Bíblia, atlas, personagens, temas e pesquisa pessoal.
// Cartografia de Leituras: estudos são percursos com estações, fontes e uma próxima ligação explícita.
import { useEffect, useMemo, useState } from "react";
import { ArrowRight, Bookmark, BookOpen, Check, Compass, Download, ExternalLink, Map, PenLine, Plus, Search, Sparkles, Target, Trash2 } from "lucide-react";
import DeepStudyReader from "@/components/DeepStudyReader";
import { readStudyState, writeStudyState, type StudyRoute, type StudyState } from "@/lib/study-store";
import { studyPaths, type StudyDestination, type StudyPath } from "@/lib/study-paths-data";
import { groupStudyCollections, type GroupStudyCollection } from "@/lib/group-study-collections";
import "@/study-paths-search.css";
import "@/teaching-kit.css";
import "@/study-paths-deep.css";
import "@/group-study-collections.css";

type StudyPathsHubProps = { go: (view: StudyDestination) => void };

export default function StudyPathsHub({ go }: StudyPathsHubProps) {
  const [activeId, setActiveId] = useState("escatologia-sem-atalhos");
  const [state, setState] = useState<StudyState>(() => readStudyState());
  const [title, setTitle] = useState("Meu roteiro de estudo");
  const [goal, setGoal] = useState("Organizar perguntas, textos e conexões para estudar com profundidade.");
  const [query, setQuery] = useState("");
  const [message, setMessage] = useState("");
  const active = studyPaths.find(path => path.id === activeId) || studyPaths[0];
  const filteredPaths = useMemo(() => { const normalized = query.trim().toLocaleLowerCase("pt-BR"); if (!normalized) return studyPaths; return studyPaths.filter(path => [path.title, path.category, path.lede, path.question, path.methodologicalNote, path.tags.join(" "), ...path.steps.flatMap(step => [step.title, step.references, step.summary])].join(" ").toLocaleLowerCase("pt-BR").includes(normalized)); }, [query]);
  const savedForActive = useMemo(() => state.routes.filter(route => route.pathId === active.id), [state.routes, active.id]);
  const deepStudyIds = ["escatologia-sem-atalhos", "financas-trabalho-generosidade", "espirito-dons-fruto-missao", "anjos-mensageiros-mundo-espiritual", "trindade-pai-filho-espirito", "oracao-lamento-discernimento"];
  const deepStudies = studyPaths.filter(path => deepStudyIds.includes(path.id));

  useEffect(() => writeStudyState(state), [state]);
  useEffect(() => { if (query.trim() && filteredPaths.length && !filteredPaths.some(path => path.id === activeId)) setActiveId(filteredPaths[0].id); }, [activeId, filteredPaths, query]);
  useEffect(() => { if (!message) return; const timer = window.setTimeout(() => setMessage(""), 2400); return () => window.clearTimeout(timer); }, [message]);

  const completeStep = (index: number) => {
    const id = `path-${active.id}-${index}`;
    setState(current => ({ ...current, completed: current.completed.includes(id) ? current.completed.filter(item => item !== id) : [...current.completed, id] }));
  };
  const saveRoute = () => {
    const routeTitle = title.trim();
    if (!routeTitle) { setMessage("Dê um nome ao seu roteiro antes de guardar."); return; }
    const route: StudyRoute = { id: `route-${Date.now()}`, title: routeTitle, goal: goal.trim(), pathId: active.id, stepIds: active.steps.map((_, index) => `path-${active.id}-${index}`), createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() };
    setState(current => ({ ...current, routes: [route, ...current.routes] }));
    setMessage("Roteiro guardado na sua mesa de estudo.");
  };
  const removeRoute = (id: string) => { setState(current => ({ ...current, routes: current.routes.filter(route => route.id !== id) })); setMessage("Roteiro removido deste navegador."); };
  const markPath = () => setState(current => ({ ...current, favorites: current.favorites.includes(active.id) ? current.favorites.filter(id => id !== active.id) : [...current.favorites, active.id] }));
  const exportRoute = (route: StudyRoute) => { const source = studyPaths.find(path => path.id === route.pathId); if (!source) return; const markdown = [`# ${route.title}`, "", `**Percurso:** ${source.title}`, `**Objetivo:** ${route.goal || "Sem objetivo registrado."}`, "", "## Pergunta-guia", source.question, "", "## Etapas", ...source.steps.map((step, index) => `- [${state.completed.includes(`path-${source.id}-${index}`) ? "x" : " "}] **${step.title}** — ${step.references}\n  ${step.summary}`), "", "## Limite metodológico", source.methodologicalNote, "", "---", "Gerado em A Bíblia em Visão Geral · roteiro pessoal local-first."].join("\n"); const blob = new Blob([markdown], { type: "text/markdown;charset=utf-8" }); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `${route.title.toLocaleLowerCase("pt-BR").normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "") || "roteiro-biblico"}.md`; anchor.click(); window.setTimeout(() => URL.revokeObjectURL(url), 0); setMessage("Roteiro exportado em Markdown para impressão ou aula."); };
  const exportTeachingKit = () => { const questions = [`O que o texto desta rota afirma antes de aplicarmos a nós mesmos?`, `Que contexto histórico, literário ou comunitário muda a maneira de ler ${active.title}?`, `Que pergunta permanece aberta depois deste encontro?`]; const markdown = [`# Kit de encontro — ${active.title}`, "", "## Pergunta-guia", active.question, "", "## Plano sugerido", ...active.steps.map((step, index) => `### Encontro ${index + 1} — ${step.title}\n**Textos:** ${step.references}\n${step.summary}`), "", "## Perguntas para o grupo", ...questions.map(question => `- ${question}`), "", "## Limite metodológico", active.methodologicalNote, "", "Gerado em A Bíblia em Visão Geral."].join("\n"); const blob = new Blob([markdown], { type: "text/markdown;charset=utf-8" }); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `kit-${active.id}.md`; anchor.click(); window.setTimeout(() => URL.revokeObjectURL(url), 0); setMessage("Kit de encontro exportado em Markdown."); };

  return <section className="study-paths page-section" aria-labelledby="study-paths-title">
    <header className="study-paths__hero">
      <div><span className="study-paths__kicker"><Compass size={15} /> Estudos profundos · textos, temas e doutrinas</span><h1 id="study-paths-title">Não procure só um tema.<br /><em>Estude-o a fundo.</em></h1><p>Escolha um estudo profundo, avance por textos, pessoas, mapas e fontes; depois transforme o caminho em um roteiro pessoal que permanece na sua mesa de estudo.</p></div>
      <div className="study-paths__hero-mark"><strong>{studyPaths.length}</strong><span>estudos<br />disponíveis</span><small>{state.routes.length} pessoais</small></div>
    </header>
    <div className="study-paths__entry"><div><span>Entrada em destaque · 12 estações</span><h2>Escatologia completa está aqui.</h2><p>Uma rota de Daniel a Apocalipse, com escolas interpretativas, símbolos, cidades, milênio, arrebatamento, juízo e nova criação.</p></div><button onClick={() => go("apocalypse")}>Abrir estudo escatológico <ArrowRight size={16} /></button></div>
    <div className="atlas-route-ledger study-paths-route-ledger" aria-label="Coordenadas do percurso ativo"><span>Rota ativa · {active.number}</span><strong>{active.category} <i /> pergunta <i /> textos <i /> debate <i /> próxima conexão</strong><em>{active.steps.length} estações nesta rota</em></div>
    <RouteSurvey active={active} />
    <section className="study-paths__deep" aria-labelledby="deep-studies-title"><header><span>Comece por aqui</span><h2 id="deep-studies-title">Estudos profundos <em>em destaque.</em></h2><p>Se você procura escatologia, finanças, espiritualidade, anjos ou Trindade, toque diretamente no tema. Cada estudo abre textos, contexto, perguntas e um percurso de investigação.</p></header><div className="study-paths__deep-grid">{deepStudies.map(path => <button key={path.id} className={active.id === path.id ? "is-active" : ""} onClick={() => setActiveId(path.id)}><span>{path.number}</span><div><small>{path.category}</small><strong>{path.title}</strong><p>{path.lede}</p></div><ArrowRight size={16} /></button>)}</div></section>
    <div className="study-paths__layout">
      <aside className="study-paths__index" aria-label="Índice de estudos profundos"><label className="study-paths__search"><Search size={15} /><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Buscar estudo, texto ou pergunta" aria-label="Buscar nos estudos profundos" /></label><div className="study-paths__result-count">{filteredPaths.length} de {studyPaths.length} estudos</div>{filteredPaths.map(path => <button key={path.id} className={active.id === path.id ? "is-active" : ""} onClick={() => setActiveId(path.id)}><span>{path.number}</span><div><small>{path.category}</small><strong>{path.title}</strong><em>{path.tags.join(" · ")}</em></div><ArrowRight size={15} /></button>)}{filteredPaths.length === 0 && <p className="study-paths__no-result">Nenhum estudo reúne esses termos. Tente um texto bíblico, tema ou pergunta.</p>}</aside>
      <article className="study-paths__detail"><header><div><span>{active.category}</span><h2>{active.title}</h2><p>{active.lede}</p></div><button className={state.favorites.includes(active.id) ? "is-saved" : ""} onClick={markPath} aria-label="Salvar percurso"><Bookmark size={17} />{state.favorites.includes(active.id) ? "Salvo" : "Salvar"}</button></header><div className="study-paths__question"><Target size={18} /><div><span>Pergunta-guia</span><strong>{active.question}</strong></div></div><div className="study-paths__source-plate"><span>Placa de fontes e relações</span><strong>{active.steps.map((step, index) => <i key={step.title}>{String(index + 1).padStart(2, "0")} · {step.references}</i>)}</strong><em>O percurso avança do texto à pergunta, do contexto ao debate, sem retirar a fonte de cena.</em></div><DeepStudyReader studyId={active.id} /><section className="teaching-kit"><header><div><span>Para aula, grupo ou discipulado</span><h3>Transforme esta rota em encontro.</h3></div><button onClick={exportTeachingKit}><Download size={14} /> Exportar kit</button></header><div className="teaching-kit__grid">{active.steps.slice(0, 2).map((step, index) => <article key={step.title}><span>Encontro {index + 1}</span><strong>{step.title}</strong><p><b>{step.references}</b><br />{step.summary}</p></article>)}</div><div className="teaching-kit__questions"><span>Perguntas para o grupo</span><ul><li>O que o texto afirma antes de qualquer aplicação?</li><li>Que contexto muda a leitura deste tema?</li><li>Que pergunta permanece aberta para a próxima etapa?</li></ul></div></section><div className="study-paths__method"><Sparkles size={16} /><p><strong>Limite metodológico:</strong> {active.methodologicalNote}</p></div><footer><button onClick={() => go(active.destination)}>{active.destination === "atlas" ? <Map size={15} /> : <BookOpen size={15} />}{active.destinationLabel} <ArrowRight size={14} /></button><span>{savedForActive.length ? `${savedForActive.length} roteiro(s) pessoal(is) nesta rota` : "Você ainda não salvou este percurso."}</span></footer></article>
    </div>
    <section className="study-paths__creator" aria-labelledby="creator-title"><div className="study-paths__creator-intro"><span><PenLine size={15} /> Oficina pessoal</span><h2 id="creator-title">Crie um estudo que faça sentido para sua pergunta.</h2><p>O roteiro salva título, objetivo, rota escolhida e os marcos que você pode concluir. Ele fica neste navegador e entra no backup da mesa de estudo.</p></div><div className="study-paths__creator-form"><label>Nome do roteiro<input value={title} onChange={event => setTitle(event.target.value)} placeholder="Ex.: Estudar generosidade e justiça" /></label><label>Objetivo de investigação<textarea value={goal} onChange={event => setGoal(event.target.value)} placeholder="Que pergunta você quer acompanhar?" /></label><button onClick={saveRoute}><Plus size={15} /> Guardar roteiro pessoal</button></div></section>
    <GroupStudyCollections />
    <section className="study-paths__saved"><header><span>Arquivo de pesquisa pessoal</span><h2>Roteiros guardados <em>nesta mesa.</em></h2></header>{state.routes.length === 0 ? <div className="study-paths__empty"><Compass size={23} /><p>Ainda não há roteiros pessoais. Escolha uma rota acima, dê um objetivo ao estudo e guarde o primeiro caminho.</p></div> : <div className="study-paths__saved-grid">{state.routes.map(route => { const source = studyPaths.find(path => path.id === route.pathId); return <article key={route.id}><span>{source?.number || "—"}</span><div><small>{source?.title || "Rota pessoal"}</small><h3>{route.title}</h3><p>{route.goal || "Sem objetivo registrado."}</p><strong>{route.stepIds.filter(id => state.completed.includes(id)).length}/{route.stepIds.length} marcos concluídos</strong></div><div><button onClick={() => setActiveId(route.pathId)} aria-label={`Abrir ${route.title}`}><ArrowRight size={15} /></button><button onClick={() => exportRoute(route)} aria-label={`Exportar ${route.title} em Markdown`}><Download size={15} /></button><button onClick={() => removeRoute(route.id)} aria-label={`Excluir ${route.title}`}><Trash2 size={15} /></button></div></article>; })}</div>}</section>
    {message && <div className="study-paths__toast" role="status"><Check size={15} />{message}</div>}
  </section>;
}

function GroupStudyCollections() {
  const [activeId, setActiveId] = useState(groupStudyCollections[0].id);
  const active = groupStudyCollections.find((collection) => collection.id === activeId) || groupStudyCollections[0];
  const exportCollection = (collection: GroupStudyCollection) => {
    const markdown = [`# ${collection.title}`, "", `**${collection.subtitle}**`, `**Público:** ${collection.audience}`, `**Duração:** ${collection.duration}`, "", "## Visão geral", collection.overview, "", "## Objetivos", ...collection.objectives.map((item) => `- ${item}`), "", "## Encontros", ...collection.sessions.flatMap((session) => [`### Encontro ${session.number} — ${session.title}`, `**Texto-base:** ${session.scripture}`, `**Objetivo:** ${session.aim}`, "", "**Movimento do encontro**", session.movement, "", "**Perguntas para conversa**", ...session.questions.map((question) => `- ${question}`), "", `**Prática para a semana:** ${session.practice}`, `**Foco do atlas:** ${session.atlas}`, `**Fonte de partida:** [${session.source.label}](${session.source.url})`, ""]), "## Nota ao facilitador", "Comece pelo texto bíblico, situe o encontro no contexto e preserve perguntas abertas. A prática sugerida não mede maturidade espiritual; ela ajuda o grupo a responder de modo concreto, comunitário e responsável.", "", "---", "Gerado em A Bíblia em Visão Geral · Coleções para Escola Dominical e pequenos grupos."].join("\n");
    const blob = new Blob([markdown], { type: "text/markdown;charset=utf-8" });
    const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `${collection.id}.md`; anchor.click(); window.setTimeout(() => URL.revokeObjectURL(url), 0);
  };
  return <section className="group-study-collections" aria-labelledby="group-study-collections-title"><header className="group-study-collections__head"><div><span>Arquivo para ensinar · roteiro imprimível</span><h2 id="group-study-collections-title">Coleções para a sala<br /><em>e para a roda.</em></h2><p>Escolha uma sequência, consulte as quatro estações e exporte o caderno em Markdown para adaptar à Escola Dominical, a jovens ou a pequenos grupos.</p></div><strong>{groupStudyCollections.length} coleções</strong></header><div className="group-study-collections__layout"><aside className="group-study-collections__index" aria-label="Coleções de ensino">{groupStudyCollections.map(collection => <button key={collection.id} type="button" className={collection.id === active.id ? "is-active" : ""} onClick={() => setActiveId(collection.id)}><span>{collection.code}</span><div><strong>{collection.title}</strong><small>{collection.duration}</small></div></button>)}</aside><article className="group-study-collections__sheet"><header><div><small>{active.audience} · {active.duration}</small><h3>{active.title}</h3><p>{active.overview}</p></div><button type="button" onClick={() => exportCollection(active)}><Download size={15} /> Exportar caderno</button></header><div className="group-study-collections__objectives">{active.objectives.map(objective => <span key={objective}>{objective}</span>)}</div><div className="group-study-collections__sessions">{active.sessions.map(session => <article key={session.number} className="group-study-collections__session"><span>{session.number}</span><strong>{session.scripture}</strong><h4>{session.title}</h4><p>{session.aim}</p><em>Atlas · {session.atlas}</em><a className="group-study-collections__source" href={session.source.url} target="_blank" rel="noreferrer">{session.source.label} <ExternalLink size={11} /></a></article>)}</div></article></div></section>;
}

function RouteSurvey({ active }: { active: StudyPath }) {
  const stations = ["Texto", "Contexto", "Pergunta", "Debate", "Fonte"];
  return <section className="study-paths__route-survey" aria-label="Mapa das camadas do percurso"><span>Leitura em coordenadas</span><div>{stations.map((station, index) => <article key={station}><i>{String(index + 1).padStart(2, "0")}</i><strong>{station}</strong><small>{index < active.steps.length ? active.steps[index].references : "Síntese e próxima conexão"}</small></article>)}</div><em>{active.steps.length} estações de investigação · escolha uma etapa no índice e volte à fonte</em></section>;
}
